<?php

echo IMAGETYPE_JPEG,PHP_EOL;
echo IMAGETYPE_GIF,PHP_EOL;
echo IMAGETYPE_PNG,PHP_EOL;
echo IMAGETYPE_WBMP,PHP_EOL;
echo IMAGETYPE_XBM,PHP_EOL;
echo IMAGETYPE_WEBP,PHP_EOL;
echo IMAGETYPE_BMP,PHP_EOL;

?>
