<?php

language::add_translations([

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Musik Sammlung",
	"button_file_browser" =>				"Datei Browser",
	"button_internet_radio" =>				"Internet Radio Stationen",
	"button_albumart" =>					"Album Art Manager",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Quellen Ansicht",
	"button_back" =>						"Zurück",
	"button_history" =>						"History",
	"button_forward" =>						"Vorwärts",
	"button_toggleplaylist" =>				"Toggle Playlist",

	// Tooltips for playlist buttons
	"button_alarm" =>						"Alarm Clock",
	"button_prefs" =>						"RompR Preferences",
	"button_clearplaylist" =>				"Leere Playlist",
	"button_loadplaylist" =>				"Lade gespeicherte Playlist",
	"button_saveplaylist" =>				"Sichere Playlist",

	// Tooltips for playback controls
	"button_previous" =>					"Vorheriger Titel",
	"button_play" =>						"Play/Pause",
	"button_stop" =>						"Stop",
	"button_stopafter" =>					"Stoppe nach aktuellem Titel",
	"button_next" =>						"Nächster Titel",
	"button_love" =>						"Ich liebe diesen Titel",
	"button_volume" =>						"Ziehen um Lautstärke einzustellen",

	// Configuration menu entries
	"config_theme" =>						"AUSSEHEN",
	"config_hidealbumlist" =>				"Verstecke Musik Sammlung",
	"config_hidefileslist" =>				"Verstecke Dateiliste",
	"config_hidelastfm" =>					"Verstecke Last.FM Radiosender",
	"config_hideradio" =>					"Verstecke Radiosender",
	"config_hidepodcasts" =>				"Verstecke Podcasts",
	"config_hideplaylistslist" =>			"Verstecke gespeicherte Wiedergabelisten",
	"config_hidepluginplaylistslist" =>		"Verstecke personalisierte Radiosender",
	"config_hidebrowser" =>					"Verstecke Infofenster",
	"config_lastfmlang" =>					"Sprache für Last.FM und Wikipedia",
	"config_lastfmdefault" =>				"Standardsprache (English)",
	"config_lastfminterface" =>				"Sprache der RompR-Oberfläche",
	"config_lastfmbrowser" =>				"Browser Standardsprache",
	"config_autoscroll" =>					"Auto-Scroll Playlist zum aktuellen Titel",
	"config_autocovers" =>					"Automatisch Cover herunterladen",
	"config_musicfolders" =>				"Um automatisch Coverart von Ihren Musikverzeichnissen zu nutzen, geben Sie bitte den Pfad zu Ihrer Musiksammlung in dieses Feld ein:",
	"config_crossfade" =>					"Crossfade Dauer (Sekunden)",
	"config_doubleclick" =>					"Doppel-Klick zum Hinzufügen, Klick zum Auswählen",
	"config_singleclick" =>					"Klick zum Hinzufügen, keine Auswahl",
	"config_sortbydate" =>					"Sortiere Alben nach Datum",
	"config_notvabydate" =>					"Keine Sortierung nach Datum bei 'Verschiedene Künstler'",
	"config_updateonstart" =>				"Musiksammlung beim Start automatisch aktualisieren",
	"config_updatenow" =>					"Musiksammlung jetzt aktualisieren",
	"config_rescan" =>						"Musiksammlung vollständig neu einlesen",
	"config_editshortcuts" =>				"Editiere Tastaturkürzel ...",
	"config_audiooutputs" =>				"Audioausgänge",
	"config_lastfmusername" =>				"Last.FM Benutzername",
	"config_loginbutton" =>					"Anmeldung",
	"config_scrobbling" =>					"Last.FM Scrobbling einschalten",
	"config_scrobblepercent" =>				"Wieviel Prozent des Titels müssen vor dem Scrobbeln abgespielt sein (Standard: 50%)",
	"config_autocorrect" =>					"Last.FM Autokorrektur eingeschaltet",
	"config_tagloved" =>					"Tagge Lieblingstitel mit:",
	"config_country" =>						"LAND (für Spotify)",
	"config_fontsize" =>					"FONT-GRÖSSE",
	"config_fontname" =>					"FONT-STIL",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Sichern",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Musiksammlung durchsuchen",
	"button_searchfiles" =>					"Dateisuche",
	"label_yourradio" =>					"Ihre Radio Sender",
	"label_podcasts" =>						"Podcasts",
	"label_somafm" =>						"Soma FM",
	"label_bbcradio" =>						"Live BBC Radio",
	"label_emptyinfo" =>					"Dies ist das Informationsfenster. Interessante Informationen erscheinen hier sobald Sie Musik abspielen",
	"button_playlistcontrols" =>			"Playlist Kontrollfenster",
	"button_random" =>						"ZUFALLSAUSWAHL",
	"button_crossfade" =>					"CROSSFADE",
	"button_repeat" =>						"WIEDERHOLEN",
	"button_consume" =>						"NACH APSPIELEN LÖSCHEN",
	"label_yes" =>							"Ja",
	"label_no" =>							"Nein",
	"label_updating" =>						"Aktualisiere Musiksammlung",
	"label_update_error" =>					"Erstellen der Musiksammlung gescheitert!",
	"label_playlisterror" =>				"Etwas ist beim Empfang der Playlist falsch gelaufen!",
	"label_mpd_no" =>						"MPD kann die Lautstärke nicht anpassen, wenn die Wiedergabe gestoppt ist",
	"button_OK" =>							"OK",
	"button_cancel" =>						"Abbruch",
	"error_playlistname" =>					"Playlist Name darf keine Schrägstriche enthalten",
	"label_savedpl" =>						"Playlist gesichert als %s",

	// Search Forms
	"label_searchfor" =>					"Suche nach",
	"label_searching" =>					"Suche...",
	"label_searchresults" =>				"Suchergebnisse",

	// General multipurpose labels
	"label_tracks" =>						"Titel",
	"label_albums" =>						"Alben",
	"label_artists" =>						"Künstler/in",
	"label_track" =>						"Titel",
	"label_album" =>						"Album",
	"label_artist" =>						"Künstler/in",
	"label_anything" =>						"Irgendetwas",
	"label_genre" =>						"Genre",
	"label_composer" =>						"Komponist",
	"label_performer" =>					"Interpret",
	"label_rating" =>						"Rating",
	"label_tag" =>							"Tag",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"Fehler. Bitte laden Sie die Seite neu und versuchen es noch einmal!",
	"label_days" =>							"Tage",
	"label_noalbums" =>						"Es wurde kein entsprechendes Album gefunden",
	"label_duration" =>						"Dauer",
	"label_playererror" =>					"Abspielfehler",
	"button_playradio" =>					"Abspielen",

	// Playlist and Now Playing
	"label_notforradio" =>					"Not supported for radio streams",
	"label_incoming" =>						"Lade...",
	"label_addingtracks" =>					"Füge Titel hinzu",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"von",
	"label_on" =>							"auf",
    // Now playing - 1:45 of 6:50
	"label_of" =>							"von",

	// Podcasts
	"podcast_entrybox" =>					"Geben Sie die URL eines Podacast RSS Feeds hier ein oder ziehen Sie das Icon hierhin",
	// Podcast tooltips
	"podcast_delete" =>						"Lösche diesen Podcast",
	"podcast_configure" =>					"Konfiguriere diesen Podcast",
	"podcast_refresh" =>					"Lösche diesen Podcast",
	"podcast_download_all" =>				"Lade alle Episoden dieses Podcasts herunter",
	"podcast_mark_all" =>					"Mark All Episodes as Listened",
	// Podcast display options
	"podcast_display" =>					"Anzeige",
	"podcast_display_all" =>				"Alles",
	"podcast_display_onlynew" =>			"Nur Neues",
	"podcast_display_unlistened" =>			"Neu und nicht aufgeführt",
	"podcast_display_downloadnew" =>		"Neu und Heruntergeladen",
	"podcast_display_downloaded" =>			"Nur Heruntergeladen",
	// Podcast refresh options
	"podcast_refresh" =>					"Aktualisiere",
	"podcast_refresh_never" =>				"Manuell",
	"podcast_refresh_hourly" =>				"Stündlich",
	"podcast_refresh_daily" =>				"Täglich",
	"podcast_refresh_weekly" =>				"Wöchentlich",
	"podcast_refresh_monthly" =>			"Monatlich",
	// Podcast auto expire
	"podcast_expire" =>						"Behalte Episoden für",
	"podcast_expire_tooltip" =>				"Alle Episoden älter als dieser Wert werden aus der Liste gelöscht. Änderungen an diesem Wert werden bei der nächsten Aktualisierung des Podcastsaktiv",
	"podcast_expire_never" =>				"Immer",
	"podcast_expire_week" =>				"Eine Woche",
	"podcast_expire_2week" =>				"Zwei Wochen",
	"podcast_expire_month" =>				"Ein Monat",
	"podcast_expire_2month" =>				"Zwei Monate",
	"podcast_expire_6month" =>				"Sechs Monate",
	"podcast_expire_year" =>				"Ein Jahr",
	// Podcast number to keep
	"podcast_keep" =>						"Maximale Anzahl",
	"podcast_keep_tooltip" =>				"Diese Liste wird immer nur so viele Einträge anzeigen wie angebenDiese Liste wird immer nur so viele Einträge anzeigen wie angegeben. Änderungen an dieser Option werden bei der nächsten Aktualisierung des Podcasts aktiv",
	"podcast_keep_0" =>						"Unbegrenzt",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Halte alle heruntergeladenen Episoden",
	"podcast_kd_tooltip" =>					"Diese Liste wird immer nur so viele Einträge anzeigen wie angegeben. Änderungen an dieser Option werden bei der nächsten Aktualisierung des Podcasts aktiv",
	"podcast_tooltip_new" =>				"Dies ist eine neue Episode",
	"podcast_tooltip_notnew" =>				"Diese Episode ist nicht neu, wurde aber bisher nicht angezeigt",
	"podcast_tooltip_downloaded" =>			"Diese Episode wurde herunter geladen",
	"podcast_tooltip_download" =>			"Laden Sie diese Episode auf Ihren Computer herunter",
	"podcast_tooltip_mark" =>				"Als Gehört markieren",
	"podcast_tooltip_delepisode" =>			"Lösche diese Episode",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Bitte überlegen Sie sich, ob Sie diesen Sender unterstützen wollen, falls Ihnen die Sendungen gefallen",

	// Your radio stations
	"label_radioinput" =>					"Geben Sie die URL",

	//Album Art Manager
	"albumart_title" =>						"Album Art",
	"albumart_getmissing" =>				"Hole fehlende Cover",
	"albumart_showall" =>					"Zeige alle Cover",
	"albumart_instructions" =>				"Klicken Sie ein Cover an, um es zu ändern oder ziehen Sie ein Bild von Ihrer Festplatte oder aus einem anderen Browserfenster hierhin",
	"albumart_onlyempty" =>					"Zeige nur Alben ohne Cover",
	"albumart_allartists" =>				"Alle Künstler/innen",
	"albumart_googlesearch" =>				"Bing Suche",
	"albumart_local" =>						"Lokale Bilder",
	"albumart_upload" =>					"Datei Upload",
	"albumart_uploadbutton" =>				"Upload",
	"albumart_newtab" =>					"Google Suche in neuer Registerkarte",
	"albumart_dragdrop" =>					"Sie können mit Drag & Drop Bilder von Ihrer Festplatte oder aus einem anderen Browserfenster direkt auf dieses Bild ziehen (funktioniert mit den meisten Browsern)",
	"albumart_showmore" =>					"Zeige mehr Resultate",
	"albumart_googleproblem" =>				"Es gab ein Problem. Bing meldet",
	"albumart_getthese" =>					"Hole diese Cover",
	"albumart_nocovercount" =>				"Alben ohne Cover",
	"albumart_getting" =>					"Hole",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"RompR konnte sich nicht mit einem MPD oder Mopidy Server verbinden",
	"setup_connecterror" =>					"Es gab einen Fehler bei der Kommunikation mit Ihrem MPD oder Mopidy Server: ",
	"setup_request" =>						"Sie haben die Setup-Seite aufgerufen",
	"setup_labeladdresses" =>				"Bitte geben Sie die IP Adresse und den Port Ihres MPD Servers in dieser Maske ein",
	"setup_addressnote" =>					"Anmerkung: localhost meint in diesem Zusammenhang den Computer auf dem der Apache Webserver läuft",
	"setup_ipaddress" =>					"IP Adresse oder Hostname",
	"setup_port" =>							"Port",
	"setup_advanced" =>						"Fortgeschrittene Optionen",
	"setup_password" =>						"Passwort",
	"setup_unixsocket" =>					"UNIX-Domain Socket",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Log In zu Last.FM",
	"lastfm_login1" =>						"Bitte den Button unten anklicken, um die Last.FM Website in einer neuen Registerkarte zu öffnen. Geben Sie Ihre Last.FM Login Daten ein falls nötig und geben dann RompR die Erlaubnis Ihren Account zu nutzen!",
	"lastfm_login2" =>						"Sie können die neue Registerkarte schließen, wenn Sie mit den Eingaben fertig sind, aber schließen Sie nicht dieses Dialogfenster!",
	"lastfm_loginbutton" =>					"Hier klicken, um sich anzumelden",
	"lastfm_login3" =>						"Nachdem Sie sich bei Last.FM angemeldet haben, den OK-Button anklicken, um den Prozess abzuschließen",
	"lastfm_loginfailed" =>					"Anmeldung bei Last.FM fehlgeschlagen",
	"label_loved" =>						"Lieblingstitel",
	"label_lovefailed" =>					"Markierung als Lieblingstitel fehlgeschlagen",
	"label_unloved" =>						"Markierung als Lieblingstitel entfernt",
	"label_unlovefailed" =>					"Entfernen der Lieblingstitel-Markierung fehlgeschlagen",
	"label_scrobblefailed" =>				"Scrobble fehlgeschlagen",

	// Info Panel
	"info_gettinginfo" =>					"Hole Info...",
	"info_newtab" =>						"In neuer Registerkarte betrachten",

	// File Info panel
	"button_fileinfo" =>					"Info Panel (Datei Information)",
	"info_file" =>							"Datei:",
	"info_from_beets" =>					"(vom Beets Server)",
	"info_format" =>						"Format:",
	"info_bitrate" =>						"Bitrate:",
	"info_samplerate" =>					"Sample Rate:",
	"info_mono" =>							"Mono",
	"info_stereo" =>						"Stereo",
	"info_channels" =>						"Kanäle",
	"info_date" =>							"Datum:",
	"info_genre" =>							"Genre:",
	"info_performers" =>					"Interpreten:",
	"info_composers" =>						"Komponisten:",
	"info_comment" =>						"Kommentar:",
	"info_label" =>							"Label:",
	"info_disctitle" =>						"Disk Titel:",
	"info_encoder" =>						"Encoder:",
	"info_year" =>							"Jahr:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Info Panel (Last.FM)",
	"label_notrackinfo" =>					"Konnte keine Informationen zu diesem Titel finden",
	"label_noalbuminfo" =>					"Konnte keine Informationen zu diesem Album finden",
	"label_noartistinfo" =>					"Konnte keine Informationen zu diesem Künstler / dieser Künstlerin finden",
	"lastfm_listeners" =>					"Hörer/innen:",
	"lastfm_plays" =>						"Spielt:",
	"lastfm_yourplays" =>					"Sie haben abgespielt::",
	"lastfm_toptags" =>						"TOP TAGS:",
	"lastfm_addtags" =>						"TAGS hinzufügen",
	"lastfm_addtagslabel" =>				"Tags, Komma getrennt, hinzufügen",
	"button_add" =>							"Hinzufügen",
	"lastfm_yourtags" =>					"IHRE TAGS:",
	"lastfm_simar" =>						"Ähnliche Künstler/innen",
	"lastfm_removetag" =>					"Tag entfernen",
	"lastfm_releasedate" =>					"Veröffentlichungsdatum",
	"lastfm_viewtrack" =>					"Titel auf Last.FM ansehen",
	"lastfm_tagerror" =>					"Ändern der Tags fehlgeschlagen",
	"lastfm_loved" =>						"Lieblingstitel",
	"lastfm_lovethis" =>					"Lieblingsstück",
	"lastfm_unlove" =>						"Kein Lieblingsstück mehr",
	"lastfm_notfound" =>					"%s Nicht gefunden",

	// Lyrics info panel
	"button_lyrics" =>						"Info Panel (Liedtexte)",
	"lyrics_lyrics" =>						"Liedtexte",
	"lyrics_nonefound" =>					"Kein Liedtext gefunden",
	"lyrics_info" =>						"Um Liedtexte anzusehen, stellen Sie bitte sicher, dass Ihre lokalen Dateien mit Liedtexten versehen wurden",
	"lyrics_nopath" =>						"Um Liedtexte anzusehen, stellen Sie bitte sicher, dass Ihre lokalen Dateien mit Liedtexten versehen wurden und setzen Sie den Pfad zu Ihren Musikdateien in den Voreinstellungen",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"JAHR",
	"title_title" =>						"TITEL",
	"title_type" =>							"ART",
	"title_label" =>						"LABEL",
	"label_pages" =>						"SEITEN",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"PLATTENFIRMA",
	"discogs_personnel" =>					"BESETZUNG",
	"discogs_videos" =>						"VIDEOS",
	"discogs_styles" =>						"MUSIKRICHTUNG",
	"discogs_genres" =>						"GENRES",
	"discogs_tracklisting" =>				"TITELLISTE",
	"discogs_realname" =>					"RICHTIGER NAME:",
	"discogs_aliases" =>					"ALIAS:",
	"discogs_alsoknown" =>					"AUCH BEKANNT ALS:",
	"discogs_external" =>					"EXTERNE VERKNÜPFUNG",
	"discogs_bandmembers" =>				"BAND MITGLIEDER",
	"discogs_memberof" =>					"MITGLIED VON",
	"discogs_discography" =>				"%s DISCOGRAPHIE",

	// Discogs info panel
	"button_discogs" =>						"Info Panel (Discogs)",
	"discogs_error" =>						"Netzwerkfehler oder keine Antwort von Discogs",
	"discogs_nonsense" =>					"Konnte keine sinnvolle Antwort von Discogs bekommen",
	"discogs_noalbum" =>					"Konnte dieses Album nicht auf Discogs finden",
	"discogs_notrack" =>					"Konnte diesen Titel nicht auf Discogs finden",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Info Panel (Musicbrainz)",
	"musicbrainz_error" =>					"Keine Antwort von MusicBrainz",
	"musicbrainz_contacterror" =>			"Es gab einen Fehler beim Verbindungsversuch zu Musicbrainz",
	"musicbrainz_noartist" =>				"Konnte diesen Künstler / diese Künstlerin nicht auf Musicbrainz finden",
	"musicbrainz_noalbum" =>				"Konnte dieses Album nicht auf Musicbrainz finden",
	"musicbrainz_notrack" =>				"Konnte diesen Titel nicht auf Musicbrainz finden",
	"musicbrainz_noinfo" =>					"Konnte keine Information von Musicbrainz holen",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Aktuell",
	"musicbrainz_origin" =>					"HERKUNFT",
	"musicbrainz_active" =>					"AKTIV",
	"musicbrainz_rating" =>					"BEWERTUNG",
	"musicbrainz_notes" =>					"ANMERKUNGEN",
	"musicbrainz_tags" =>					"TAGS",
	"musicbrainz_externaldiscography" =>		"Discographie (%s)",
	"musicbrainz_officalhomepage" =>		"Offizielle Homepage (%s)",
	"musicbrainz_fansite" =>				"Fan Site (%s)",
	"musicbrainz_lyrics" =>					"Liedtexte (%s)",
	"musicbrainz_social" =>					"Social Network",
	"musicbrainz_microblog" =>				"Mikroblog",
	"musicbrainz_review" =>					"Bewertung (%s)",
	"musicbrainz_novotes" =>				"(Keine Stimmen)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 von %s Bewertungen",
	"musicbrainz_appears" =>				"VERÖFFENTLICHT AUF",
	"musicbrainz_credits" =>				"CREDITS",
	"musicbrainz_status" =>					"STATUS",
	"musicbrainz_date" =>					"DATUM",
	"musicbrainz_country" =>				"LAND",
	"musicbrainz_disc" =>					"DISK",

	// SoundCloud info panel
	"button_soundcloud" =>					"Info Panel (SoundCloud)",
	"soundcloud_trackinfo" =>				"Titel Info",
	"soundcloud_plays" =>					"Spielt",
	"soundcloud_downloads" =>				"Downloads",
	"soundcloud_faves" =>					"Favoriten",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"Status",
	"soundcloud_license" =>					"Lizens",
	"soundcloud_buy" =>						"Kaufe Titel",
	"soundcloud_view" =>					"Auf SoundCloud ansehen",
	"soundcloud_user" =>					"SoundCloud Benutzer",
	"soundcloud_fullname" =>				"Vollständiger Name",
	"soundcloud_Country" =>					"Land",
	"soundcloud_city" =>					"Stadt",
	"soundcloud_website" =>					"Website besuchen",
	"soundcloud_not" =>						"Dieses Fenster zeigt nur Information über Musik aus der Soundcloud",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Info Panel (Wikipedia)",
	"wiki_nothing" =>						"Nichts in der Wikipedia gefunden",
	"wiki_fail" =>							"Wikipedia konnte nichts in Verbindung mit '%s' finden",
	"wiki_suggest" =>						"Wikipedia konnte keine passenden Seiten zu '%s' finden",
	"wiki_suggest2" =>						"Hier sind einige Vorschläge die Wikipedia gemacht hat",

	// Keybindings editor
	"title_keybindings" =>					"Tastaturkürzel",
	"button_volup" =>						"Lauter",
	"button_voldown" =>						"Leiser",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"Sterne",
	"star" =>								"Stern",
	"label_tags" =>							"Tags",
	"label_wishlist" =>						"Wunschliste",
	"label_viewwishlist" =>					"Wunschliste ansehen",
	"label_addtow" =>						"Zu Wunschliste hinzugefügt",
	"config_synctags" =>					"Halte Tags synchron mit Last.FM",
	"config_loveis" =>						"Last.FM Lieblingslied bedeutet",
	"playlist_xstar" =>						"%s oder mehr Sterne",
	"button_about" =>						"Über RompR",
	"label_notfound" =>						"Titel Nicht gefunden",
	// Eg + 3 more
	"label_tagmanager" =>					"Tag Verwaltung",
	"label_ratingmanager" =>				"Bewertungsverwaltung",

	//New in 0.52
	"config_alarm_ramp" =>					"Einblenden",

        // New in 0.60
	"spotify_error" =>						"Keine Antwort von Spotify",
	"spotify_noinfo" =>						"Konnte keine Informationen von Spotify beziehen",
	"button_infospotify" =>					"Info Feld (Spotify)",
	"config_icontheme" =>					"ICONS",
	"label_radio" =>						"Radio",
	"label_pop" =>							"Popularität",
	"label_albumsby" =>						"Alben von dieser Künstlerin / diesem Künstler",
	"label_singleartistradio" =>			"Titel nach Künstler/in",
	"label_mostplayed" =>					"Meist gespielt",
	"label_neverplayed" =>					"Nie gespielt",
	"label_radio_fartist" =>				"Lieblingskünstler/in Radio",
	"label_pluginplaylists" =>				"Eigene Radio Playlist",
	"label_recentlyadded_random" =>			"Kürzlich hinzugefügte Titel (Zufallsauswahl)",
	"label_recentlyadded_byalbum" =>		"Kürzlich hinzugefügte Alben",
	"setup_mpd" =>							"MPD/Mopidy Einstellungen",
	"settings_appearance" =>				"Erscheinungsbild",
	"settings_panels" =>					"Einstellungen",
	"settings_language" =>					"Sprache",
	"settings_interface" =>					"Interface",
	"label_charts" =>						"Deine Top 40",
	"button_subscribe" =>					"Abonnieren",
	"config_sortbycomposer" =>				"Benutze Komponist als Sortierfeld",
	"config_composergenre" =>				" .. nur wenn Genre gleich:",
	"config_displaycomposer" =>				"Zeige Komponist / Interpret in Aktuell läuft",
	"label_radio_mix" =>					"Spotify Recommendations",
	"label_gotnotracks" =>					"Keine Titel gefunden",
	"config_artistfirst" =>					"Künstler an der Spitze der Sammlung",
	"config_nosortprefixes" =>				"Ignoriere diese Präfixe beim Sortieren von Künstler/innen",
	"button_skipforward" =>					"Nach vorne Springen",
	"button_skipbackward" =>				"Zurück Springen",
	"config_snoozetime" =>					"Schlummern (Minuten)",
	"config_ramptime" =>					"Einblenden (Sekunden)",
	"button_rateone" =>						"Bewertung 1 Stern",
	"button_ratetwo" =>						"Bewertung 2 Sterne",
	"button_ratethree" =>					"Bewertung 3 Sterne",
	"button_ratefour" =>					"Bewertung 4 Sterne",
	"button_ratefive" =>					"Bewertung 5 Sterne",
	"button_updatecollection" =>			"Aktualisiere Musik Sammlung",
	"label_favealbums" =>					"Lieblingsalben",
	"button_nextsource" =>					"Info Feld - Nächste Quelle",
	"button_infopanel" =>					"Info Feld",
	"config_coversize" =>					"ALBUM COVER GRÖSSE",
	"podcast_sortmode" =>					"Sortier Reihenfolge",
	"podcast_newestfirst" =>				"Neuestes zuerst",
	"podcast_oldestfirst" =>				"Ältestes zuerst",
	"podcast_hidedescriptions" =>			"Verstecke Beschreibungen",

        // New in 0.64/0.65/0.70
	"label_metabackup" =>					"Metadaten Sicherung",
	"button_backup" =>						"Erzeuge Sicherung",
	"button_restore" =>						"Sicherung wiederherstellen",
	"button_collectioncontrols" =>			"Musik Sammlung Sortier Optionen",
	"button_createplaylist" =>				"ERZEUGE PLAYLIST",
	"label_renameplaylist" =>				"Playlist umbenennen",
	"button_plugins" =>						"Alles Mögliche",
	"label_filename" =>						"Dateiname",
	"label_resultscollection" =>			"Sammlung",
	"label_resultstree" =>					"Verzeichnisbaum",
	"label_displayresultsas" =>				"Zeige Ergebnisse als:",
	"label_files" =>						"Dateien",
	"label_albumartist" =>					"Album Künstler/in",
	"config_collectionfolders" =>			"Bilde Sammlung von:",
	"button_videos" =>						"Ähnliche Videos",
	"label_allrandom" =>					"Zufallswiedergabe aller Titel",
	"config_background" =>					"HINTERGRUNDBILD",
	"lastfm_error" =>						"Konnte keine passenden Informationen auf Last.FM finden",
	"config_skin" =>						"AUSSEHEN",

        // New in 0.71
	"label_albumsbyartist" =>				"Alben (nach Künstler/in)",
	"config_wheelspeed" =>					"Mausrad Geschwindigkeit",

        //CHANGED in 0.60
	"config_country" =>						"LAND (für Last.FM und Spotify)",
	"setup_labeladdresses" =>				"Bei Verbindungsproblemen IP Addresse statt 'localhost' benutzen",
	"setup_ipaddress" =>					"Mopidy oder MPD Server",

	"config_cdplayermode" =>				"CD Player Modus (Stelle Stücke nicht in die Wartechlange, starte Wiedergabe mit gewähltem Stück)",

	"label_recentlyplayed" =>				"Kürzlich gespielte Stücke",
	"label_simar_radio" =>					"Ähnliche Künstler wie",

	"label_tradsearch" =>					"Klassische Suche mit mehreren Suchbegriffen",

	"played_never" =>						"Dieses Stück wurde noch nie gespielt",
	"played_once" =>						"Dieses Stück wurde einmal gespielt",
	"played_twice" =>						"Dieses Stück wurde zweimal gespielt",
	"played_n" =>							"Dieses Stück wurde %s Mal gespielt",
	"played_last" =>						"Es wurde zuletzt am %s gespielt",
	"added_on" =>							"Es wurde am %s zur Sammlung hinzugefügt",
	"button_infoyou" =>						"Überraschungsmodus",
	"discover_now" =>						"Vorgeschlagen auf Grund von %s",
	"config_discovembobulate" =>			"Überraschungsmodus beim Start ausführen",
	"label_spotify_mix" =>					"Spotify Wochen Mix",
	"label_spotify_dj" =>					"Spotify Swim",
	"label_spottery_lottery" =>				"Spotify Zufallsauswahl!",
	"label_dailymix" =>						"Dein täglicher Mix",
	"label_luckydip" =>						"Your Lucky Dip",
	"label_startshere" =>					"Deine Entdeckungsreise startet hier",
	"label_getspotify" =>					"Installiere Spotify, um Deine Entdeckungsreise zu beginnen",
	"because_liked" =>						"Dir gefiel %s, vielleicht gefällt Dir auch:",
	"because_listened" =>					"Ähnlich wie %s:",
	"albumart_findsmall" =>					"Finde kleine Coverbilder",
	"button_sleep" =>						"Einschlaf Timer",

	// ----------------------------------------------------
	// Missing Translations
	// ----------------------------------------------------
	//"podcast_undelete" =>					"Undelete Deleted Episodes",
	//"podcast_removedownloaded" =>			"Remove Downloaded Files",
	//"label_radio_recommend" =>			"Recommendations based on this %s",
	//"label_amendalbum" =>					"Amend Album Details",
	//"label_tuneinradio" =>				"TuneIn Radio Directory",
	//"label_generalsettings" =>			"General Settings",
	//"config_beetsserver" =>				"Location of Beets Server (ip.address:port)",
	//"config_players" =>					"Players",
	//"button_edit_players" =>				"Edit Players",
	//"label_play_all" =>					"Play All",
	//"label_last_played" =>				"Last Played:",
	//"label_station_website" =>			"Station Website",
	//"label_play_whole_album" =>			"Play Whole Album",
	//"label_from_collection" =>			"Play All Tracks From Collection",
	//"label_with_ratings" =>				"Play Only Tracks With Ratings",
	//"label_with_tags" =>					"Play Only Tracks With Tags",
	//"label_with_tagandrat" =>				"Play Only Tracks With Tags And Ratings",
	//"label_with_tagorrat" =>				"Play Only Tracks With Tags Or Ratings",
	//"config_google_credentials" =>		"Google API Credentials",
	//"config_read_the_docs" =>				"Please Read The Documentation",
	//"label_dateadded" =>					"Date Added",
	//"label_radiostation" =>				"Radio Station",
	//"label_opmlimporter" =>				"OPML Importer",
	//"config_playerintitlebar" =>			"Show Player Name in Titlebar",
	//"label_communityradio" =>				"Community Radio Browser",
	//"label_volume" =>						"Volume",
	//"button_debuginfo" =>					"Debug Information",
	//"config_podcast_defaults" =>			"Default Options For New Podcasts",
	//"config_marknewasunlistened" =>		"Mark New Episodes as Unlistened Before Refresh",
	//"config_albumartinplaylist" =>		"Show Album Art in Current Playlist",
	//"label_resume" =>						"Resume",
	//"label_sortby" =>						"Sort By",
	//"label_then" =>						"Then",
	//"label_publisher" =>					"Publisher",
	//"label_category" =>					"Category",
	//"label_new_episodes" =>				"New Episodes",
	//"label_unlistened_episodes" =>		"Unlistened Episodes",
	//"label_loading" =>					"Loading...",
	//"label_choosefile" =>					"Choose A File",
	//"label_choosefiles" =>				"Choose File(s)",
	//"label_changevery" =>					"Change Every",
	//"label_albumstolistento" =>			"Albums To Listen To",
	//"no_albumtolistento" =>				"You can add any Spotify album to this list from the Info Panel, you can then come back and check them out at your leisure.",
	//"label_addedtolistenlater" =>			"Added To Albums To Listen To",
	//"label_all_time" =>					"Entire Collection",
	//"label_today" =>						"Added Today",
	//"label_thisweek" =>					"Added This Week",
	//"label_thismonth" =>					"Added This Month",
	//"label_thisyear" =>					"Added This Year",
	//"label_searchtrack" =>				"Search For This Track",
	//"label_removefromwl" =>				"Remove Track From Wishlist",
	//"label_gethelp" =>					"Click For Help",
	//"label_podcastcontrols" =>			"Podcast Search and Sort Controls",
	//"label_closepanel" =>					"Close this Panel",
	//"label_hidepanel" =>					"Hide This Panel",
	//"label_removefromplaylist" =>			"Remove From Playlist",
	//"label_addtolistenlater" =>			"Add To Albums To Listen To",
	//"label_removefromlistenlater" =>		"Remove From Albums To Listen To",
	//"label_addtocollection" =>			"Add Album To Music Collection",
	//"label_addtoradio" =>					"Add To Your Radio Stations",
	//"button_logout" =>					"Logout",
	//"label_transferplaylist" =>			"Transfer Play Queue To New Player?",
	//"podcast_refresh_all" =>				"Refresh All Podcasts",
	//"label_global_controls" =>			"Global Controls",
	//"label_topleft" =>					"Top Left",
	//"label_topright" =>					"Top Right",
	//"label_bottomleft" =>					"Bottom Left",
	//"label_bottomright" =>				"Bottom Right",
	//"label_centre" =>						"Centered",
	//"config_preferlocal" =>				"Prefer Local Music to Internet Sources",
	//"config_lastfm_playcounts" =>			"Use Last.FM Playcounts",
	//"config_sync_lastfm_playcounts" =>		"Synchronise Last.FM Playcounts At Start",
	//"label_lfm_playcountimporter" =>		"Last.FM Playcount Importer",
	//"label_mustlogintolfm" =>				"You must be logged in to Last.FM to use this feature",
	//"label_lfm_syncing" =>				"Syncing Last.FM Playcounts",
	//"label_lfm_nonew" =>					"No new tracks have been added to the Music Collection since the last import on %s",
	//"config_smart_chunksize" =>			"Number of upcoming tracks to display",
	//"warning_smart_debug" =>				"WARNING! Running Personal Radio with debugging enabled may crash your browser!",
	//"label_unplayabletracks" =>			"Unplayable Tracks",
	//"label_no_unplayable" =>				"There are no unplayable tracks in your Collection",
	//"label_removefromcol" =>				"Remove From Collection",
	//"label_audiobooks" =>					"Spoken Word",
	//"config_hideaudiobooks" =>			"Hide Spoken Word",
	//"config_audiobook_directory" =>		"Directory Containing Spoken Word Files",
	//"error_imageupload" =>				"Failed To Upload Image",
	//"error_toomanyimages" =>				"Too many images, or image file too big",
	//"error_sendingcommands" =>			"Failed Sending Commands To %s",
	//"error_cantdeleteplayer" =>			"You cannot delete the player you're currently using",
	//"error_duplicateplayer" =>			"You cannot have two players with the same name",
	//"error_backupfail" =>					"Failed to %s backup",
	//"error_nogenres" =>					"Please choose some Genres",
	//"error_collectionupdate" =>			"Music Collection Update Failed",
	//"error_nocol" =>						"Already Updating Collection!",
	//"error_dupkey" =>						"Key '%s' is already used by '%s'",
	//"error_dlpfail" =>					"Something went wrong checking the download progress!",
	//"error_refreshfail" =>				"Podcast Refresh Failed",
	//"error_trfailed" =>					"Failed to Transfer Playlist",
	//"error_trackexists" =>				"That track is already in the collection",
	//"error_nosearchnow" =>				"Cannot Search while updating collection",
	//"label_backupcreated" =>				"Backup Created",
	//"label_sleepon" =>					"Sleep Timer Enabled",
	//"label_addedtocol" =>					"Added track to Collection",
	//"label_addedtosw" =>					"Added track to Spoken Word",
	//"label_addedradio" =>					"Added To Your Radio Stations",
	//"label_updatedone" =>					"Music Collection Updated",
	//"label_addingalbum" =>				"Adding Album To Collection",
	//"error_truncated" =>					"Browser history has been truncated - artist cannot be displayed",
	//"error_noplayer" =>					"Could not get a response from the player!",
	//"label_preparing" =>					"Preparing. Please Wait While RompЯ Calculates...",
	//"label_scanningf" =>					"Scanning Folder %s",
	//"label_fremaining" =>					"%s folders remaining",
	//"label_scanningp" =>					"Scanning Playlist %s",
	//"importer_status" =>					"Done %s of %s. Elapsed %s, Remaining %s",
	//"label_playcount" =>					"Playcount",
	//"label_lfm_playcount" =>				"Last.FM Playcount",
	//"label_norecdata" =>					"Once RompЯ has gathered some data, it will show recommendations here. Play some music!",
	//"label_dailymixdesc" =>				"A playlist just for you, a mix of tracks you know and new music you might love. Powered by Last.FM %s",
	//"label_luckydipdesc" =>				"A radio station just for you, playing a wider range of music by artists you know and artists you don't yet love. Powered by Last.FM %s",
	//"label_goonlogin" =>					"Log in to Last.FM and start scrobbling. RompЯ can then delight you with new music you're going to love!",
	//"label_nospotify" =>					"Use Mopidy with a Youtube Music subscription, and start scrobbbling to Last.FM so RompЯ can delight you with new music you're going to love!",
	//"label_spotimixdesc" =>				"A radio station of suggestions based on your recent listening. Powered by RompЯ and Spotify",
	//"label_spotiswimdesc" =>				"Scanning the vastness of Spotify. Powered by RompЯ and Spotify",
	//"label_opmlexp" =>					"OPML Export",
	//"button_opmlexp" =>					"Export Podcasts As OPML",
	//"button_selectall" =>					"Select All",
	//"button_selectnone" =>				"Select None",
	//"button_import" =>					"Import Selected",
	//"label_onlyspotify" =>				"This panel is only applicable if your player can play Spotify",
	//"label_daylabels" =>					array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
	//"label_alarm_play_specific" =>		"Play This Item :",
	//"label_alarm_to_play" =>				"Drop Item Here",
	//"label_every_day" =>					"Every Day",
	//"label_every_wday" =>					"Every Weekday",
	//"label_every_wend" =>					"Every Weekend",
	//"label_new_alarm" =>					"Create New Alarm...",
	//"label_delete_alarm" =>				"Delete This Alarm",
	//"config_hidesearcher" =>				"Hide Search Panel",
	//"label_refreshinprogress" =>			"Podcasts are already being refreshed. Try again later",
	//"button_addtoplaylist" =>				"Add To Saved Playlist",
	//"config_snapcast" =>					"Snapcast",
	//"config_snapcast_server" =>			"Snapcast Server",
	//"config_snapcast_port" =>				"Port",
	//"snapcast_notthere" =>				"Could not contact Snapcast server",
	//"snapcast_group" =>					"Group ",
	//"snapcast_changegroup" =>				"Change Group",
	//"snapcast_latency" =>					"Latency ",
	//"snapcast_setlatency" =>				"Set Latency",
	//"snapcast_notconnected" =>			"(Not Connected)",
	//"label_lastfm_mix_7day" =>			"Last.FM Daily Mix",
	//"label_lastfm_mix_1month" =>			"Last.FM Monthly Mix",
	//"label_lastfm_mix_12month" =>			"Last.FM Yearly Mix",
	//"label_lastfm_mix_overall" =>			"Last.FM All Time Mix",
	//"label_lastfm_dip_7day" =>			"Last.FM Recommends",
	//"label_lastfm_dip_1month" =>			"Last.FM Lucky Dip",
	//"label_lastfm_dip_12month" =>			"Last.FM Review of the Year",
	//"label_lastfm_dip_overall" =>			"Last.FM Nostalgia Trip",
	//"config_alarm_stopafter" =>			"Stop After (mins)",
	//"label_move_to_audiobooks" =>			"Move To Spoken Word",
	//"label_move_to_collection" =>			"Move To Music Collection",
	//"label_removealbum" =>				"Remove Album From Collection",
	//"label_subbed_podcasts" =>			"Subscribed Podcasts",
	//"podcast_tooltip_unlistened" =>		"Mark as Unlistened",
	//"label_addtoqueue" =>					"Add to Play Queue",
	//"label_resetresume" =>				"Reset Resume Position",
	//"label_sameascollection" =>			"Same As Collection",
	//"label_duration_seconds" =>			"Duration (seconds)",
	//"label_year" =>						"Year",
	//"label_is" =>							"is",
	//"label_is_not" =>						"is not",
	//"label_contains" =>					"contains",
	//"label_does_not_contain" =>			"does not contain",
	//"label_exists" =>						"exists",
	//"label_lessthan" =>					"is less than",
	//"label_equals" =>						"is equal to",
	//"label_greaterthan" =>				"is greater than",
	//"label_any_rule" =>					"Tracks must match at least one rule",
	//"label_all_rules" =>					"Tracks must match all rules",
	//"label_choose_one" =>					"Choose One...",
	//"error_norules" =>					"You must create some rules",
	//"label_ruleoptions" =>				"Rule Options",
	//"label_genres" =>						"Genres",
	//"label_createcustom" =>				"Create Custom Radio Station",
	//"label_edit" =>						"Edit",
	//"label_dayssince" =>					"Days since Last Played",
	//"label_disc" =>						"Disc Number",
	//"label_tracktitle" =>					"Track Title",
	//"label_albumtitle" =>					"Album Title",
	//"label_tracknumber" =>				"Track Number",
	//"config_use_original_releasedate" =>		"Use Original Release Date for Album Date, if present",
	//"label_cantataimporter" =>			"Import Ratings from Cantata",
]);

?>
