<?php

language::add_translations([

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Music Collection",
	"button_file_browser" =>				"File Browser",
	"button_internet_radio" =>				"Internet Radio Stations",
	"button_albumart" =>					"Album Art Manager",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Toggle Sources Panel",
	"button_back" =>						"Back",
	"button_history" =>						"History",
	"button_forward" =>						"Forward",
	"button_toggleplaylist" =>				"Toggle Playlist",

	// Tooltips for playlist buttons
	"button_alarm" =>						"Alarm Clock",
	"button_prefs" =>						"RompЯ Preferences",
	"button_clearplaylist" =>				"Clear Playlist",
	"button_loadplaylist" =>				"Load Saved Playlist",
	"button_saveplaylist" =>				"Save Playlist",

	// Tooltips for playback controls
	"button_previous" =>					"Previous Track",
	"button_play" =>						"Play/Pause",
	"button_stop" =>						"Stop",
	"button_stopafter" =>					"Stop After Current Track",
	"button_next" =>						"Next Track",
	"button_love" =>						"Love this track",
	"button_ban" =>							"Ban this track",
	"button_volume" =>						"Volume",

	// Configuration menu entries
	"config_theme" =>						"THEME",
	"config_hidealbumlist" =>				"Hide Music Collection",
	"config_hidefileslist" =>				"Hide Files List",
	"config_hideradio" =>					"Hide Radio Stations",
	"config_hidepodcasts" =>				"Hide Podcasts",
	"config_hideplaylistslist" =>			"Hide Saved Playlists",
	"config_hidepluginplaylistslist" =>		"Hide Personalised Radio",
	"config_hidebrowser" =>					"Hide Info Panel",
	"config_lastfmlang" =>					"Language for Last.FM and Wikipedia",
	"config_lastfmdefault" =>				"Default language (English)",
	"config_lastfminterface" =>				"RompЯ's interface language",
	"config_lastfmbrowser" =>				"Browser's default language",
	"config_autoscroll" =>					"Auto-Scroll playlist to current track",
	"config_autocovers" =>					"Automatically Download Covers",
	"config_musicfolders" =>				"To use art from your music folders or get lyrics from your files, enter the path to your music in this box:",
	"config_crossfade" =>					"Crossfade Duration (seconds)",
	"config_doubleclick" =>					"Double Click to play, Single Click to select",
	"config_singleclick" =>					"Single Click to play",
	"config_sortbydate" =>					"Sort Albums By Date",
	"config_notvabydate" =>					"Don't Apply Date Sorting to 'Various Artists'",
	"config_updateonstart" =>				"Update Music Collection On Start",
	"config_updatenow" =>					"Update Music Collection Now",
	"config_rescan" =>						"Full Local Music Rescan",
	"config_editshortcuts" =>				"Edit Keyboard Shortcuts...",
	"config_audiooutputs" =>				"Audio Outputs",
	"config_lastfmusername" =>				"Last.FM Username",
	"config_loginbutton" =>					"Login",
	"config_scrobbling" =>					"Scrobble tracks to Last.FM",
	"config_scrobblepercent" =>				"Percentage of track to play before scrobbling",
	"config_autocorrect" =>					"Use Last.FM to auto-correct artist names etc",
	"config_tagloved" =>					"Tag Loved Tracks With:",
	"config_fontsize" =>					"FONT SIZE",
	"config_fontname" =>					"FONT STYLE",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Save",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Search Music",
	"label_yourradio" =>					"Your Radio Stations",
	"label_podcasts" =>						"Podcasts",
	"label_somafm" =>						"Soma FM",
	"label_emptyinfo" =>					"This is the information panel. Interesting stuff will appear here when you play some music",
	"button_playlistcontrols" =>			"Playlist Controls",
	"button_random" =>						"SHUFFLE",
	"button_crossfade" =>					"CROSSFADE",
	"button_repeat" =>						"REPEAT",
	"button_consume" =>						"CONSUME",
	"label_yes" =>							"Yes",
	"label_no" =>							"No",
	"label_updating" =>						"Updating Music Collection",
	"label_update_error" =>					"Failed to generate music collection.",
	"label_playlisterror" =>				"Something went wrong retrieving the playlist!",
	"button_OK" =>							"OK",
	"button_cancel" =>						"Cancel",
	"error_playlistname" =>					"Playlist name cannot contain slashes",
	"label_savedpl" =>						"Playlist saved as %s",

	// Search Forms
	"label_searchfor" =>					"Search",
	"label_searching" =>					"Searching...",
	"label_searchresults" =>				"Search Results",

	// General multipurpose labels
	"label_tracks" =>						"tracks",
	"label_albums" =>						"albums",
	"label_artists" =>						"artists",
	"label_track" =>						"Track",
	"label_album" =>						"Album",
	"label_artist" =>						"Artist",
	"label_anything" =>						"Anything",
	"label_genre" =>						"Genre",
	"label_composer" =>						"Composer",
	"label_performer" =>					"Performer",
	"label_rating" =>						"Rating",
	"label_tag" =>							"Tag",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"There was an error. Please refresh the page and try again",
	"label_days" =>							"days",
	"label_noalbums" =>						"No Individual Albums Returned By Search",
	"label_duration" =>						"Duration",
	"label_playererror" =>					"Player Error",
	"button_playradio" =>					"Play",

	// Playlist and Now Playing
	"label_notforradio" =>					"Not supported for radio streams",
	"label_incoming" =>						"Incoming...",
	"label_addingtracks" =>					"Queueing Tracks",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"by",
	"label_on" =>							"on",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"of",

	// Podcasts
	"podcast_entrybox" =>					"Subscribe to RSS feed:",
	// Podcast tooltips
	"podcast_delete" =>						"Delete this Podcast",
	"podcast_configure" =>					"Configure this Podcast",
	"podcast_refresh" =>					"Refresh this Podcast",
	"podcast_download_all" =>				"Download All Episodes of this Podcast",
	"podcast_mark_all" =>					"Mark All Episodes as Listened",
	"podcast_undelete" =>					"Undelete Deleted Episodes",
	"podcast_removedownloaded" =>			"Remove Downloaded Files",
	// Podcast display options
	"podcast_display" =>					"Display",
	"podcast_display_all" =>				"Everything",
	"podcast_display_onlynew" =>			"Only New",
	"podcast_display_unlistened" =>			"New and Unlistened",
	"podcast_display_downloadnew" =>		"New and Downloaded",
	"podcast_display_downloaded" =>			"Only Downloaded",
	// Podcast refresh options
	"podcast_refresh" =>					"Refresh",
	"podcast_refresh_never" =>				"Manually",
	"podcast_refresh_hourly" =>				"Hourly",
	"podcast_refresh_daily" =>				"Daily",
	"podcast_refresh_weekly" =>				"Weekly",
	"podcast_refresh_monthly" =>			"Monthly",
	// Podcast auto expire
	"podcast_expire" =>						"Keep Episodes For",
	"podcast_expire_tooltip" =>				"Any episodes older than this value will be removed from the list. Changes to this option will take effect next time you refresh the podcast",
	"podcast_expire_never" =>				"Ever",
	"podcast_expire_week" =>				"One Week",
	"podcast_expire_2week" =>				"Two Weeks",
	"podcast_expire_month" =>				"One Month",
	"podcast_expire_2month" =>				"Two Months",
	"podcast_expire_6month" =>				"Six Months",
	"podcast_expire_year" =>				"One Year",
	// Podcast number to keep
	"podcast_keep" =>						"Number To Keep",
	"podcast_keep_tooltip" =>				"The list will only ever show this many episodes. Changes to this option will take effect next time you refresh the podcast",
	"podcast_keep_0" =>						"Unlimited",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Keep all downloaded episodes",
	"podcast_kd_tooltip" =>					"Enable this option to keep all downloaded episodes. The above two options will then only apply to episodes that have not been downloaded",
	"podcast_tooltip_new" =>				"This is a new episode",
	"podcast_tooltip_notnew" =>				"This episode is not new but it has not been listened to",
	"podcast_tooltip_downloaded" =>			"This episode has been downloaded. Click to remove the downloaded file.",
	"podcast_tooltip_download" =>			"Download this episode to your computer",
	"podcast_tooltip_mark" =>				"Mark as listened",
	"podcast_tooltip_delepisode" =>			"Delete this episode",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Please consider supporting Soma.FM if you like these stations",

	// Your radio stations
	"label_radioinput" =>					"Enter a URL",

	//Album Art Manager
	"albumart_title" =>						"Album Art",
	"albumart_getmissing" =>				"Get Missing Covers",
	"albumart_showall" =>					"Show All Covers",
	"albumart_instructions" =>				"Click a cover to change it, or drag an image from your hard drive or another browser window",
	"albumart_onlyempty" =>					"Show Only Albums Without Covers",
	"albumart_allartists" =>				"All Artists",
	"albumart_googlesearch" =>				"Bing Search",
	"albumart_local" =>						"Local Images",
	"albumart_upload" =>					"File Upload",
	"albumart_uploadbutton" =>				"Upload",
	"albumart_newtab" =>					"Google Search in New Tab",
	"albumart_dragdrop" =>					"You can drag-and-drop images from your hard drive or another browser window directly onto the image (in most browsers)",
	"albumart_showmore" =>					"Show More Results",
	"albumart_googleproblem" =>				"There was a problem. Bing said",
	"albumart_getthese" =>					"Get These Covers",
	"albumart_nocovercount" =>				"albums without a cover",
	"albumart_getting" =>					"Getting",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr could not connect to an mpd or mopidy server",
	"setup_connecterror" =>					"There was an error when communicating with your mpd or mopidy server : ",
	"setup_request" =>						"You requested the setup page",
	"setup_addressnote" =>					"Note: localhost in this context means the computer running the webserver",
	"setup_port" =>							"Port",
	"setup_advanced" =>						"Advanced options",
	"setup_password" =>						"Password",
	"setup_unixsocket" =>					"UNIX-domain socket",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Log In to Last.FM",
	"lastfm_login1" =>						"Please click the button below to open the Last.FM website in a new tab. Enter your Last.FM login details if required then give RompЯ permission to access your account",
	"lastfm_login2" =>						"You can close the new tab when you have finished but do not close this dialog!",
	"lastfm_loginbutton" =>					"Click Here To Log In",
	"lastfm_login3" =>						"Once you have logged in to Last.FM, click the OK button below to complete the process",
	"lastfm_loginfailed" =>					"Failed to log in to Last.FM",
	"label_loved" =>						"Loved",
	"label_lovefailed" =>					"Failed To Make Love",
	"label_unloved" =>						"Unloved",
	"label_unlovefailed" =>					"Failed To Remove Love",
	"label_scrobblefailed" =>				"Failed to scrobble",

	// Info Panel
	"info_gettinginfo" =>					"Getting Info...",
	"info_newtab" =>						"View In New Tab",

	// File Info panel
	"button_fileinfo" =>					"Info Panel (File Information)",
	"info_file" =>							"File:",
	"info_from_beets" =>					"(from beets server)",
	"info_format" =>						"Format:",
	"info_bitrate" =>						"Bitrate:",
	"info_samplerate" =>					"Sample Rate:",
	"info_mono" =>							"Mono",
	"info_stereo" =>						"Stereo",
	"info_channels" =>						"Channels",
	"info_date" =>							"Date:",
	"info_genre" =>							"Genre:",
	"info_performers" =>					"Performers:",
	"info_composers" =>						"Composers:",
	"info_comment" =>						"Comment:",
	"info_label" =>							"Label:",
	"info_disctitle" =>						"Disc Title:",
	"info_encoder" =>						"Encoder:",
	"info_year" =>							"Year:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Info Panel (Last.FM)",
	"label_notrackinfo" =>					"Could not find information about this track",
	"label_noalbuminfo" =>					"Could not find information about this album",
	"label_noartistinfo" =>					"Could not find information about this artist",
	"lastfm_listeners" =>					"Listeners:",
	"lastfm_plays" =>						"Plays:",
	"lastfm_yourplays" =>					"Your Plays:",
	"lastfm_toptags" =>						"TOP TAGS:",
	"lastfm_addtags" =>						"ADD TAGS",
	"lastfm_addtagslabel" =>				"Add tags, comma separated",
	"button_add" =>							"ADD",
	"lastfm_yourtags" =>					"YOUR TAGS:",
	"lastfm_simar" =>						"Similar Artists",
	"lastfm_removetag" =>					"Remove Tag",
	"lastfm_releasedate" =>					"Release Date",
	"lastfm_viewtrack" =>					"View track on Last.FM",
	"lastfm_tagerror" =>					"Failed to modify tags",
	"lastfm_loved" =>						"Loved",
	"lastfm_lovethis" =>					"Love This Track",
	"lastfm_unlove" =>						"Unlove This Track",
	"lastfm_notfound" =>					"%s Not Found",

	// Lyrics info panel
	"button_lyrics" =>						"Info Panel (Lyrics)",
	"lyrics_lyrics" =>						"Lyrics",
	"lyrics_nonefound" =>					"No Lyrics were found",
	"lyrics_info" =>						"To use the lyrics viewer you need to ensure your local files are tagged with lyrics",
	"lyrics_nopath" =>						"To use the lyrics viewer you need to ensure your local files are tagged with lyrics and set the music path in the preferences",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"YEAR",
	"title_title" =>						"TITLE",
	"title_type" =>							"TYPE",
	"title_label" =>						"LABEL",
	"label_pages" =>						"PAGES",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"COMPANIES",
	"discogs_personnel" =>					"PERSONNEL",
	"discogs_videos" =>						"VIDEOS",
	"discogs_styles" =>						"STYLES",
	"discogs_genres" =>						"GENRES",
	"discogs_tracklisting" =>				"TRACK LISTING",
	"discogs_realname" =>					"REAL NAME:",
	"discogs_aliases" =>					"ALIASES:",
	"discogs_alsoknown" =>					"ALSO KNOWN AS:",
	"discogs_external" =>					"EXTERNAL LINKS",
	"discogs_bandmembers" =>				"BAND MEMBERS",
	"discogs_memberof" =>					"MEMBER OF",
	"discogs_discography" =>				"%s DISCOGRAPHY",

	// Discogs info panel
	"button_discogs" =>						"Info Panel (Discogs)",
	"discogs_error" =>						"Nothing was found by Discogs",
	"discogs_nonsense" =>					"Couldn't get a sensible response from Discogs",
	"discogs_noalbum" =>					"Couldn't find this album on Discogs",
	"discogs_notrack" =>					"Couldn't find this track on Discogs",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Info Panel (Musicbrainz)",
	"musicbrainz_error" =>					"Did not get a response from MusicBrainz",
	"musicbrainz_contacterror" =>			"There was an error contacting Musicbrainz",
	"musicbrainz_noartist" =>				"Could not find this artist on Musicbrainz",
	"musicbrainz_noalbum" =>				"Could not find this album on Musicbrainz",
	"musicbrainz_notrack" =>				"Could not find this track on Musicbrainz",
	"musicbrainz_noinfo" =>					"Could not get information from Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Present",
	"musicbrainz_origin" =>					"ORIGIN",
	"musicbrainz_active" =>					"ACTIVE",
	"musicbrainz_rating" =>					"RATING",
	"musicbrainz_notes" =>					"NOTES",
	"musicbrainz_tags" =>					"TAGS",
	"musicbrainz_externaldiscography" =>	"Discography (%s)",
	"musicbrainz_officalhomepage" =>		"Official Homepage (%s)",
	"musicbrainz_fansite" =>				"Fan Site (%s)",
	"musicbrainz_lyrics" =>					"Lyrics (%s)",
	"musicbrainz_social" =>					"Social Network (%s)",
	"musicbrainz_streaming" =>				"Free Streaming (%s)",
	"musicbrainz_microblog" =>				"Microblog",
	"musicbrainz_review" =>					"Review (%s)",
	"musicbrainz_purchase" =>				"Purchase (%s)",
	"musicbrainz_novotes" =>				"(No Votes)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 from %s votes",
	"musicbrainz_appears" =>				"THIS TRACK APPEARS ON",
	"musicbrainz_credits" =>				"CREDITS",
	"musicbrainz_status" =>					"STATUS",
	"musicbrainz_date" =>					"DATE",
	"musicbrainz_country" =>				"COUNTRY",
	"musicbrainz_disc" =>					"DISC",
	"musicbrainz_album_releases" =>			"RELEASES OF THIS ALBUM",

	// SoundCloud info panel
	"button_soundcloud" =>					"Info Panel (SoundCloud)",
	"soundcloud_trackinfo" =>				"Track Info",
	"soundcloud_plays" =>					"Plays",
	"soundcloud_downloads" =>				"Downloads",
	"soundcloud_faves" =>					"Faves",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"State",
	"soundcloud_license" =>					"License",
	"soundcloud_buy" =>						"Buy Track",
	"soundcloud_view" =>					"View on SoundCloud",
	"soundcloud_user" =>					"SoundCloud User",
	"soundcloud_fullname" =>				"Full Name",
	"soundcloud_Country" =>					"Country",
	"soundcloud_city" =>					"City",
	"soundcloud_website" =>					"Visit Website",
	"soundcloud_not" =>						"This panel will only display information about music from SoundCloud",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Info Panel (Wikipedia)",
	"wiki_nothing" =>						"Got nothing from Wikipedia",
	"wiki_fail" =>							"Wikipedia could not find anything related to '%s'",
	"wiki_suggest" =>						"Wikipedia was unable to find any pages matching '%s'",
	"wiki_suggest2" =>						"Here are some suggestions it came up with",

	// Keybindings editor
	"title_keybindings" =>					"Keyboard Shortcuts",
	"button_volup" =>						"Volume Up",
	"button_voldown" =>						"Volume Down",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"stars",
	"star" =>								"star",
	"label_tags" =>							"Tags",
	"label_wishlist" =>						"Wishlist",
	"label_viewwishlist" =>					"View Your Wishlist",
	"label_addtow" =>						"Added To Wishlist",
	"config_synctags" =>					"Keep Tags in Sync With Last.FM",
	"config_loveis" =>						"Last.FM Love Means",
	"playlist_xstar" =>						"%s or More Stars",
	"button_about" =>						"About RompЯ",
	"label_notfound" =>						"Track Not Found",
	// Eg + 3 more

	//New in 0.52
	"config_alarm_ramp" =>					"Fade In",

	// New in 0.60
	"spotify_error" =>						"No response from Spotify",
	"spotify_noinfo" =>						"Could not get information from Spotify",
	"button_infospotify" =>					"Info Panel (Spotify)",
	"config_icontheme" =>					"ICONS",
	"label_radio" =>						"Radio",
	"label_pop" =>							"Popularity",
	"label_albumsby" =>						"Albums By This Artist",
	"label_singleartistradio" =>			"Tracks By Artist",
	"label_mostplayed" =>					"Favourite Tracks",
	"label_neverplayed" =>					"Never Played Tracks",
	"label_radio_fartist" =>				"Favourite Artists",
	"label_pluginplaylists" =>				"Personalised Radio",
	"label_recentlyadded_random" =>			"Recently Added Tracks (Random)",
	"label_recentlyadded_byalbum" =>		"Recently Added Albums",
	"setup_mpd" =>							"MPD/Mopidy Settings",
	"settings_appearance" =>				"Appearance",
	"settings_panels" =>					"Panels",
	"settings_language" =>					"Language",
	"settings_interface" =>					"Interface",
	"label_charts" =>						"Top 40",
	"button_subscribe" =>					"Subscribe",
	"config_sortbycomposer" =>				"Use Composer as Sort Artist",
	"config_composergenre" =>				" .. only if Genre is:",
	"config_displaycomposer" =>				"Display Composer/Performer in Now Playing",
	"label_radio_mix" =>					"Favourite Artists and Related Artists",
	"label_gotnotracks" =>					"Didn't find any tracks",
	"config_artistfirst" =>					"Artists At Top Of Collection",
	"config_nosortprefixes" =>				"Ignore These Prefixes When Sorting Artists",
	"button_skipforward" =>					"Skip Forwards",
	"button_skipbackward" =>				"Skip Backwards",
	"config_snoozetime" =>					"Snooze Time (Mins)",
	"config_ramptime" =>					"Fade Time (Secs)",
	"button_rateone" =>						"Rate 1 Star",
	"button_ratetwo" =>						"Rate 2 Stars",
	"button_ratethree" =>					"Rate 3 Stars",
	"button_ratefour" =>					"Rate 4 Stars",
	"button_ratefive" =>					"Rate 5 Stars",
	"button_updatecollection" =>			"Update Music Collection",
	"label_favealbums" =>					"Favourite Albums",
	"button_nextsource" =>					"Info Panel - Cycle Source",
	"button_infopanel" =>					"Info Panel",
	"config_coversize" =>					"ALBUM COVER SIZE",
	"podcast_sortmode" =>					"Sort Order",
	"podcast_newestfirst" =>				"Newest First",
	"podcast_oldestfirst" =>				"Oldest First",
	"podcast_hidedescriptions" =>			"Hide Descriptions",

	// New in 0.64/0.65/0.70
	"label_metabackup" =>					"Metadata Backup",
	"button_backup" =>						"Create Backup",
	"button_restore" =>						"Restore Backup",
	"button_collectioncontrols" =>			"Music Collection Sort Controls",
	"button_createplaylist" =>				"CREATE PLAYLIST",
	"label_renameplaylist" =>				"Rename Playlist",
	"button_plugins" =>						"All Kinds of Good Stuff",
	"label_filename" =>						"Filename",
	"label_resultscollection" =>			"Collection",
	"label_resultstree" =>					"Directory Tree",
	"label_displayresultsas" =>				"Display Music Search Results As:",
	"label_files" =>						"Files",
	"label_albumartist" =>					"Album Artist",
	"config_collectionfolders" =>			"Build Collection From:",
	"button_videos" =>						"Related Videos",
	"label_allrandom" =>					"All Tracks At Random",
	"config_background" =>					"Background Image",
	"lastfm_error" =>						"Could not find information on Last.FM",
	"config_skin" =>						"SKIN",

	// New in 0.71
	"label_albumsbyartist" =>				"Albums (by Artist)",
	"config_wheelspeed" =>					"Mouse Wheel Scroll Speed",

	"label_radio_recommend" =>				"Recommendations based on this %s",
	"label_amendalbum" =>					"Amend Album Details",
	"label_radio_recommended" =>			"Recommendations For You",

	//CHANGED in 0.60
	"config_country" =>						"COUNTRY (for Spotify)",
	"setup_labeladdresses" =>				"If you are having connection issues, try using an IP address instead of 'localhost'",
	"setup_ipaddress" =>					"Mopidy or mpd server",

	"config_cdplayermode" =>				"CD Player Mode (do not queue tracks, start album from selected track)",

	"label_recentlyplayed" =>				"Recently Played Tracks",
	"label_simar_radio" =>					"Artists Similar To",

	"label_tradsearch" =>					"Advanced Search",

	"played_never" =>						"This track has never been played",
	"played_once" =>						"This track has been played once",
	"played_twice" =>						"This track has been played twice",
	"played_n" =>							"This track has been played %s times",
	"played_last" =>						"It was last played on %s",
	"added_on" =>							"It was added to the collection on %s",
	"button_infoyou" =>						"The Discoverator",
	"discover_now" =>						"Track Suggestions Based On %s",
	"config_discovembobulate" =>			"Open Discoverator On Start",
	"label_spotify_mix" =>					"Spotify Weekly Mix",
	"label_spotify_dj" =>					"Spotify Swim",
	"label_spottery_lottery" =>				"Spotify Surprise!",
	"label_dailymix" =>						"Your Daily Mix",
	"label_luckydip" =>						"Your Lucky Dip",
	"label_startshere" =>					"Your Discovery Starts Here",
	"label_getspotify" =>					"Get Spotify or Youtube Music To Start Discovering",
	"because_liked" =>						"You like %s, so you might like:",
	"because_listened" =>					"Similar to %s:",
	"albumart_findsmall" =>					"Find Small Images",
	"button_sleep" =>						"Sleep Timer",
	"label_tuneinradio" =>					"TuneIn Radio Directory",
	"label_generalsettings" =>				"General Settings",
	"config_beetsserver" =>					"Location of Beets Server (ip.address:port)",
	"config_players" =>						"Players",
	"button_edit_players" =>				"Edit Players",

	"label_play_all" =>						"Play All",
	"label_last_played" =>					"Last Played:",
	"label_station_website" =>				"Station Website",

	"label_play_whole_album" =>				"Play Whole Album",
	"label_from_collection" =>				"Play All Tracks From Collection",
	"label_with_ratings" =>					"Play Only Tracks With Ratings",
	"label_with_tags" =>					"Play Only Tracks With Tags",
	"label_with_tagandrat" =>				"Play Only Tracks With Tags And Ratings",
	"label_with_tagorrat" =>				"Play Only Tracks With Tags Or Ratings",
	"config_google_credentials" =>			"Bing API Credentials",
	"config_read_the_docs" =>				"Please Read The Documentation",
	"label_dateadded" =>					"Date Added",
	"label_radiostation" =>					"Radio Station",
	"label_opmlimporter" =>					"OPML Importer",
	"config_playerintitlebar" =>			"Show Player Name in Titlebar",
	"label_communityradio" =>				"Community Radio Browser",
	"label_volume" =>						"Volume",
	"button_debuginfo" =>					"Debug Information",
	"config_podcast_defaults" =>			"Default Options For New Podcasts",
	"config_marknewasunlistened" =>			"Mark New Episodes as Unlistened Before Refresh",
	"config_albumartinplaylist" =>			"Show Album Art in Play Queue",
	"label_resume" =>						"Resume",
	"label_sortby" =>						"Sort By",
	"label_then" =>							"Then",
	"label_publisher" =>					"Publisher",
	"label_category" =>						"Category",
	"label_new_episodes" =>					"New Episodes",
	"label_unlistened_episodes" =>			"Unlistened Episodes",
	"label_loading" =>						"Loading...",
	"label_choosefile" =>					"Choose A File",
	"label_choosefiles" =>					"Choose File(s)",
	"label_changevery" =>					"Change Every",
	"label_albumstolistento" =>				"Albums To Listen To",
	"no_albumtolistento" =>					"You can add any Spotify album to this list from the Info Panel, you can then come back and check them out at your leisure.",
	"label_addedtolistenlater" =>			"Added To Albums To Listen To",
	"label_all_time" =>						"Entire Collection",
	"label_today" =>						"Added Today",
	"label_thisweek" =>						"Added This Week",
	"label_thismonth" =>					"Added This Month",
	"label_thisyear" =>						"Added This Year",
	"label_searchtrack" =>					"Search For This Track",
	"label_removefromwl" =>					"Remove Track From Wishlist",
	"label_gethelp" =>						"Click For Help",
	"label_podcastcontrols" =>				"Podcast Search and Sort Controls",
	"label_closepanel" =>					"Close this Panel",
	"label_hidepanel" =>					"Hide This Panel",
	"label_removefromplaylist" =>			"Remove From Playlist",
	"label_addtolistenlater" =>				"Add To Albums To Listen To",
	"label_removefromlistenlater" =>		"Remove From Albums To Listen To",
	"label_addtocollection" =>				"Add Album To Music Collection",
	"label_addtoradio" =>					"Add To Your Radio Stations",
	"button_logout" =>						"Logout",
	"label_transferplaylist" =>				"Transfer Play Queue To New Player?",
	"label_yes" =>							"Yes",
	"label_no" =>							"No",
	"podcast_refresh_all" =>				"Refresh All Podcasts",
	"label_global_controls" =>				"Global Controls",
	"label_topleft" =>						"Top Left",
	"label_topright" =>						"Top Right",
	"label_bottomleft" =>					"Bottom Left",
	"label_bottomright" =>					"Bottom Right",
	"label_centre" =>						"Centered",
	"label_bottomcentre" =>					"Centered at Bottom",
	"label_topcentre" =>					"Centered at Top",
	"config_preferlocal" =>					"Prefer Local Music to Internet Sources",
	"config_lastfm_playcounts" =>			"Use Last.FM Playcounts",
	"config_sync_lastfm_playcounts" =>		"Synchronise Playcounts with last.FM",
	"label_lfm_playcountimporter" =>		"Last.FM Playcount Importer",
	"label_mustlogintolfm" =>				"You must be logged in to Last.FM to use this feature",
	"label_lfm_syncing" =>					"Syncing Last.FM Playcounts",
	"label_lfm_nonew" =>					"No new tracks have been added to the Music Collection since the last import on %s",
	"config_smart_chunksize" =>				"Number of upcoming tracks to display",
	"warning_smart_debug" =>				"WARNING! Running Personal Radio with debugging enabled may crash your browser!",
	"label_unplayabletracks" =>				"Unplayable Tracks",
	"label_no_unplayable" =>				"There are no unplayable tracks in your Collection",
	"label_removefromcol" =>				"Remove From Collection",
	"label_audiobooks" =>					"Spoken Word",
	"config_hideaudiobooks" =>				"Hide Spoken Word",
	"config_audiobook_directory" =>			"Directory Containing Spoken Word Files",
	"error_imageupload" =>					"Failed To Upload Image",
	"error_toomanyimages" =>				"Too many images, or image file too big",
	"error_sendingcommands" =>				"Failed Sending Commands To %s",
	"error_cantdeleteplayer" =>				"You cannot delete the player you're currently using",
	"error_duplicateplayer" =>				"You cannot have two players with the same name",
	"error_backupfail" =>					"Failed to %s backup",
	"error_nogenres" =>						"Please choose some Genres",
	"error_collectionupdate" =>				"Music Collection Update Failed",
	"error_nocol" =>						"Already Updating Collection!",
	"error_dupkey" =>						"Key '%s' is already used by '%s'",
	"error_dlpfail" =>						"Something went wrong checking the download progress!",
	"error_refreshfail" =>					"Podcast Refresh Failed",
	"error_trfailed" =>						"Failed to Transfer Playlist",
	"error_trackexists" =>					"That track is already in the collection",
	"error_nosearchnow" =>					"Cannot Search while updating collection",
	"label_backupcreated" =>				"Backup Created",
	"label_sleepon" =>						"Sleep Timer Enabled",
	"label_addedtocol" =>					"Added track to Collection",
	"label_addedtosw" =>					"Added track to Spoken Word",
	"label_addedradio" =>					"Added To Your Radio Stations",
	"label_updatedone" =>					"Music Collection Updated",
	"label_addingalbum" =>					"Adding Album To Collection",
	"error_truncated" =>					"Browser history has been truncated - artist cannot be displayed",
	"error_noplayer" =>						"Could not get a response from the player!",
	"label_preparing" =>					"Preparing. Please Wait While RompЯ Calculates...",
	"label_scanningf" =>					"Scanning Folder %s",
	"label_fremaining" =>					"%s folders remaining",
	"label_scanningp" =>					"Scanning Playlist %s",
	"importer_status" =>					"Done %s of %s. Elapsed %s, Remaining %s",
	"label_playcount" =>					"Playcount",
	"label_lfm_playcount" =>				"Last.FM Playcount",
	"label_norecdata" =>					"Once RompЯ has gathered some data, it will show recommendations here. Play some music!",
	"label_dailymixdesc" =>					"A playlist just for you, a mix of tracks you know and new music you might love. Powered by Last.FM %s",
	"label_luckydipdesc" =>					"A radio station just for you, playing a wider range of music by artists you know and artists you don't yet love. Powered by Last.FM %s",
	"label_goonlogin" =>					"Log in to Last.FM and start scrobbling. RompЯ can then delight you with new music you're going to love!",
	"label_nospotify" =>					"Use Mopidy with a Youtube Music subscription and start scrobbbling to Last.FM so RompЯ can delight you with new music you're going to love!",
	"label_spotimixdesc" =>					"A radio station of suggestions based on your recent listening. Powered by RompЯ and Spotify",
	"label_spotiswimdesc" =>				"Scanning the vastness of Spotify. Powered by RompЯ and Spotify",
	"label_opmlexp" =>						"OPML Export",
	"button_opmlexp" =>						"Export Podcasts As OPML",
	"button_selectall" =>					"Select All",
	"button_selectnone" =>					"Select None",
	"button_import" =>						"Import Selected",
	"label_onlyspotify" =>					"This panel is only applicable if your player can play Spotify",
	// NOTE: Sunday MUST be first
	"label_daylabels" => array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
	"label_alarm_play_specific" =>			"Play This Item :",
	"label_alarm_to_play" =>				"Drop Item Here",
	"label_alarm_to_play_click" =>			"Click To Select Item To Play",
	"label_every_day" =>					"Every Day",
	"label_every_wday" =>					"Every Weekday",
	"label_every_wend" =>					"Every Weekend",
	"label_new_alarm" =>					"Create New Alarm...",
	"label_delete_alarm" =>					"Delete This Alarm",
	"config_hidesearcher" =>				"Hide Search Panel",
	"label_refreshinprogress" =>			"Podcasts are already being refreshed. Try again later",
	"button_addtoplaylist" =>				"Add To Saved Playlist",
	"config_snapcast" =>					"Snapcast",
	"config_snapcast_server" =>				"Snapcast Server",
	"config_snapcast_port" =>				"TCP Port",
	"config_snapcast_http" =>				"HTTP Port",
	"snapcast_notthere" =>					"Could not contact Snapcast server",
	"snapcast_group" =>						"Group ",
	"snapcast_changegroup" =>				"Change Group",
	"snapcast_latency" =>					"Latency ",
	"snapcast_setlatency" =>				"Set Latency",
	"snapcast_notconnected" =>				"(Not Connected)",
	"label_lastfm_mix_7day" =>				"Last.FM Daily Mix",
	"label_lastfm_mix_1month" =>			"Last.FM Monthly Mix",
	"label_lastfm_mix_12month" =>			"Last.FM Yearly Mix",
	"label_lastfm_mix_overall" =>			"Last.FM All Time Mix",
	"label_lastfm_dip_7day" =>				"Last.FM Recommends",
	"label_lastfm_dip_1month" =>			"Last.FM Lucky Dip",
	"label_lastfm_dip_12month" =>			"Last.FM Review of the Year",
	"label_lastfm_dip_overall" =>			"Last.FM Nostalgia Trip",
	"config_alarm_stopafter" =>				"Stop After (mins)",
	"label_move_to_audiobooks" =>			"Move To Spoken Word",
	"label_move_to_collection" =>			"Move To Music Collection",
	"label_removealbum" =>					"Remove Album From Collection",
	"label_subbed_podcasts" =>				"Subscribed Podcasts",
	"podcast_tooltip_unlistened" =>			"Mark as Unlistened",
	"label_addtoqueue" =>					"Add to Play Queue",
	"label_resetresume" =>					"Reset Resume Position",
	"label_sameascollection" =>				"Same As Collection",
	"label_duration_seconds" =>				"Duration (seconds)",
	"label_year" =>							"Year",
	"label_is" =>							"is",
	"label_is_not" =>						"is not",
	"label_contains" =>						"contains",
	"label_does_not_contain" =>				"does not contain",
	"label_exists" =>						"exists",
	"label_lessthan" =>						"is less than",
	"label_equals" =>						"is equal to",
	"label_greaterthan" =>					"is greater than",
	"label_any_rule" =>						"Tracks must match at least one rule",
	"label_all_rules" =>					"Tracks must match all rules",
	"label_choose_one" =>					"Choose One...",
	"error_norules" =>						"You must create some rules",
	"label_ruleoptions" =>					"Rule Options",
	"label_genres" =>						"Genres",
	"label_createcustom" =>					"Create Custom Radio Station",
	"label_edit" =>							"Edit",
	"label_dayssince" =>					"Days since Last Played",
	"label_disc" =>							"Disc Number",
	"label_tracktitle" =>					"Track Title",
	"label_albumtitle" =>					"Album Title",
	"label_tracknumber" =>					"Track Number",
	"config_use_original_releasedate" =>	"Use Original Release Date for Album Date, if present",
	"label_cantataimporter" =>				"Import Ratings from Cantata",
	"podcast_writetags" =>					"Write ID3 Tags to Downloaded Files",
	"label_youtubedl" =>					"Download Audio",
	"label_youtubedl_all" =>				"Download All Youtube Tracks",
	"error_playergone" =>					"Player '%s' has stopped resonding!",
	"label_mopidy_http" =>					"Mopidy HTTP Interface Port",
	"info_mopidy_http" =>					"Optional, provides extra functionality with Mopidy",
	"label_collinfo" =>						"Collection Information",
	"label_incoll" =>						"This track is in the Music Collection",
	"label_notincoll" =>					"This track is not in the Music Collection. Click to add it",
	"label_image_search" =>					'You need a Bing Image Search API key to use Bing Search. Please read the documentation.',
	"config_hidemastervolume" =>			'Use Snapcast Volume as Main Volume Control',
	"setup_mopidy_scan" =>					'Allow RompR to run mopidy local scan when creating the Music Collection',
	"setup_mopidy_scan_title" =>			'Mopidy Special Options',
	"label_upnext" =>						'Up Next',
	// "config_consumeworkaround" =>			'Work Around Mopidy Consume Bug (Read the Docs First)',
	// "warn_consumearound" =>					'Please DISABLE consume before enabling this option',
	// "msg_consumearound" =>					'Read the Docs about this option. You must be running romonitor for it to work',
	"podcast_display_nud" =>				'New, Unlistened, & Downloaded',
	"label_usetrackimages" =>				'Scan each track for an image',
	"label_unusetrackimages" =>				'Do not scan each track for an image',
	"config_audiobook_tags" =>				'Set track as Spoken Word when adding tags',
	"label_random_order" => 				'Random Order',
	"label_remove_all" => 					'Remove All',
	"manage_bgs" =>							'Manage Background Images',
	"label_bg_global" =>					'Use In All Browsers',
	"label_bg_only" =>						'For This Browser Only',
	"label_playfromhere" =>					'Play From Here',
	"config_browserid" =>					'Browser ID',
	"button_clearwishlist" =>				'Clear Wishlist',
	"label_mfyc" =>							'Music From Your Collection',
	"label_mfsp" =>							'Music From Spotify',
	"label_mfe" =>							'Music From Everywhere',
	"label_playqueue" =>					'Play Queue',
	"label_numplays" =>						'%s Plays',
	"button_bookmarks" =>					'Add Bookmark',
	"label_remcur" =>						'Remove Current Image',
	"button_nextbg" => 						'Next Background Image',
	"button_delbg" => 						'Delete Current Background Image',
	"label_name" =>							'Name',
	"play_even_if_playing" =>				'Even If Already Playing',
	"setup_mpd_special"	=>					'MPD Special Options',
	"info_mpd_websocket" =>					"Optional, provides extra functionality with MPD",
	"label_mpd_websocket" =>				'Port for MPD Websocket Server',
	"label_ui_defaults" =>					'Defaults',
	"button_save_defaults" =>				'Save As Default For All Browsers',
	"label_recommenddesc" =>				'A Radio Station of recommendations based on your listening',
	"label_rmixdesc" =>						'A Radio Station of music by artists you love and artists like them',
	"config_stupid_round_corners" =>		'Padding at bottom of screen (to help on phones with round corners or controls that get in the way)'
	// ----------------------------------------------------
	// Proobaly Unused
	// ----------------------------------------------------
	//"label_smartsetup" =>					"Preparing. Please Wait A Moment....",

]);

?>
