<?php

// The first term here is the name that will appear in the drop-down list
// This has the form $langname['file_name without .php extension'] = "Display Name";
// Try to name your file as the two-letter language code so RompR can pick a suitable
// default language automatically.

$langname['fr'] = "Français";

$languages['fr'] = array (

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Musique",
	"button_file_browser" =>				"Parcourir",
	"button_internet_radio" =>				"Radios Internet",
	"button_albumart" =>					"Gestion De Pochettes",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Parcours Des Sources",
	"button_back" =>						"Retour",
	"button_history" =>						"Historique",
	"button_forward" =>						"Suivant",
	"button_toggleplaylist" =>				"Parcours Des Playlists",

	// Tooltips for playlist buttons
	"button_prefs" =>						"Préférences",
	"button_clearplaylist" =>				"Vider Playlist",
	"button_loadplaylist" =>				"Charger Playlist",
	"button_saveplaylist" =>				"Sauver Playlist",

	// Tooltips for playback controls
	"button_previous" =>					"Morceau Précédent",
	"button_play" =>						"Play/Pause",
	"button_stop" =>						"Stop",
	"button_stopafter" =>					"Stop A La Fin Du Morceau",
	"button_next" =>						"Suivant",
	"button_love" =>						"J'Aime",
	"button_volume" =>						"Régler le volume",

	// Configuration menu entries
	"settings_language" =>					"Langage",
	"config_theme" =>						"THEME",
	"config_hidealbumlist" =>				"Masquer Liste Musicale Locale",
	"config_hidefileslist" =>				"Masque Liste Fichiers",
	"config_hidelastfm" =>					"Masquer Stations Last.FM",
	"config_hideradio" =>					"Masquer Stations Radio",
	"config_lastfmlang" =>					"Langues pour Last.FM et Wikipedia",
	"config_lastfmdefault" =>				"Langue par défaut (English)",
	"config_lastfminterface" =>				"Langue de l'interface RompR",
	"config_lastfmbrowser" =>				"Langue par défaut du navigateur",
	"config_autoscroll" =>					"Auto-Scrolle la playlist jusqu'à la piste courante",
	"config_autocovers" =>					"Télécharge automatiquement les pochettes",
	"config_musicfolders" =>				"Pour utiliser les pochettes de vos dossiers musique, indiquer les chemins des dossiers ici :",
	"config_crossfade" =>					"Durée du fondu (secondes)",
	"config_doubleclick" =>					"Double-clic pour ajout, Click pour sélection",
	"config_singleclick" =>					"Click pour ajout, pas de sélection",
	"config_sortbydate" =>					"Classement Des Albums Par Date",
	"config_notvabydate" =>					"Pas De Classement Par Date Pour 'Various Artists'",
	"config_updateonstart" =>				"Mise A Jour De La Musique Locale Au Démarrage",
	"config_updatenow" =>					"Mise A Jour De La Musique Locale",
	"config_rescan" =>						"Scan Complet De La Musique Locale",
	"config_editshortcuts" =>				"Edition Des Raccourcis Clavier...",
	"config_audiooutputs" =>				"Sorties Audio",
	"config_lastfmusername" =>				"Utilisateur Last.FM",
	"config_loginbutton" =>					"Connexion",
	"config_scrobbling" =>					"Scrobbling Last.FM Activé",
	"config_scrobblepercent" =>				"Pourcentage de pistes à jouer avec de scrobbler",
	"config_autocorrect" =>					"Auto-correction Last.FM Activée",
	"config_tagloved" =>					"Tagguer Pistes Aimées Avec:",
	"config_country" =>						"PAYS (pour Spotify)",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Sauver",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Recherche De Musique",
	"button_searchfiles" =>					"Recherche De Fichier",
	"label_yourradio" =>					"Vos Stations Radio",
	"label_podcasts" =>						"Podcasts",
	"label_somafm" =>						"Soma FM",
	"label_bbcradio" =>						"Live BBC Radio",
	"label_icecast" =>						"Icecast Radio",
	"label_emptyinfo" =>					"Panneau d'information concernant la musique en cours de lecture",
	"button_playlistcontrols" =>			"Contrôle De La Playlist",
	"button_random" =>						"ALÉATOIRE",
	"button_crossfade" =>					"FONDU",
	"button_repeat" =>						"RÉPÉTITION",
	"button_consume" =>						"CONSOMMER",
	"label_yes" =>							"Oui",
	"label_no" =>							"Non",
	"label_updating" =>						"Mise A Jour Des Fichiers Locaux",
	"label_update_error" =>					"Echec de la génération de la liste de musique locale !",
	"label_playlisterror" =>				"Quelque chose s'est mal passé dans la récupération de la liste de lecture !",
	"button_OK" =>							"OK",
	"button_cancel" =>						"Annuler",
	"error_playlistname" =>					"Le nom de la liste de lecture comprend des '/'",
	"label_savedpl" =>						"Liste de lecture sauvée comme %s",

	// Search Forms
	"label_searchfor" =>					"Rechercher ...",
	"label_searching" =>					"Recherche en cours...",
	"label_searchresults" =>				"Résultats",
	"label_limitsearch" =>					"Limite Des Recherches",

	// General multipurpose labels
	"label_tracks" =>						"pistes",
	"label_albums" =>						"albums",
	"label_artists" =>						"artistes",
	"label_track" =>						"Piste",
	"label_album" =>						"Album",
	"label_artist" =>						"Artiste",
	"label_anything" =>						"Tout",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"Il y a eu une erreur. Merci de rafraîchir cette page et d'essayer à nouveau",
	"label_days" =>							"jours",
	"label_noalbums" =>						"Aucun Albums Trouvé",
	"label_duration" =>						"Durée",
	"label_playererror" =>					"Erreur Du Lecteur",
	"button_playradio" =>					"Lecture",

	// Playlist and Now Playing
	"label_notforradio" =>					"Non supporté pour les flux radio",
	"label_incoming" =>						"Entrant...",
	"label_addingtracks" =>					"Ajouter Des Pistes",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"par",
	"label_on" =>							"dans",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"de",

	// Podcasts
	"podcast_entrybox" =>					"Entrez l'URL d'un podcast flux RSS feed ici, ou déplacez son icône",
	// Podcast tooltips
	"podcast_delete" =>						"Supprimer ce Podcast",
	"podcast_configure" =>					"Configurer ce Podcast",
	"podcast_refresh" =>					"Rafraîchir ce Podcast",
	"podcast_download_all" =>				"Télécharger tous les épisodes de ce Podcast",
	"podcast_mark_all" =>					"Marquer Tous les Épisodes comme Écoutés",
	// Podcast display options
	"podcast_display" =>					"Afficher",
	"podcast_display_all" =>				"Tout",
	"podcast_display_onlynew" =>			"Nouveaux Seulement",
	"podcast_display_unlistened" =>			"Nouveaux et Non Écoutes",
	"podcast_display_downloadnew" =>		"Nouveaux et Téléchargés",
	"podcast_display_downloaded" =>			"Seulement Les Téléchargés",
	// Podcast refresh options
	"podcast_refresh" =>					"Rafraîchir",
	"podcast_refresh_never" =>				"Manuellement",
	"podcast_refresh_hourly" =>				"Toutes les Heures",
	"podcast_refresh_daily" =>				"Tous les Jours",
	"podcast_refresh_weekly" =>				"Toutes les Semaines",
	"podcast_refresh_monthly" =>			"Tous les Mois",
	// Podcast auto expire
	"podcast_expire" =>						"Conserver les Épisodes Pendant",
	"podcast_expire_tooltip" =>				"Tout épisode plus ancien que cette durée sera supprimé de la liste. Les changements de cette option prendront effet au prochain rafraîchissement du podcast",
	"podcast_expire_never" =>				"Toujours",
	"podcast_expire_week" =>				"Une Semaine",
	"podcast_expire_2week" =>				"Deux Semaines",
	"podcast_expire_month" =>				"Un Mois",
	"podcast_expire_2month" =>				"Deux Mois",
	"podcast_expire_6month" =>				"Six Mois",
	"podcast_expire_year" =>				"Uné Année",
	// Podcast number to keep
	"podcast_keep" =>						"Nombre De Podcasts A Conserver",
	"podcast_keep_tooltip" =>				"La liste ne montrera que ce nombre d'épisodes. Les changements de cette option prendront effet au prochain rafraîchissement du podcast",
	"podcast_keep_0" =>						"Pas de limitation",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Conserver tous les épisodes téléchargés",
	"podcast_kd_tooltip" =>					"Activer cette option pour conserver tous les épisodes téléchargés. Les deux options précédentes ne s'appliqueront qu'aux épisodes déjà téléchargés",
	"podcast_tooltip_new" =>				"Ceci est un nouvel épisode",
	"podcast_tooltip_notnew" =>				"Cet épisode n'est pas nouveau, mais il n'a pas été écouté",
	"podcast_tooltip_downloaded" =>			"Cet épisode a été téléchargé",
	"podcast_tooltip_download" =>			"Télécharger cet épisode sur votre ordinateur",
	"podcast_tooltip_mark" =>				"Marquer comme écouté",
	"podcast_tooltip_delepisode" =>			"Supprimer cet épisode",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Donations bienvenues, si vous aimez ces stations",

	// Your radio stations
	"label_radioinput" =>					"Entrez l'URL",

	//Album Art Manager
	"albumart_title" =>						"Pochettes de Disques",
	"albumart_getmissing" =>				"Trouver les Pochettes Manquantes",
	"albumart_showall" =>					"Montrer Toutes les Pochettes",
	"albumart_instructions" =>				"Sélectionner une pochette pour la changer, ou déplacer une image de votre disque dur ou d'une autre fenêtre du navigateur",
	"albumart_onlyempty" =>					"Montrer Uniquement Les Albums Sans Pochettes",
	"albumart_allartists" =>				"Tous Les Artistes",
	"albumart_googlesearch" =>				"Recherche Google",
	"albumart_local" =>						"Images Locales",
	"albumart_upload" =>					"Envoi De Fichier",
	"albumart_uploadbutton" =>				"Envoi",
	"albumart_newtab" =>					"Recherche Google Dans Un Nouvel Onglet",
	"albumart_dragdrop" =>					"Vous pouvez glisser-déposer des images depuis votre disque dur ou depuis une autre fenêtre du navigateur directement par dessus l'image (dans la plupart des navigateurs)",
	"albumart_showmore" =>					"Montrer Plus De Résultats",
	"albumart_googleproblem" =>				"Google dit qu'il y a eu un problème",
	"albumart_getthese" =>					"Récupérer Ces Pochettes",
	"albumart_nocovercount" =>				"albums sans pochette",
	"albumart_getting" =>					"Récupération",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr n'a pas réussi à se connecter à un serveur mpd ou mopidy",
	"setup_connecterror" =>					"Il y a eu un problème de communication avec votre serveur mpd ou mopidy : ",
	"setup_request" =>						"Vous avez demandé la page de configuration",
	"setup_labeladdresses" =>				"Veuillez entrer l'adresse IP et le port de votre serveur mpd dans ce formulaire",
	"setup_addressnote" =>					"Note: localhost dans ce contexte signifie que votre ordinateur fait tourner un serveur apache",
	"setup_ipaddress" =>					"Adresse IP ou nom d'hôte",
	"setup_port" =>							"Port",
	"setup_advanced" =>						"Options avancées",
	"setup_password" =>						"Mot de passe",
	"setup_unixsocket" =>					"socket UNIX",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Connexion à Last.FM",
	"lastfm_login1" =>						"Cliquez le bouton ci-dessous opur ouvrir le site Last.FM dans un nouvel onglet. Entrez votre identifiant Last.FM si nécessaire et donnez la permission d'accès à RompR",
	"lastfm_login2" =>						"Vous pouvez fermer le nouvel onglet une fois terminé, mais ne fermez pas cette fenêtre !",
	"lastfm_loginbutton" =>					"Cliquez Ici Pour Connecter",
	"lastfm_login3" =>						"Une fois connecté sur Last.FM, cliquer sur le bouton OK ci-dessous pour terminer le processus",
	"lastfm_loginfailed" =>					"Échec de connexion à Last.FM",
	"label_loved" =>						"J'Aime",
	"label_lovefailed" =>					"Échec De Marquage J'aime",
	"label_unloved" =>						"Je N'Aime Plus",
	"label_unlovefailed" =>					"Échec De Suppresion Du J'Aime",
	"label_scrobblefailed" =>				"Échec de scrobble",

	// Info Panel
	"info_gettinginfo" =>					"Récupération Des Infos...",
	"info_newtab" =>						"Voir Dans Un Nouvel Onglet",

	// File Info panel
	"button_fileinfo" =>					"Informations (Ficher)",
	"info_file" =>							"Fichier:",
	"info_from_beets" =>					"(des serveurs beets)",
	"info_format" =>						"Format:",
	"info_bitrate" =>						"Debit:",
	"info_samplerate" =>					"Échantillonnage:",
	"info_mono" =>							"Mono",
	"info_stereo" =>						"Stéreo",
	"info_channels" =>						"Canaux",
	"info_date" =>							"Date:",
	"info_genre" =>							"Genre:",
	"info_performers" =>					"Interprète:",
	"info_composers" =>						"Compositeurs:",
	"info_comment" =>						"Commentaire:",
	"info_label" =>							"Label:",
	"info_disctitle" =>						"Titre Du Disque:",
	"info_encoder" =>						"Encodeur:",
	"info_year" =>							"Année:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Informations (Last.FM)",
	"label_notrackinfo" =>					"Pas d'information trouvée sur cette piste",
	"label_noalbuminfo" =>					"Pas d'information trouvée sur cet album",
	"label_noartistinfo" =>					"Pas d'information trouvée sur cet artiste",
	"lastfm_listeners" =>					"Auditeurs:",
	"lastfm_plays" =>						"Lectures:",
	"lastfm_yourplays" =>					"Vos Lectures:",
	"lastfm_toptags" =>						"TOP TAGS:",
	"lastfm_addtags" =>						"AJOUT DE TAGS",
	"lastfm_addtagslabel" =>				"Ajout de tags, séparés par des virgules",
	"button_add" =>							"AJOUT",
	"lastfm_yourtags" =>					"VOS TAGS:",
	"lastfm_simar" =>						"Artistes Proches",
	"lastfm_removetag" =>					"Supprimer Le Tag",
	"lastfm_releasedate" =>					"Date De Sortie",
	"lastfm_viewtrack" =>					"Voir la pise sur Last.FM",
	"lastfm_tagerror" =>					"Echec de modification des tags",
	"lastfm_loved" =>						"Aimé",
	"lastfm_lovethis" =>					"J'Aime Cette Piste",
	"lastfm_unlove" =>						"Je N'Aime Plus Cette Piste",
	"lastfm_notfound" =>					"%s Non Trouvé",

	// Lyrics info panel
	"button_lyrics" =>						"Informations (Paroles)",
	"lyrics_lyrics" =>						"Paroles",
	"lyrics_nonefound" =>					"Pas De Paroles Trouvées",
	"lyrics_info" =>						"Pour utiliser le visualiseur de paroles, vous devez utiliser Mopidy avec un serveur Beets et vous assurer que vos fichiers sont taggués avec des paroles",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"ANNEE",
	"title_title" =>						"TITRE",
	"title_type" =>							"TYPE",
	"title_label" =>						"LABEL",
	"label_pages" =>						"PAGES",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"ENTREPRISES",
	"discogs_personnel" =>					"PERSONNEL",
	"discogs_videos" =>						"VIDEOS",
	"discogs_styles" =>						"STYLES",
	"discogs_genres" =>						"GENRES",
	"discogs_tracklisting" =>				"LISTE DES PISTES",
	"discogs_realname" =>					"NOM REEL:",
	"discogs_aliases" =>					"ALIAS:",
	"discogs_alsoknown" =>					"AUSSI CONNU COMME:",
	"discogs_external" =>					"LIES EXTERNES",
	"discogs_bandmembers" =>				"MEMBRES DU GROUPE",
	"discogs_memberof" =>					"MEMBRE DE",
	"discogs_discography" =>				"DISCOGRAPHIE DE",

	// Discogs info panel
	"button_discogs" =>						"Informations (Discogs)",
	"discogs_error" =>						"Il y a eu une erreur réseau ou Discogs a refusé de répondre",
	"discogs_nonsense" =>					"Aucune information pertinente de Discogs",
	"discogs_noalbum" =>					"Album non trouvé sur Discogs",
	"discogs_notrack" =>					"Piste non trouvée sur Discogs",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Informations (Musicbrainz)",
	"musicbrainz_error" =>					"Pas de réponse de MusicBrainz",
	"musicbrainz_contacterror" =>			"Il y a eu une erreur de communication avec Musicbrainz",
	"musicbrainz_noartist" =>				"Artiste non trouvé sur Musicbrainz",
	"musicbrainz_noalbum" =>				"Album non trouvé sur Musicbrainz",
	"musicbrainz_notrack" =>				"Piste non trouvée sur Musicbrainz",
	"musicbrainz_noinfo" =>					"Pas d'information trouvée sur Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Aujourd'hui",
	"musicbrainz_origin" =>					"ORIGINE",
	"musicbrainz_active" =>					"ACTIF",
	"musicbrainz_rating" =>					"NOTATION",
	"musicbrainz_notes" =>					"NOTES",
	"musicbrainz_tags" =>					"TAGS",
	"musicbrainz_externaldiscography" =>		"Discographie (%s)",
	"musicbrainz_officalhomepage" =>		"Page Officielle (%s)",
	"musicbrainz_fansite" =>				"Site De Fans (%s)",
	"musicbrainz_lyrics" =>					"Paroles (%s)",
	"musicbrainz_social" =>					"Réseau Social",
	"musicbrainz_microblog" =>				"Microblog",
	"musicbrainz_review" =>					"Critiques (%s)",
	"musicbrainz_novotes" =>				"(Aucun Vote)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 sur %s votes",
	"musicbrainz_appears" =>				"CETTE PISTE APPARAÎT SUR",
	"musicbrainz_credits" =>				"CREDITS",
	"musicbrainz_status" =>					"STATUS",
	"musicbrainz_date" =>					"DATE",
	"musicbrainz_country" =>				"PAYS",
	"musicbrainz_disc" =>					"DISQUE",

	// SoundCloud info panel
	"button_soundcloud" =>					"Informations (SoundCloud)",
	"soundcloud_trackinfo" =>				"Informations Sur La Piste",
	"soundcloud_plays" =>					"Lectures",
	"soundcloud_downloads" =>				"Téléchargements",
	"soundcloud_faves" =>					"Favoris",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"Etat",
	"soundcloud_license" =>					"License",
	"soundcloud_buy" =>						"Acheter La Piste",
	"soundcloud_view" =>					"Voir sur SoundCloud",
	"soundcloud_user" =>					"Utilisateur SoundCloud",
	"soundcloud_fullname" =>				"Nom Complet",
	"soundcloud_Country" =>					"Pays",
	"soundcloud_city" =>					"Ville",
	"soundcloud_website" =>					"Visiter Le Site Web",
	"soundcloud_not" =>						"Ce panneau ne montre que les informations sur la musique venant de SoundCloud",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Informations (Wikipedia)",
	"wiki_nothing" =>						"Rien n'a été trouvé sur Wikipedia",
	"wiki_fail" =>							"Wikipedia n'a rien pu trouver sur '%s'",
	"wiki_suggest" =>						"Wikipedia n'a trouvé aucune page correspondant à '%s'",
	"wiki_suggest2" =>						"Voici quelques suggestions qui ont été indiquées",

	// Keybindings editor
	"title_keybindings" =>					"Raccourcis Clavier",
	"button_volup" =>						"Monter Volume",
	"button_voldown" =>						"Baisser Volume",

	// ----------------------------------------------------
	// Missing Translations
	// ----------------------------------------------------
	//"button_alarm" =>						"Alarm Clock",
	//"config_hidepodcasts" =>				"Hide Podcasts",
	//"config_hideplaylistslist" =>			"Hide Saved Playlists",
	//"config_hidepluginplaylistslist" =>		"Hide Personalised Radio",
	//"config_hidebrowser" =>				"Hide Info Panel",
	//"config_fontsize" =>					"FONT SIZE",
	//"config_fontname" =>					"FONT STYLE",
	//"label_genre" =>						"Genre",
	//"label_composer" =>					"Composer",
	//"label_performer" =>					"Performer",
	//"label_rating" =>						"Rating",
	//"label_tag" =>						"Tag",
	//"podcast_undelete" =>					"Undelete Deleted Episodes",
	//"podcast_removedownloaded" =>			"Remove Downloaded Files",
	//"lyrics_nopath" =>					"To use the lyrics viewer you need to ensure your local files are tagged with lyrics and set the music path in the preferences",
	//"stars" =>							"stars",
	//"star" =>								"star",
	//"label_tags" =>						"Tags",
	//"label_wishlist" =>					"Wishlist",
	//"label_viewwishlist" =>				"View Your Wishlist",
	//"label_addtow" =>						"Added To Wishlist",
	//"config_synctags" =>					"Keep Tags in Sync With Last.FM",
	//"config_loveis" =>					"Last.FM Love Means",
	//"playlist_xstar" =>					"%s or More Stars",
	//"button_about" =>						"About RompЯ",
	//"label_notfound" =>					"Track Not Found",
	//"config_alarm_ramp" =>				"Fade In",
	//"spotify_error" =>					"No response from Spotify",
	//"spotify_noinfo" =>					"Could not get information from Spotify",
	//"button_infospotify" =>				"Info Panel (Spotify)",
	//"config_icontheme" =>					"ICONS",
	//"label_radio" =>						"Radio",
	//"label_pop" =>						"Popularity",
	//"label_albumsby" =>					"Albums By This Artist",
	//"label_singleartistradio" =>			"Tracks By Artist",
	//"label_mostplayed" =>					"Favourite Tracks",
	//"label_neverplayed" =>				"Never Played Tracks",
	//"label_radio_fartist" =>				"Favourite Artists",
	//"label_pluginplaylists" =>			"Personalised Radio",
	//"label_recentlyadded_random" =>		"Recently Added Tracks (Random)",
	//"label_recentlyadded_byalbum" =>		"Recently Added Albums",
	//"setup_mpd" =>						"MPD/Mopidy Settings",
	//"settings_appearance" =>				"Appearance",
	//"settings_panels" =>					"Panels",
	//"settings_interface" =>				"Interface",
	//"label_charts" =>						"Top 40",
	//"button_subscribe" =>					"Subscribe",
	//"config_sortbycomposer" =>			"Use Composer as Sort Artist",
	//"config_composergenre" =>				" .. only if Genre is:",
	//"config_displaycomposer" =>			"Display Composer/Performer in Now Playing",
	//"label_radio_mix" =>					"Favourite Artists and Related Artists",
	//"label_gotnotracks" =>				"Didn't find any tracks",
	//"config_artistfirst" =>				"Artists At Top Of Collection",
	//"config_nosortprefixes" =>			"Ignore These Prefixes When Sorting Artists",
	//"button_skipforward" =>				"Skip Forwards",
	//"button_skipbackward" =>				"Skip Backwards",
	//"config_snoozetime" =>				"Snooze Time (Mins)",
	//"config_ramptime" =>					"Fade Time (Secs)",
	//"button_rateone" =>					"Rate 1 Star",
	//"button_ratetwo" =>					"Rate 2 Stars",
	//"button_ratethree" =>					"Rate 3 Stars",
	//"button_ratefour" =>					"Rate 4 Stars",
	//"button_ratefive" =>					"Rate 5 Stars",
	//"button_updatecollection" =>			"Update Music Collection",
	//"label_favealbums" =>					"Favourite Albums",
	//"button_nextsource" =>				"Info Panel - Cycle Source",
	//"button_infopanel" =>					"Info Panel",
	//"config_coversize" =>					"ALBUM COVER SIZE",
	//"podcast_sortmode" =>					"Sort Order",
	//"podcast_newestfirst" =>				"Newest First",
	//"podcast_oldestfirst" =>				"Oldest First",
	//"podcast_hidedescriptions" =>			"Hide Descriptions",
	//"label_metabackup" =>					"Metadata Backup",
	//"button_backup" =>					"Create Backup",
	//"button_restore" =>					"Restore Backup",
	//"button_collectioncontrols" =>		"Music Collection Sort Controls",
	//"button_createplaylist" =>			"CREATE PLAYLIST",
	//"label_renameplaylist" =>				"Rename Playlist",
	//"button_plugins" =>					"All Kinds of Good Stuff",
	//"label_filename" =>					"Filename",
	//"label_resultscollection" =>			"Collection",
	//"label_resultstree" =>				"Directory Tree",
	//"label_displayresultsas" =>			"Display Results As:",
	//"label_files" =>						"Files",
	//"label_albumartist" =>				"Album Artist",
	//"config_collectionfolders" =>			"Build Collection From:",
	//"button_videos" =>					"Related Videos",
	//"label_allrandom" =>					"All Tracks At Random",
	//"config_background" =>				"BACKGROUND IMAGE",
	//"lastfm_error" =>						"Could not find information on Last.FM",
	//"config_skin" =>						"SKIN",
	//"label_albumsbyartist" =>				"Albums (by Artist)",
	//"config_wheelspeed" =>				"Mouse Wheel Scroll Speed",
	//"label_searchcollectiononly" =>		"Search Only in Music Collection",
	//"label_radio_recommend" =>			"Recommendations based on this %s",
	//"label_amendalbum" =>					"Amend Album Details",
	//"config_cdplayermode" =>				"CD Player Mode (do not queue tracks, start album from selected track)",
	//"label_recentlyplayed" =>				"Recently Played Tracks",
	//"label_simar_radio" =>				"Artists Similar To",
	//"label_tradsearch" =>					"Advanced Search",
	//"played_never" =>						"This track has never been played",
	//"played_once" =>						"This track has been played once",
	//"played_twice" =>						"This track has been played twice",
	//"played_n" =>							"This track has been played %s times",
	//"played_last" =>						"It was last played on %s",
	//"added_on" =>							"It was added to the collection on %s",
	//"button_infoyou" =>					"The Discoverator",
	//"discover_now" =>						"Track Suggestions Based On %s",
	//"config_discovembobulate" =>			"Open Discoverator On Start",
	//"label_spotify_mix" =>				"Spotify Weekly Mix",
	//"label_spotify_dj" =>					"Spotify Swim",
	//"label_spottery_lottery" =>			"Spotify Surprise!",
	//"label_dailymix" =>					"Your Daily Mix",
	//"label_luckydip" =>					"Your Lucky Dip",
	//"label_startshere" =>					"Your Discovery Starts Here",
	//"label_getspotify" =>					"Get Spotify To Start Discovering",
	//"because_liked" =>					"You like %s, so you might like:",
	//"because_listened" =>					"Similar to %s:",
	//"albumart_findsmall" =>				"Find Small Images",
	//"button_sleep" =>						"Sleep Timer",
	//"label_tuneinradio" =>				"TuneIn Radio Directory",
	//"label_generalsettings" =>			"General Settings",
	//"config_beetsserver" =>				"Location of Beets Server (ip.address:port)",
	//"config_players" =>					"Players",
	//"button_edit_players" =>				"Edit Players",
	//"label_play_all" =>					"Play All",
	//"label_last_played" =>				"Last Played:",
	//"label_station_website" =>			"Station Website",
	//"label_play_whole_album" =>			"Play Whole Album",
	//"label_from_collection" =>			"Play All Tracks From Collection",
	//"label_with_ratings" =>				"Play Only Tracks With Ratings",
	//"label_with_tags" =>					"Play Only Tracks With Tags",
	//"label_with_tagandrat" =>				"Play Only Tracks With Tags And Ratings",
	//"label_with_tagorrat" =>				"Play Only Tracks With Tags Or Ratings",
	//"config_google_credentials" =>		"Google API Credentials",
	//"config_read_the_docs" =>				"Please Read The Documentation",
	//"label_dateadded" =>					"Date Added",
	//"label_radiostation" =>				"Radio Station",
	//"label_opmlimporter" =>				"OPML Importer",
	//"config_playerintitlebar" =>			"Show Player Name in Titlebar",
	//"label_communityradio" =>				"Community Radio Browser",
	//"label_volume" =>						"Volume",
	//"config_playlistswipe" =>				"Swipe to remove tracks from Current Playlist",
	//"button_debuginfo" =>					"Debug Information",
	//"config_podcast_defaults" =>			"Default Options For New Podcasts",
	//"config_marknewasunlistened" =>		"Mark New Episodes as Unlistened Before Refresh",
	//"config_albumartinplaylist" =>		"Show Album Art in Current Playlist",
	//"label_resume" =>						"Resume",
	//"label_sortby" =>						"Sort By",
	//"label_then" =>						"Then",
	//"label_publisher" =>					"Publisher",
	//"label_category" =>					"Category",
	//"label_new_episodes" =>				"New Episodes",
	//"label_unlistened_episodes" =>		"Unlistened Episodes",
	//"label_loading" =>					"Loading...",
	//"label_choosefile" =>					"Choose A File",
	//"label_choosefiles" =>				"Choose File(s)",
	//"label_changevery" =>					"Change Every",
	//"label_albumstolistento" =>			"Albums To Listen To",
	//"no_albumtolistento" =>				"You can add any Spotify album to this list from the Info Panel, you can then come back and check them out at your leisure.",
	//"label_addedtolistenlater" =>			"Added To Albums To Listen To",
	//"label_all_time" =>					"Entire Collection",
	//"label_today" =>						"Added Today",
	//"label_thisweek" =>					"Added This Week",
	//"label_thismonth" =>					"Added This Month",
	//"label_thisyear" =>					"Added This Year",
	//"label_searchtrack" =>				"Search For This Track",
	//"label_removefromwl" =>				"Remove Track From Wishlist",
	//"label_gethelp" =>					"Click For Help",
	//"label_podcastcontrols" =>			"Podcast Search and Sort Controls",
	//"label_closepanel" =>					"Close this Panel",
	//"label_hidepanel" =>					"Hide This Panel",
	//"label_removefromplaylist" =>			"Remove From Playlist",
	//"label_addtolistenlater" =>			"Add To Albums To Listen To",
	//"label_removefromlistenlater" =>		"Remove From Albums To Listen To",
	//"label_addtocollection" =>			"Add Album To Music Collection",
	//"label_addtoradio" =>					"Add To Your Radio Stations",
	//"button_logout" =>					"Logout",
	//"label_transferplaylist" =>			"Transfer Play Queue To New Player?",
	//"podcast_refresh_all" =>				"Refresh All Podcasts",
	//"label_global_controls" =>			"Global Controls",
	//"label_topleft" =>					"Top Left",
	//"label_topright" =>					"Top Right",
	//"label_bottomleft" =>					"Bottom Left",
	//"label_bottomright" =>				"Bottom Right",
	//"label_centre" =>						"Centered",
	//"config_preferlocal" =>				"Prefer Local Music to Internet Sources",
	//"config_lastfm_playcounts" =>			"Use Last.FM Playcounts",
	//"config_sync_lastfm_playcounts" =>		"Synchronise Last.FM Playcounts At Start",
	//"label_lfm_playcountimporter" =>		"Last.FM Playcount Importer",
	//"label_mustlogintolfm" =>				"You must be logged in to Last.FM to use this feature",
	//"label_lfm_syncing" =>				"Syncing Last.FM Playcounts",
	//"label_lfm_nonew" =>					"No new tracks have been added to the Music Collection since the last import on %s",
	//"config_smart_chunksize" =>			"Number of upcoming tracks to display",
	//"warning_smart_debug" =>				"WARNING! Running Personal Radio with debugging enabled may crash your browser!",
	//"label_unplayabletracks" =>			"Unplayable Tracks",
	//"label_no_unplayable" =>				"There are no unplayable tracks in your Collection",
	//"label_removefromcol" =>				"Remove From Collection",
	//"label_audiobooks" =>					"Spoken Word",
	//"config_hideaudiobooks" =>			"Hide Spoken Word",
	//"config_audiobook_directory" =>		"Directory Containing Spoken Word Files",
	//"error_imageupload" =>				"Failed To Upload Image",
	//"error_toomanyimages" =>				"Too many images, or image file too big",
	//"error_sendingcommands" =>			"Failed Sending Commands To %s",
	//"error_cantdeleteplayer" =>			"You cannot delete the player you're currently using",
	//"error_duplicateplayer" =>			"You cannot have two players with the same name",
	//"error_backupfail" =>					"Failed to %s backup",
	//"error_nogenres" =>					"Please choose some Genres",
	//"error_collectionupdate" =>			"Music Collection Update Failed",
	//"error_nocol" =>						"Already Updating Collection!",
	//"error_dupkey" =>						"Key '%s' is already used by '%s'",
	//"error_dlpfail" =>					"Something went wrong checking the download progress!",
	//"error_refreshfail" =>				"Podcast Refresh Failed",
	//"error_trfailed" =>					"Failed to Transfer Playlist",
	//"error_trackexists" =>				"That track is already in the collection",
	//"error_nosearchnow" =>				"Cannot Search while updating collection",
	//"label_backupcreated" =>				"Backup Created",
	//"label_sleepon" =>					"Sleep Timer Enabled",
	//"label_addedtocol" =>					"Added track to Collection",
	//"label_addedtosw" =>					"Added track to Spoken Word",
	//"label_addedradio" =>					"Added To Your Radio Stations",
	//"label_updatedone" =>					"Music Collection Updated",
	//"label_addingalbum" =>				"Adding Album To Collection",
	//"error_truncated" =>					"Browser history has been truncated - artist cannot be displayed",
	//"error_noplayer" =>					"Could not get a response from the player!",
	//"label_preparing" =>					"Preparing. Please Wait While RompЯ Calculates...",
	//"label_scanningf" =>					"Scanning Folder %s",
	//"label_fremaining" =>					"%s folders remaining",
	//"label_scanningp" =>					"Scanning Playlist %s",
	//"importer_status" =>					"Done %s of %s. Elapsed %s, Remaining %s",
	//"label_playcount" =>					"Playcount",
	//"label_lfm_playcount" =>				"Last.FM Playcount",
	//"label_norecdata" =>					"Once RompЯ has gathered some data, it will show recommendations here. Play some music!",
	//"label_dailymixdesc" =>				"A playlist just for you, a mix of tracks you know and new music you might love. Powered by Last.FM %s",
	//"label_luckydipdesc" =>				"A radio station just for you, playing a wider range of music by artists you know and artists you don't yet love. Powered by Last.FM %s",
	//"label_goonlogin" =>					"Log in to Last.FM and start scrobbling. RompЯ can then delight you with new music you're going to love!",
	//"label_nospotify" =>					"Use Mopidy with a Spotify Premium subscription or a Google Play Music subscription, and start scrobbbling to Last.FM so RompЯ can delight you with new music you're going to love!",
	//"label_spotimixdesc" =>				"A radio station of suggestions based on your recent listening. Powered by RompЯ and Spotify",
	//"label_spotiswimdesc" =>				"Scanning the vastness of Spotify. Powered by RompЯ and Spotify",
	//"label_opmlexp" =>					"OPML Export",
	//"button_opmlexp" =>					"Export Podcasts As OPML",
	//"button_selectall" =>					"Select All",
	//"button_selectnone" =>				"Select None",
	//"button_import" =>					"Import Selected",
	//"label_onlyspotify" =>				"This panel is only applicable if your player can play Spotify",
	//"label_daylabels" =>					array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
	//"label_alarm_play_specific" =>		"Play This Item :",
	//"label_alarm_to_play" =>				"Drop Item Here",
	//"label_every_day" =>					"Every Day",
	//"label_every_wday" =>					"Every Weekday",
	//"label_every_wend" =>					"Every Weekend",
	//"label_new_alarm" =>					"Create New Alarm...",
	//"label_delete_alarm" =>				"Delete This Alarm",
	//"config_hidesearcher" =>				"Hide Search Panel",
	//"label_refreshinprogress" =>			"Podcasts are already being refreshed. Try again later",
	//"button_addtoplaylist" =>				"Add To Saved Playlist",
	//"config_snapcast" =>					"Snapcast",
	//"config_snapcast_server" =>			"Snapcast Server",
	//"config_snapcast_port" =>				"Port",
	//"snapcast_notthere" =>				"Could not contact Snapcast server",
	//"snapcast_group" =>					"Group ",
	//"snapcast_changegroup" =>				"Change Group",
	//"snapcast_latency" =>					"Latency ",
	//"snapcast_setlatency" =>				"Set Latency",
	//"snapcast_notconnected" =>			"(Not Connected)",
	//"label_lastfm_mix_7day" =>			"Last.FM Daily Mix",
	//"label_lastfm_mix_1month" =>			"Last.FM Monthly Mix",
	//"label_lastfm_mix_12month" =>			"Last.FM Yearly Mix",
	//"label_lastfm_mix_overall" =>			"Last.FM All Time Mix",
	//"label_lastfm_dip_7day" =>			"Last.FM Recommends",
	//"label_lastfm_dip_1month" =>			"Last.FM Lucky Dip",
	//"label_lastfm_dip_12month" =>			"Last.FM Review of the Year",
	//"label_lastfm_dip_overall" =>			"Last.FM Nostalgia Trip",
	//"config_alarm_stopafter" =>			"Stop After (mins)",
	//"label_move_to_audiobooks" =>			"Move To Spoken Word",
	//"label_move_to_collection" =>			"Move To Music Collection",
	//"label_removealbum" =>				"Remove Album From Collection",
	//"label_subbed_podcasts" =>			"Subscribed Podcasts",
	//"podcast_tooltip_unlistened" =>		"Mark as Unlistened",
	//"label_addtoqueue" =>					"Add to Play Queue",
	//"label_resetresume" =>				"Reset Resume Position",
	//"label_sameascollection" =>			"Same As Collection",
	//"label_duration_seconds" =>			"Duration (seconds)",
	//"label_year" =>						"Year",
	//"label_is" =>							"is",
	//"label_is_not" =>						"is not",
	//"label_contains" =>					"contains",
	//"label_does_not_contain" =>			"does not contain",
	//"label_exists" =>						"exists",
	//"label_lessthan" =>					"is less than",
	//"label_equals" =>						"is equal to",
	//"label_greaterthan" =>				"is greater than",
	//"label_any_rule" =>					"Tracks must match at least one rule",
	//"label_all_rules" =>					"Tracks must match all rules",
	//"label_choose_one" =>					"Choose One...",
	//"error_norules" =>					"You must create some rules",
	//"label_ruleoptions" =>				"Rule Options",
	//"label_genres" =>						"Genres",
	//"label_createcustom" =>				"Create Custom Radio Station",
	//"label_edit" =>						"Edit",
	//"label_dayssince" =>					"Days since Last Played",
	//"label_disc" =>						"Disc Number",
	//"label_tracktitle" =>					"Track Title",
	//"label_albumtitle" =>					"Album Title",
	//"label_tracknumber" =>				"Track Number",
	//"config_use_original_releasedate" =>		"Use Original Release Date for Album Date, if present",
	//"label_cantataimporter" =>			"Import Ratings from Cantata",
);

?>
