<?php

// The first term here is the name that will appear in the drop-down list
// This has the form $langname['file_name without .php extension'] = "Display Name";
// Try to name your file as the two-letter language code so RompR can pick a suitable
// default language automatically.

$langname['it'] = "Italiano";

$languages['it'] = array (

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Collezione Musicale",
	"button_file_browser" =>				"Esplora File",
	"button_internet_radio" =>				"Internet Radio",
	"button_albumart" =>					"Gestione Copertine Album",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Mostra/Nascondi Pannello Sorgenti",
	"button_back" =>						"Indietro",
	"button_history" =>						"Cronologia",
	"button_forward" =>						"Avanti",
	"button_toggleplaylist" =>				"Mostra/Nascondi Playlist",

	// Tooltips for playlist buttons
	"button_alarm" =>						"Sveglia",
	"button_prefs" =>						"Preferenze di RompR",
	"button_clearplaylist" =>				"Cancella Playlist",
	"button_loadplaylist" =>				"Carica Playlist Salvata",
	"button_saveplaylist" =>				"Salva Playlist",

	// Tooltips for playback controls
	"button_previous" =>					"Brano Precedente",
	"button_play" =>						"Play/Pausa",
	"button_stop" =>						"Stop",
	"button_stopafter" =>					"Stop Dopo il Brano Corrente",
	"button_next" =>						"Brano Successivo",
	"button_love" =>						"Aggiungi ai Brani Preferiti",
	"button_volume" =>						"Trascina per regolare il volume",

	// Configuration menu entries
	"config_theme" =>						"TEMA",
	"config_hidealbumlist" =>				"Nascondi Collezione Musicale",
	"config_hidefileslist" =>				"Nascondi Elenco File",
	"config_hidelastfm" =>					"Nascondi le Stazioni Last.FM",
	"config_hideradio" =>					"Nascondi le Stazioni Radio",
	"config_hidebrowser" =>					"Nascondi Pannello Informazioni",
	"config_lastfmlang" =>					"Lingua per Last.FM e Wikipedia",
	"config_lastfmdefault" =>				"Lingua predefinita (inglese)",
	"config_lastfminterface" =>				"Lingua dell'interfaccia di RompR",
	"config_lastfmbrowser" =>				"Lingua predefinita del Browser",
	"config_autoscroll" =>					"Scorri automaticamente la playlist al brano corrente",
	"config_autocovers" =>					"Scarica automaticamente le copertine",
	"config_musicfolders" =>				"Per utilizzare le immagini dalla tua cartella musica o per recuperare i testi dai tuoi file, inserisci qui il percorso alla tua musica:",
	"config_crossfade" =>					"Durata dissolvenza incrociata (secondi)",
	"config_doubleclick" =>					"Doppio-clic per aggiungere, clic per selezionare",
	"config_singleclick" =>					"Clic per aggiungere, nessuna selezione",
	"config_sortbydate" =>					"Ordina Album per Data",
	"config_notvabydate" =>					"Non applicare l'ordinamento per data a 'Artisti Vari'",
	"config_updateonstart" =>				"Aggiorna Collezione Musicale all'Avvio",
	"config_updatenow" =>					"Aggiorna Collezione Musicale Adesso",
	"config_rescan" =>						"Ricerca nuovamente tutta la Musica in locale",
	"config_editshortcuts" =>				"Modifica le Scorciatoie da Tastiera...",
	"config_audiooutputs" =>				"Uscite Audio",
	"config_lastfmusername" =>				"Nome utente Last.FM",
	"config_loginbutton" =>					"Accedi",
	"config_scrobbling" =>					"Abilita lo Scrobbling di Last.FM",
	"config_scrobblepercent" =>				"Percentuale di brano riprodotto prima di effettuare lo scrobbling",
	"config_autocorrect" =>					"Abilita autocorrezione di Last.FM",
	"config_tagloved" =>					"Tagga il Brano come Preferito con:",
	"config_fontsize" =>					"DIMENSIONE CARATTERI",
	"config_fontname" =>					"STILE CARATTERI",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Salva",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Cerca Musica",
	"button_searchfiles" =>					"Cerca File",
	"label_yourradio" =>					"Le Tue Stazioni Radio",
	"label_podcasts" =>						"Podcast",
	"label_somafm" =>						"Soma FM",
	"label_bbcradio" =>						"Radio BBC Live",
	"label_icecast" =>						"Radio Icecast",
	"label_emptyinfo" =>					"Questo è il pannello informazioni. Diverse cose interessanti appariranno qui quando riprodurrai della musica.",
	"button_playlistcontrols" =>			"Controlli Playlist",
	"button_random" =>						"CASUALE",
	"button_crossfade" =>					"DISSOLVENZA INCROCIATA",
	"button_repeat" =>						"RIPETI",
	"button_consume" =>						"CONSUMA",
	"label_yes" =>							"Sì",
	"label_no" =>							"No",
	"label_updating" =>						"Aggiornamento Collezione Musicale",
	"label_update_error" =>					"Creazione della Collezione Musicale fallita!",
	"label_playlisterror" =>				"Qualcosa è andato storto recuperando la playlist!",
	"button_OK" =>							"OK",
	"button_cancel" =>						"Annulla",
	"error_playlistname" =>					"Il nome della Playlist non può contenere 'barre'",
	"label_savedpl" =>						"Playlist salvata come %s",

	// Search Forms
	"label_searchfor" =>					"Cerca Per",
	"label_searching" =>					"Sto Cercando...",
	"label_searchresults" =>				"Risultati della Ricerca",
	"label_limitsearch" =>					"Cerca in un Backend Specifico",

	// General multipurpose labels
	"label_tracks" =>						"brani",
	"label_albums" =>						"album",
	"label_artists" =>						"artisti",
	"label_track" =>						"Brano",
	"label_album" =>						"Album",
	"label_artist" =>						"Artista",
	"label_anything" =>						"Qualsiasi",
	"label_genre" =>						"Genere",
	"label_composer" =>						"Compositore",
	"label_performer" =>					"Esecutore",
	"label_rating" =>						"Valutazione",
	"label_tag" =>							"Tag",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"C'è stato un errore. Ricarica la pagina e riprova.",
	"label_days" =>							"giorni",
	"label_noalbums" =>						"La ricerca non ha trovato l'album specificato",
	"label_duration" =>						"Durata",
	"label_playererror" =>					"Errore del riproduttore",
	"button_playradio" =>					"Play",

	// Playlist and Now Playing
	"label_notforradio" =>					"Non supportato per gli stream radio",
	"label_incoming" =>						"In arrivo...",
	"label_addingtracks" =>					"Aggiungo Brani",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"di",
	"label_on" =>							"da",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"di",

	// Podcasts
	"podcast_entrybox" =>					"Inserisci l'URL al feed RSS del podcast, o trascina la sua icona qui",
	// Podcast tooltips
	"podcast_delete" =>						"Elimina questo Podcast",
	"podcast_configure" =>					"Configura questo Podcast",
	"podcast_refresh" =>					"Aggiorna questo Podcast",
	"podcast_download_all" =>				"Scarica Tutti gli Episodi di questo Podcast",
	"podcast_mark_all" =>					"Segna Tutti gli Episodi come Ascoltati",
	// Podcast display options
	"podcast_display" =>					"Mostra",
	"podcast_display_all" =>				"Qualsiasi",
	"podcast_display_onlynew" =>			"Solo Nuovi",
	"podcast_display_unlistened" =>			"Nuovi e non Ascoltati",
	"podcast_display_downloadnew" =>		"Nuovi e Scaricati",
	"podcast_display_downloaded" =>			"Solo Scaricati",
	// Podcast refresh options
	"podcast_refresh" =>					"Aggiorna",
	"podcast_refresh_never" =>				"Manualmente",
	"podcast_refresh_hourly" =>				"Ogni Ora",
	"podcast_refresh_daily" =>				"Ogni Giorno",
	"podcast_refresh_weekly" =>				"Ogni Settimana",
	"podcast_refresh_monthly" =>			"Ogni Mese",
	// Podcast auto expire
	"podcast_expire" =>						"Conserva Episodi Per",
	"podcast_expire_tooltip" =>				"Qualsiasi episodio più vecchio di questo valore sarà rimosso dall'elenco. Le modifiche avranno effetto al prossimo aggiornamento del podcast",
	"podcast_expire_never" =>				"Sempre",
	"podcast_expire_week" =>				"Una Settimana",
	"podcast_expire_2week" =>				"Due Settimane",
	"podcast_expire_month" =>				"Un Mese",
	"podcast_expire_2month" =>				"Due Mesi",
	"podcast_expire_6month" =>				"Sei Mesi",
	"podcast_expire_year" =>				"Un Anno",
	// Podcast number to keep
	"podcast_keep" =>						"Numero di Episodi da Conservare",
	"podcast_keep_tooltip" =>				"Questo elenco mostrerà sempre questo numero di episodi. Le modifiche avranno effetto al prossimo aggiornamento del podcast",
	"podcast_keep_0" =>						"Illimitato",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Conserva tutti gli episodi scaricati",
	"podcast_kd_tooltip" =>					"Abilita questa opzione per conservare tutti gli episodi scaricati. Le due opzioni precedenti si applicheranno solo agli episodi che non sono stati scaricati",
	"podcast_tooltip_new" =>				"Questo è un nuovo episodio",
	"podcast_tooltip_notnew" =>				"Questo episodio non è nuovo, ma non è stato ascoltato",
	"podcast_tooltip_downloaded" =>			"Questo episodio è stato scaricato",
	"podcast_tooltip_download" =>			"Scarica questo episodio sul tuo computer",
	"podcast_tooltip_mark" =>				"Segna come ascoltato",
	"podcast_tooltip_delepisode" =>			"Elimina questo episodio",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Se ti piacciono queste stazioni, prendi in considerazione di supportare economicamente Soma.FM",

	// Your radio stations
	"label_radioinput" =>					"Inserisci un URL",

	//Album Art Manager
	"albumart_title" =>						"Copertine Album",
	"albumart_getmissing" =>				"Recupera Copertine Mancanti",
	"albumart_showall" =>					"Mostra tutte le copertine",
	"albumart_instructions" =>				"Fai clic su una copertina per cambiarla, o trascina un'immagine dal tuo hard disk o da un'altra finestra del browser",
	"albumart_onlyempty" =>					"Mostra solo gli album senza copertine",
	"albumart_allartists" =>				"Tutti gli Artisti",
	"albumart_googlesearch" =>				"Cerca su Google",
	"albumart_local" =>						"Immagini in Locale",
	"albumart_upload" =>					"Carica File",
	"albumart_uploadbutton" =>				"Carica",
	"albumart_newtab" =>					"Ricerca Google in una nuova scheda",
	"albumart_dragdrop" =>					"Puoi trascinare le immagini dal tuo hard disk o direttamente da un'altra finestra del browser (nella maggior parte dei browser)",
	"albumart_showmore" =>					"Mostra più risultati",
	"albumart_googleproblem" =>				"Si è verificato un problema. Lo ha detto Google",
	"albumart_getthese" =>					"Recupera queste copertine",
	"albumart_nocovercount" =>				"album senza copertina",
	"albumart_getting" =>					"Sto recuperando",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr non riesce a connettersi ad un server mpd o mopidy",
	"setup_connecterror" =>					"Si è verificato un errore nella comunicazione con il tuo server mpd o mopidy : ",
	"setup_request" =>						"Hai richiesto la pagina di configurazione",
	"setup_addressnote" =>					"Nota: localhost in questo contesto indica il computer dove è in esecuzione il server Apache",
	"setup_port" =>							"Porta",
	"setup_advanced" =>						"Opzioni avanzate",
	"setup_password" =>						"Password",
	"setup_unixsocket" =>					"Socket dominio UNIX",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Accedi a Last.FM",
	"lastfm_login1" =>						"Fai clic sul bottone in basso per aprire il sito di Last.FM in una nuova scheda. Inserisci le tue credenziali Last.FM se richieste quindi concedi a RompR il permesso di accedere al tuo account",
	"lastfm_login2" =>						"Puoi chiudere la nuova scheda quando hai finito ma non chiudere questa finestra di dialogo!",
	"lastfm_loginbutton" =>					"Fai clic qui per accedere",
	"lastfm_login3" =>						"Una volta effettuato l'accesso a Last.FM, fai clic sul bottone OK qui sotto per completare la procedura",
	"lastfm_loginfailed" =>					"Accesso a Last.FM fallito",
	"label_loved" =>						"Preferiti",
	"label_lovefailed" =>					"Aggiunta ai preferiti fallita",
	"label_unloved" =>						"Rimosso da preferiti",
	"label_unlovefailed" =>					"Rimozione dai preferiti fallita",
	"label_scrobblefailed" =>				"Scrobble fallito",

	// Info Panel
	"info_gettinginfo" =>					"Recupero informazioni...",
	"info_newtab" =>						"Visualizza in una nuova scheda",

	// File Info panel
	"button_fileinfo" =>					"Pannello Informazioni (Informazioni File)",
	"info_file" =>							"File:",
	"info_from_beets" =>					"(dal server beets)",
	"info_format" =>						"Formato:",
	"info_bitrate" =>						"Bitrate:",
	"info_samplerate" =>					"Campionamento:",
	"info_mono" =>							"Mono",
	"info_stereo" =>						"Stereo",
	"info_channels" =>						"Canali",
	"info_date" =>							"Data:",
	"info_genre" =>							"Genere:",
	"info_performers" =>					"Esecutori:",
	"info_composers" =>						"Compositori:",
	"info_comment" =>						"Commenti:",
	"info_label" =>							"Etichetta:",
	"info_disctitle" =>						"Titolo Disco:",
	"info_encoder" =>						"Encoder:",
	"info_year" =>							"Anno:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Pannello Informazioni (Last.FM)",
	"label_notrackinfo" =>					"Impossibile trovare informazioni su questo brano",
	"label_noalbuminfo" =>					"Impossibile trovare informazioni su questo album",
	"label_noartistinfo" =>					"Impossibile trovare informazioni su questo artista",
	"lastfm_listeners" =>					"Ascoltatori:",
	"lastfm_plays" =>						"Riproduzioni:",
	"lastfm_yourplays" =>					"Tue riproduzioni:",
	"lastfm_toptags" =>						"TOP TAG:",
	"lastfm_addtags" =>						"AGGIUNGI TAG",
	"lastfm_addtagslabel" =>				"Aggiungi tag separati da virgola",
	"button_add" =>							"AGGIUNGI",
	"lastfm_yourtags" =>					"TUOI TAG:",
	"lastfm_simar" =>						"Artisiti simili",
	"lastfm_removetag" =>					"Rimuovi Tag",
	"lastfm_releasedate" =>					"Data di rilascio",
	"lastfm_viewtrack" =>					"Visualizza il brano su Last.FM",
	"lastfm_tagerror" =>					"Modifica dei tag fallita",
	"lastfm_loved" =>						"Aggiunto ai preferiti",
	"lastfm_lovethis" =>					"Aggiungi brano ai preferiti",
	"lastfm_unlove" =>						"Rimuovi brano dai preferiti",
	"lastfm_notfound" =>					"%s non trovato",

	// Lyrics info panel
	"button_lyrics" =>						"Pannello Informazioni (Testi)",
	"lyrics_lyrics" =>						"Testi",
	"lyrics_nonefound" =>					"Nessun testo trovato",
	"lyrics_info" =>						"Per visualizzare i testi delle canzoni devi assicurarti che i tuoi file locali siano correttamente etichettati con i testi",
	"lyrics_nopath" =>						"Per visualizzare i testi delle canzoni devi assicurarti che i tuoi file locali siano correttamente etichettati con i testi e impostare il percorso della musica nelle preferenze",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"ANNO",
	"title_title" =>						"TITOLO",
	"title_artist" =>						"ARTISTA",
	"title_type" =>							"TIPO",
	"title_label" =>						"ETICHETTA",
	"label_pages" =>						"PAGINE",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"COMPAGNIE",
	"discogs_personnel" =>					"PERSONALE",
	"discogs_videos" =>						"VIDEO",
	"discogs_styles" =>						"STILI",
	"discogs_genres" =>						"GENERI",
	"discogs_tracklisting" =>				"ELENCO BRANI",
	"discogs_realname" =>					"VERO NOME:",
	"discogs_aliases" =>					"ALIAS:",
	"discogs_alsoknown" =>					"CONOSCIUTO ANCHE COME:",
	"discogs_external" =>					"COLLEGAMENTI ESTERNI",
	"discogs_bandmembers" =>				"MEMBRI DELLA BAND",
	"discogs_memberof" =>					"MEMBRO DI",
	"discogs_discography" =>				"DISCOGRAFIA %s",

	// Discogs info panel
	"button_discogs" =>						"Pannello Informazioni (Discogs)",
	"discogs_error" =>						"Si è verificato un errore di rete o Discogs non ha risposto",
	"discogs_nonsense" =>					"Impossibile ottenere una risposta sensata da Discogs",
	"discogs_noalbum" =>					"Impossibile trovare questo album su Discogs",
	"discogs_notrack" =>					"Impossibile trovare questo brano su Discogs",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Pannello Informazioni (Musicbrainz)",
	"musicbrainz_error" =>					"Nessuna risposta da from MusicBrainz",
	"musicbrainz_contacterror" =>			"Si è verificato un errore connettendosi a Musicbrainz",
	"musicbrainz_noartist" =>				"Impossibile trovare questo artista su Musicbrainz",
	"musicbrainz_noalbum" =>				"Impossibile trovare questo album su Musicbrainz",
	"musicbrainz_notrack" =>				"Impossibile trovare questo brano su Musicbrainz",
	"musicbrainz_noinfo" =>					"Impossibile ottenere informazioni da Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Presente",
	"musicbrainz_origin" =>					"ORIGINE",
	"musicbrainz_active" =>					"ATTIVO",
	"musicbrainz_rating" =>					"VALUTAZIONE",
	"musicbrainz_notes" =>					"NOTE",
	"musicbrainz_tags" =>					"TAG",
	"musicbrainz_externaldiscography" =>		"Discografia (%s)",
	"musicbrainz_officalhomepage" =>		"Sito ufficiale (%s)",
	"musicbrainz_fansite" =>				"Fan Site (%s)",
	"musicbrainz_lyrics" =>					"Testi (%s)",
	"musicbrainz_social" =>					"Social Network",
	"musicbrainz_microblog" =>				"Microblog",
	"musicbrainz_review" =>					"Recensioni (%s)",
	"musicbrainz_novotes" =>				"(Nessun voto)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 su %s voti",
	"musicbrainz_appears" =>				"QUESTO BRANO E' PRESENTE IN",
	"musicbrainz_credits" =>				"CREDITI",
	"musicbrainz_status" =>					"STATO",
	"musicbrainz_date" =>					"DATA",
	"musicbrainz_country" =>				"NAZIONE",
	"musicbrainz_disc" =>					"DISCO",

	// SoundCloud info panel
	"button_soundcloud" =>					"Pannello Informazioni (SoundCloud)",
	"soundcloud_trackinfo" =>				"Info Brano",
	"soundcloud_plays" =>					"Riprodotti",
	"soundcloud_downloads" =>				"Scaricati",
	"soundcloud_faves" =>					"Favoriti",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"Stato",
	"soundcloud_license" =>					"Licenza",
	"soundcloud_buy" =>						"Acquista brano",
	"soundcloud_view" =>					"Visualizza su SoundCloud",
	"soundcloud_user" =>					"Utente SoundCloud",
	"soundcloud_fullname" =>				"Nome completo",
	"soundcloud_Country" =>					"Nazione",
	"soundcloud_city" =>					"Città",
	"soundcloud_website" =>					"Visita il sito web",
	"soundcloud_not" =>						"Questo pannello mostra solo informazioni sulla musica di SoundCloud",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Pannello Informazioni (Wikipedia)",
	"wiki_nothing" =>						"Nessun risultato da Wikipedia",
	"wiki_fail" =>							"Wikipedia non ha trovato nulla riguardo '%s'",
	"wiki_suggest" =>						"Wikipedia non è riuscita a trovare nessuna pagina corrispondente a '%s'",
	"wiki_suggest2" =>						"Alcuni suggerimenti che sono usciti a riguardo",

	// Keybindings editor
	"title_keybindings" =>					"Scorciatoie da Tastiera",
	"button_volup" =>						"Volume Su",
	"button_voldown" =>						"Volume Giù",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"stelle",
	"star" =>								"stella",
	"label_tags" =>							"Tag",
	"label_wishlist" =>						"Lista dei Desideri",
	"label_viewwishlist" =>					"Visualizza la tua Lista dei Desideri",
	"label_addtow" =>						"Aggiunto alla Lista dei Desideri",
	"config_synctags" =>					"Mantieni sincronizzati i Tag con Last.FM",
	"config_loveis" =>						"Preferito in Last.FM significa",
	"playlist_xstar" =>						"%s o più stelle",
	"button_about" =>						"Informazioni su Rompr",
	"label_notfound" =>						"Brano non trovato",
	// Eg + 3 more
	"label_tagmanager" =>					"Gestione Tag",
	"label_ratingmanager" =>				"Gestione Valutazione",

	//New in 0.52
	"config_alarm_ramp" =>					"Dissolvenza in Ingresso",

	// New in 0.60
	"spotify_error" =>						"Nessuna risposta da Spotify",
	"spotify_noinfo" =>						"Impossibile recuperare informazioni da Spotify",
	"button_infospotify" =>					"Pannello Informazioni (Spotify)",
	"config_icontheme" =>					"ICONE",
	"label_radio" =>						"Radio",
	"label_pop" =>							"Popolarità",
	"label_albumsby" =>						"Album di questo Artista",
	"label_singleartistradio" =>			"Brani dell'Artista",
	"label_mostplayed" =>					"Brani Preferiti",
	"label_neverplayed" =>					"Brani mai riprodotti",
	"label_radio_fartist" =>				"Radio dell'Artista preferite",
	"label_pluginplaylists" =>				"Radio Personalizzate",
	"label_recentlyadded_random" =>			"Brani aggiunti di recente (casuali)",
	"label_recentlyadded_byalbum" =>		"Album aggiunti di recente",
	"setup_mpd" =>							"Impostazioni specifiche di MPD",
	"settings_appearance" =>				"Aspetto",
	"settings_panels" =>					"Pannelli",
	"settings_language" =>					"Lingua",
	"settings_interface" =>					"Interfaccia",
	"label_charts" =>						"La tua Top 40",
	"button_subscribe" =>					"Iscriviti",
	"config_sortbycomposer" =>				"Usa il Compositore come ordinamento per Artista",
	"config_composergenre" =>				" .. solo se il Genere è:",
	"config_displaycomposer" =>				"Mostra Compositore/Esecutore in 'In Riproduzione'",
	"label_radio_mix" =>					"Raccomandazioni da Spotify",
	"label_gotnotracks" =>					"Non trovo nessun brano",
	"config_artistfirst" =>					"Artisti in cima alla collezione",
	"config_nosortprefixes" =>				"Ignora questi prefissi quando ordini gli Artisti",
	"config_low_memory_mode" =>				"Costruisci la Collezione usando la modalità 'poca memoria'",
	"config_meminfo" =>						"La modalità 'poca memoria' funziona meglio con vaste collezioni",
	"button_skipforward" =>					"Salta Avanti",
	"button_skipbackward" =>				"Salta Indietro",
	"config_snoozetime" =>					"Durata sonnellino (Min)",
	"config_ramptime" =>					"Durata dissolvenza (Sec)",
	"button_rateone" =>						"Valuta 1 Stella",
	"button_ratetwo" =>						"Valuta 2 Stelle",
	"button_ratethree" =>					"Valuta 3 Stelle",
	"button_ratefour" =>					"Valuta 4 Stelle",
	"button_ratefive" =>					"Valuta 5 Stelle",
	"button_updatecollection" =>			"Aggiorna collezione musicale",
	"label_favealbums" =>					"Album Preferiti",
	"button_nextsource" =>					"Pannello Informazioni - Cicla Fonte",
	"button_infopanel" =>					"Pannello Informazioni",
	"config_coversize" =>					"DIMENSIONE COVER ALBUM",
	"podcast_sortmode" =>					"Ordina per",
	"podcast_newestfirst" =>				"Prima i più nuovi",
	"podcast_oldestfirst" =>				"Prima i più vecchi",
	"podcast_hidedescriptions" =>			"Nascondi Descrizioni",

	//CHANGED in 0.60
	"config_country" =>						"NAZIONE (per potify)",
	"setup_labeladdresses" =>				"Se hai dei problemi di connessione, prova a usare un indirizzo IP al posto di 'localhost'",
	"setup_ipaddress" =>					"Server Mopidy o mpd",

	// ----------------------------------------------------
	// Missing Translations
	// ----------------------------------------------------
	//"config_hidepodcasts" =>				"Hide Podcasts",
	//"config_hideplaylistslist" =>			"Hide Saved Playlists",
	//"config_hidepluginplaylistslist" =>		"Hide Personalised Radio",
	//"podcast_undelete" =>					"Undelete Deleted Episodes",
	//"podcast_removedownloaded" =>			"Remove Downloaded Files",
	//"label_metabackup" =>					"Metadata Backup",
	//"button_backup" =>					"Create Backup",
	//"button_restore" =>					"Restore Backup",
	//"button_collectioncontrols" =>		"Music Collection Sort Controls",
	//"button_createplaylist" =>			"CREATE PLAYLIST",
	//"label_renameplaylist" =>				"Rename Playlist",
	//"button_plugins" =>					"All Kinds of Good Stuff",
	//"label_filename" =>					"Filename",
	//"label_resultscollection" =>			"Collection",
	//"label_resultstree" =>				"Directory Tree",
	//"label_displayresultsas" =>			"Display Results As:",
	//"label_files" =>						"Files",
	//"label_albumartist" =>				"Album Artist",
	//"config_collectionfolders" =>			"Build Collection From:",
	//"button_videos" =>					"Related Videos",
	//"label_allrandom" =>					"All Tracks At Random",
	//"config_background" =>				"BACKGROUND IMAGE",
	//"lastfm_error" =>						"Could not find information on Last.FM",
	//"config_skin" =>						"SKIN",
	//"label_albumsbyartist" =>				"Albums (by Artist)",
	//"config_wheelspeed" =>				"Mouse Wheel Scroll Speed",
	//"label_searchcollectiononly" =>		"Search Only in Music Collection",
	//"label_radio_recommend" =>			"Recommendations based on this %s",
	//"label_amendalbum" =>					"Amend Album Details",
	//"config_cdplayermode" =>				"CD Player Mode (do not queue tracks, start album from selected track)",
	//"label_recentlyplayed" =>				"Recently Played Tracks",
	//"label_simar_radio" =>				"Artists Similar To",
	//"label_tradsearch" =>					"Advanced Search",
	//"played_never" =>						"This track has never been played",
	//"played_once" =>						"This track has been played once",
	//"played_twice" =>						"This track has been played twice",
	//"played_n" =>							"This track has been played %s times",
	//"played_last" =>						"It was last played on %s",
	//"added_on" =>							"It was added to the collection on %s",
	//"button_infoyou" =>					"The Discoverator",
	//"discover_now" =>						"Track Suggestions Based On %s",
	//"config_discovembobulate" =>			"Open Discoverator On Start",
	//"label_spotify_mix" =>				"Spotify Weekly Mix",
	//"label_spotify_dj" =>					"Spotify Swim",
	//"label_spottery_lottery" =>			"Spotify Surprise!",
	//"label_dailymix" =>					"Your Daily Mix",
	//"label_luckydip" =>					"Your Lucky Dip",
	//"label_startshere" =>					"Your Discovery Starts Here",
	//"label_getspotify" =>					"Get Spotify To Start Discovering",
	//"because_liked" =>					"You like %s, so you might like:",
	//"because_listened" =>					"Similar to %s:",
	//"albumart_findsmall" =>				"Find Small Images",
	//"label_smartsetup" =>					"Preparing. Please Wait A Moment....",
	//"button_sleep" =>						"Sleep Timer",
	//"label_tuneinradio" =>				"TuneIn Radio Directory",
	//"label_generalsettings" =>			"General Settings",
	//"config_beetsserver" =>				"Location of Beets Server (ip.address:port)",
	//"config_players" =>					"Players",
	//"button_edit_players" =>				"Edit Players",
	//"label_play_all" =>					"Play All",
	//"label_last_played" =>				"Last Played:",
	//"label_station_website" =>			"Station Website",
	//"label_play_whole_album" =>			"Play Whole Album",
	//"label_from_collection" =>			"Play All Tracks From Collection",
	//"label_with_ratings" =>				"Play Only Tracks With Ratings",
	//"label_with_tags" =>					"Play Only Tracks With Tags",
	//"label_with_tagandrat" =>				"Play Only Tracks With Tags And Ratings",
	//"label_with_tagorrat" =>				"Play Only Tracks With Tags Or Ratings",
	//"config_google_credentials" =>		"Google API Credentials",
	//"config_read_the_docs" =>				"Please Read The Documentation",
	//"label_dateadded" =>					"Date Added",
	//"label_radiostation" =>				"Radio Station",
	//"label_opmlimporter" =>				"OPML Importer",
	//"config_playerintitlebar" =>			"Show Player Name in Titlebar",
	//"label_communityradio" =>				"Community Radio Browser",
	//"label_volume" =>						"Volume",
	//"config_playlistswipe" =>				"Swipe to remove tracks from Current Playlist",
	//"button_debuginfo" =>					"Debug Information",
	//"config_podcast_defaults" =>			"Default Options For New Podcasts",
	//"config_marknewasunlistened" =>		"Mark New Episodes as Unlistened Before Refresh",
	//"config_albumartinplaylist" =>		"Show Album Art in Current Playlist",
	//"label_resume" =>						"Resume",
	//"label_sortby" =>						"Sort By",
	//"label_then" =>						"Then",
	//"label_publisher" =>					"Publisher",
	//"label_category" =>					"Category",
	//"label_new_episodes" =>				"New Episodes",
	//"label_unlistened_episodes" =>		"Unlistened Episodes",
	//"label_loading" =>					"Loading...",
	//"label_choosefile" =>					"Choose A File",
	//"label_choosefiles" =>				"Choose File(s)",
	//"label_changevery" =>					"Change Every",
	//"label_albumstolistento" =>			"Albums To Listen To",
	//"no_albumtolistento" =>				"You can add any Spotify album to this list from the Info Panel, you can then come back and check them out at your leisure.",
	//"label_addedtolistenlater" =>			"Added To Albums To Listen To",
	//"label_all_time" =>					"Entire Collection",
	//"label_today" =>						"Added Today",
	//"label_thisweek" =>					"Added This Week",
	//"label_thismonth" =>					"Added This Month",
	//"label_thisyear" =>					"Added This Year",
	//"label_searchtrack" =>				"Search For This Track",
	//"label_removefromwl" =>				"Remove Track From Wishlist",
	//"label_gethelp" =>					"Click For Help",
	//"label_podcastcontrols" =>			"Podcast Search and Sort Controls",
	//"label_closepanel" =>					"Close this Panel",
	//"label_hidepanel" =>					"Hide This Panel",
	//"label_removefromplaylist" =>			"Remove From Playlist",
	//"label_addtolistenlater" =>			"Add To Albums To Listen To",
	//"label_removefromlistenlater" =>		"Remove From Albums To Listen To",
	//"label_addtocollection" =>			"Add Album To Music Collection",
	//"label_addtoradio" =>					"Add To Your Radio Stations",
	//"button_logout" =>					"Logout",
	//"label_transferplaylist" =>			"Transfer Play Queue To New Player?",
	//"podcast_refresh_all" =>				"Refresh All Podcasts",
	//"label_global_controls" =>			"Global Controls",
	//"label_topleft" =>					"Top Left",
	//"label_topright" =>					"Top Right",
	//"label_bottomleft" =>					"Bottom Left",
	//"label_bottomright" =>				"Bottom Right",
	//"label_centre" =>						"Centered",
	//"config_preferlocal" =>				"Prefer Local Music to Internet Sources",
	//"config_lastfm_playcounts" =>			"Use Last.FM Playcounts",
	//"config_sync_lastfm_playcounts" =>		"Synchronise Last.FM Playcounts At Start",
	//"label_lfm_playcountimporter" =>		"Last.FM Playcount Importer",
	//"label_mustlogintolfm" =>				"You must be logged in to Last.FM to use this feature",
	//"label_lfm_syncing" =>				"Syncing Last.FM Playcounts",
	//"label_lfm_nonew" =>					"No new tracks have been added to the Music Collection since the last import on %s",
	//"config_smart_chunksize" =>			"Number of upcoming tracks to display",
	//"warning_smart_debug" =>				"WARNING! Running Personal Radio with debugging enabled may crash your browser!",
	//"label_unplayabletracks" =>			"Unplayable Tracks",
	//"label_no_unplayable" =>				"There are no unplayable tracks in your Collection",
	//"label_removefromcol" =>				"Remove From Collection",
	//"label_audiobooks" =>					"Spoken Word",
	//"config_hideaudiobooks" =>			"Hide Spoken Word",
	//"config_audiobook_directory" =>		"Directory Containing Spoken Word Files",
	//"error_imageupload" =>				"Failed To Upload Image",
	//"error_toomanyimages" =>				"Too many images, or image file too big",
	//"error_sendingcommands" =>			"Failed Sending Commands To %s",
	//"error_cantdeleteplayer" =>			"You cannot delete the player you're currently using",
	//"error_duplicateplayer" =>			"You cannot have two players with the same name",
	//"error_backupfail" =>					"Failed to %s backup",
	//"error_nogenres" =>					"Please choose some Genres",
	//"error_collectionupdate" =>			"Music Collection Update Failed",
	//"error_nocol" =>						"Already Updating Collection!",
	//"error_dupkey" =>						"Key '%s' is already used by '%s'",
	//"error_dlpfail" =>					"Something went wrong checking the download progress!",
	//"error_refreshfail" =>				"Podcast Refresh Failed",
	//"error_trfailed" =>					"Failed to Transfer Playlist",
	//"error_trackexists" =>				"That track is already in the collection",
	//"error_nosearchnow" =>				"Cannot Search while updating collection",
	//"label_backupcreated" =>				"Backup Created",
	//"label_sleepon" =>					"Sleep Timer Enabled",
	//"label_addedtocol" =>					"Added track to Collection",
	//"label_addedtosw" =>					"Added track to Spoken Word",
	//"label_addedradio" =>					"Added To Your Radio Stations",
	//"label_updatedone" =>					"Music Collection Updated",
	//"label_addingalbum" =>				"Adding Album To Collection",
	//"error_truncated" =>					"Browser history has been truncated - artist cannot be displayed",
	//"error_noplayer" =>					"Could not get a response from the player!",
	//"label_preparing" =>					"Preparing. Please Wait While RompЯ Calculates...",
	//"label_scanningf" =>					"Scanning Folder %s",
	//"label_fremaining" =>					"%s folders remaining",
	//"label_scanningp" =>					"Scanning Playlist %s",
	//"importer_status" =>					"Done %s of %s. Elapsed %s, Remaining %s",
	//"label_playcount" =>					"Playcount",
	//"label_lfm_playcount" =>				"Last.FM Playcount",
	//"label_norecdata" =>					"Once RompЯ has gathered some data, it will show recommendations here. Play some music!",
	//"label_dailymixdesc" =>				"A playlist just for you, a mix of tracks you know and new music you might love. Powered by Last.FM %s",
	//"label_luckydipdesc" =>				"A radio station just for you, playing a wider range of music by artists you know and artists you don't yet love. Powered by Last.FM %s",
	//"label_goonlogin" =>					"Log in to Last.FM and start scrobbling. RompЯ can then delight you with new music you're going to love!",
	//"label_nospotify" =>					"Use Mopidy with a Spotify Premium subscription or a Google Play Music subscription, and start scrobbbling to Last.FM so RompЯ can delight you with new music you're going to love!",
	//"label_spotimixdesc" =>				"A radio station of suggestions based on your recent listening. Powered by RompЯ and Spotify",
	//"label_spotiswimdesc" =>				"Scanning the vastness of Spotify. Powered by RompЯ and Spotify",
	//"label_opmlexp" =>					"OPML Export",
	//"button_opmlexp" =>					"Export Podcasts As OPML",
	//"button_selectall" =>					"Select All",
	//"button_selectnone" =>				"Select None",
	//"button_import" =>					"Import Selected",
	//"label_onlyspotify" =>				"This panel is only applicable if your player can play Spotify",
	//"label_daylabels" =>					array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
	//"label_alarm_play_specific" =>		"Play This Item :",
	//"label_alarm_to_play" =>				"Drop Item Here",
	//"label_every_day" =>					"Every Day",
	//"label_every_wday" =>					"Every Weekday",
	//"label_every_wend" =>					"Every Weekend",
	//"label_new_alarm" =>					"Create New Alarm...",
	//"label_delete_alarm" =>				"Delete This Alarm",
	//"config_hidesearcher" =>				"Hide Search Panel",
	//"label_refreshinprogress" =>			"Podcasts are already being refreshed. Try again later",
	//"button_addtoplaylist" =>				"Add To Saved Playlist",
	//"config_snapcast" =>					"Snapcast",
	//"config_snapcast_server" =>			"Snapcast Server",
	//"config_snapcast_port" =>				"Port",
	//"snapcast_notthere" =>				"Could not contact Snapcast server",
	//"snapcast_group" =>					"Group ",
	//"snapcast_changegroup" =>				"Change Group",
	//"snapcast_latency" =>					"Latency ",
	//"snapcast_setlatency" =>				"Set Latency",
	//"snapcast_notconnected" =>			"(Not Connected)",
	//"label_lastfm_mix_7day" =>			"Last.FM Daily Mix",
	//"label_lastfm_mix_1month" =>			"Last.FM Monthly Mix",
	//"label_lastfm_mix_12month" =>			"Last.FM Yearly Mix",
	//"label_lastfm_mix_overall" =>			"Last.FM All Time Mix",
	//"label_lastfm_dip_7day" =>			"Last.FM Recommends",
	//"label_lastfm_dip_1month" =>			"Last.FM Lucky Dip",
	//"label_lastfm_dip_12month" =>			"Last.FM Review of the Year",
	//"label_lastfm_dip_overall" =>			"Last.FM Nostalgia Trip",
	//"config_alarm_stopafter" =>			"Stop After (mins)",
	//"label_move_to_audiobooks" =>			"Move To Spoken Word",
	//"label_move_to_collection" =>			"Move To Music Collection",
	//"label_removealbum" =>				"Remove Album From Collection",
	//"label_subbed_podcasts" =>			"Subscribed Podcasts",
	//"podcast_tooltip_unlistened" =>		"Mark as Unlistened",
	//"label_addtoqueue" =>					"Add to Play Queue",
	//"label_resetresume" =>				"Reset Resume Position",
	//"label_sameascollection" =>			"Same As Collection",
	//"label_duration_seconds" =>			"Duration (seconds)",
	//"label_year" =>						"Year",
	//"label_is" =>							"is",
	//"label_is_not" =>						"is not",
	//"label_contains" =>					"contains",
	//"label_does_not_contain" =>			"does not contain",
	//"label_exists" =>						"exists",
	//"label_lessthan" =>					"is less than",
	//"label_equals" =>						"is equal to",
	//"label_greaterthan" =>				"is greater than",
	//"label_any_rule" =>					"Tracks must match at least one rule",
	//"label_all_rules" =>					"Tracks must match all rules",
	//"label_choose_one" =>					"Choose One...",
	//"error_norules" =>					"You must create some rules",
	//"label_ruleoptions" =>				"Rule Options",
	//"label_genres" =>						"Genres",
	//"label_createcustom" =>				"Create Custom Radio Station",
	//"label_edit" =>						"Edit",
	//"label_dayssince" =>					"Days since Last Played",
	//"label_disc" =>						"Disc Number",
	//"label_tracktitle" =>					"Track Title",
	//"label_albumtitle" =>					"Album Title",
	//"label_tracknumber" =>				"Track Number",
	//"config_use_original_releasedate" =>		"Use Original Release Date for Album Date, if present",
);

?>
