<?php

language::add_translations([

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Kolekcja muzyki",
	"button_file_browser" =>				"Przeglądarka plików",
	"button_internet_radio" =>				"Internetowe stacje radiowe",
	"button_albumart" =>					"Menedżer okładek",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Ukryj/Pokaż panel źródeł",
	"button_back" =>						"Cofnij",
	"button_history" =>						"Historia",
	"button_forward" =>						"Do przodu",
	"button_toggleplaylist" =>				"Ukryj/Pokaż listę odtwarzania",

	// Tooltips for playlist buttons
	"button_alarm" =>						"Budzik",
	"button_prefs" =>						"RompЯ Preferencje",
	"button_clearplaylist" =>				"Wyczyść/Usuń Listę odtwarzania",
	"button_loadplaylist" =>				"Załaduj zapisaną listę odtwarzania",
	"button_saveplaylist" =>				"Zapisz listę odtwarzania",

	// Tooltips for playback controls
	"button_previous" =>					"Poprzedni utwór",
	"button_play" =>						"Graj/pauza",
	"button_stop" =>						"Stop",
	"button_stopafter" =>					"Zatrzymaj się po obecnym utworze",
	"button_next" =>						"Następny utwór",
	"button_love" =>						"Uwielbiam ten utwór",
	"button_ban" =>							"Zabroń tego utworu",
	"button_volume" =>						"Głośność",

	// Configuration menu entries
	"config_theme" =>						"TEMAT",
	"config_hidealbumlist" =>				"Ukryj kolekcję muzyki",
	"config_hidefileslist" =>				"Ukryj listę/przeglądarkę plików",
	"config_hideradio" =>					"Ukryj stacje radiowe",
	"config_hidepodcasts" =>				"Ukryj podcasty",
	"config_hideplaylistslist" =>			"Ukryj zapisane listy odtwarzania",
	"config_hidepluginplaylistslist" =>		"Ukryj spersonalizowane radio",
	"config_hidebrowser" =>					"Ukryj panel informacyjny",
	"config_lastfmlang" =>					"Język dla Last.fm i Wikipedii",
	"config_lastfmdefault" =>				"Język domyślny (angielski)",
	"config_lastfminterface" =>				"RompЯ's język interfejsu",
	"config_lastfmbrowser" =>				"Domyślny język przeglądarki",
	"config_autoscroll" =>					"Automatycznie - Przewiń listę odtwarzania na bieżąco grane audio",
	"config_autocovers" =>					"Automatycznie pobieraj okładki",
	"config_musicfolders" =>				"Aby korzystać z grafiki lub uzyskać teksty z plików audio (lyrics) , wprowadź ścieżkę do swojej muzyki w tym polu:",
	"config_crossfade" =>					"Płynne przechodzenie między ścieżkami audio (sekundy)",
	"config_doubleclick" =>					"Kliknij dwukrotnie, aby odtworzyć, pojedyncze kliknięcie, aby wybrać",
	"config_singleclick" =>					"Pojedyncze kliknięcie, żeby grać",
	"config_sortbydate" =>					"Sortowanie albumów według daty",
	"config_notvabydate" =>					"Nie stosuj sortowania według daty dla 'Various Artists'",
	"config_updateonstart" =>				"Zaktualizuj kolekcję muzyki przy starcie",
	"config_updatenow" =>					"Zaktualizuj kolekcję muzyki teraz",
	"config_rescan" =>						"Przeskanuj całą lokalną bazę muzyki",
	"config_editshortcuts" =>				"Edytuj skróty klawiatury...",
	"config_audiooutputs" =>				"Wyjścia dźwiękowe",
	"config_lastfmusername" =>				"Last.FM Nazwa użytkownika",
	"config_loginbutton" =>					"Zaloguj się",
	"config_scrobbling" =>					"Śledź (Scrobble) swoje utwory do Last.FM",
	"config_noscrobble_audiobook" =>		"Nie śledź utworów Poezji mówionej (Spoken Word)",
	"config_noscrobble_podcast" =>			"Nie śledź utworów z Podcastów",
	"config_autocorrect" =>					"Użyj Last.FM do automatycznej korekty nazw artystów itp",
	"config_tagloved" =>					"Oznacz ulubiony utwór tagiem:",
	"config_fontsize" =>					"ROZMIAR CZCIONKI",
	"config_fontname" =>					"STYL CZCIONKI",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Zapisz",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Wyszukaj muzykę",
	"label_yourradio" =>					"Twoje stacje radiowe",
	"label_podcasts" =>						"Podcasty",
	"label_somafm" =>						"Soma FM",
	"label_emptyinfo" =>					"To jest panel informacyjny. Gdy zagrasz muzykę , Pojawią się tutaj ciekawe żeczy",
	"button_playlistcontrols" =>			"Kontrola listy odtwarzania",
	"button_random" =>						"LOSOWO",
	"button_crossfade" =>					"TRYB SINGLA",
	"button_repeat" =>						"POWTÓRZ",
	"button_consume" =>						"ZAGRAJ i USUŃ",
	"label_yes" =>							"TAK",
	"label_no" =>							"NIE",
	"label_updating" =>						"Aktualizacja muzycznej kolekcji",
	"label_update_error" =>					"Nie udało się wygenerować kolekcji muzyki.",
	"label_playlisterror" =>				"Coś poszło nie tak, odzyskanie listy odtwarzania!",
	"button_OK" =>							"OK",
	"button_cancel" =>						"Anuluj",
	"error_playlistname" =>					"Nazwa listy odtwarzania nie może zawierać ukośnika",
	"label_savedpl" =>						"Lista odtwarzania zapisana jako %s",

	// Search Forms
	"label_searchfor" =>					"Szukaj",
	"label_searching" =>					"Szukam...",
	"label_searchresults" =>				"Wynik wyszukiwania",

	// General multipurpose labels
	"label_tracks" =>						"utwory",
	"label_albums" =>						"albumy",
	"label_artists" =>						"atryści",
	"label_track" =>						"Utwór",
	"label_album" =>						"Album",
	"label_artist" =>						"Artysta",
	"label_anything" =>						"Wszystko",
	"label_genre" =>						"Gatunek",
	"label_composer" =>						"Kompozytor",
	"label_performer" =>					"Wykonawca",
	"label_rating" =>						"Ocena",
	"label_tag" =>							"Tag",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"Wystąpił błąd. Odśwież stronę i spróbuj ponownie",
	"label_days" =>							"dni",
	"label_noalbums" =>						"Nie znaleziono albumów",
	"label_duration" =>						"Czas trwania",
	"label_playererror" =>					"Błąd odtwarzania",
	"button_playradio" =>					"Graj",

	// Playlist and Now Playing
	"label_notforradio" =>					"Nie obsługiwane dla strumieni radiowych",
	"label_incoming" =>						"Nadchodzący...",
	"label_addingtracks" =>					"Utwory w kolejce",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"artysta / zaspół",
	"label_on" =>							"wydany przez",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"z",

	// Podcasts
	"podcast_entrybox" =>					"Subskrybuj kanał RSS:",
	// Podcast tooltips
	"podcast_delete" =>						"Usuń ten podcast",
	"podcast_configure" =>					"Skonfiguruj ten podcast",
	"podcast_refresh" =>					"Odśwież ten podcast",
	"podcast_download_all" =>				"Pobierz wszystkie odcinki tego podcastu",
	"podcast_mark_all" =>					"Zaznacz wszystkie odcinki, jako odsłuchane",
	"podcast_undelete" =>					"Przywróć usunięte odcinki",
	"podcast_removedownloaded" =>			"Usuń pobrane pliki",
	// Podcast display options
	"podcast_display" =>					"Wyświetlacz",
	"podcast_display_all" =>				"Wszystko",
	"podcast_display_onlynew" =>			"Tylko nowe",
	"podcast_display_unlistened" =>			"Nowe i nieodsłuchane",
	"podcast_display_downloadnew" =>		"Nowe i pobrane",
	"podcast_display_downloaded" =>			"Tylko pobrane",
	// Podcast refresh options
	"podcast_refresh" =>					"Odświż",
	"podcast_refresh_never" =>				"Ręcznie",
	"podcast_refresh_hourly" =>				"Co godzinę",
	"podcast_refresh_daily" =>				"Codziennie",
	"podcast_refresh_weekly" =>				"Cotygodniowo",
	"podcast_refresh_monthly" =>			"Comiesięcznie",
	// Podcast auto expire
	"podcast_expire" =>						"Zachowaj odcinki",
	"podcast_expire_tooltip" =>				"Wszelkie odcinki starsze od tej wartości zostaną usunięte z listy. Zmiany w tej opcji pojawią się następnym razem, gdy odświeżysz podcast",
	"podcast_expire_never" =>				"Kiedykolwiek",
	"podcast_expire_week" =>				"Raz na tydzień",
	"podcast_expire_2week" =>				"Dwa tygodnie",
	"podcast_expire_month" =>				"Jeden miesiąc",
	"podcast_expire_2month" =>				"Dwa miesiące",
	"podcast_expire_6month" =>				"Sześć miesięcy",
	"podcast_expire_year" =>				"Rok",
	// Podcast number to keep
	"podcast_keep" =>						"Numer do zachowania",
	"podcast_keep_tooltip" =>				"Lista pokaże tylko wiele odcinków. Zmiany w tej opcji pojawią się następnym razem, gdy odświeżysz podcast",
	"podcast_keep_0" =>						"Nieograniczony",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Zachowaj wszystkie pobrane odcinki",
	"podcast_kd_tooltip" =>					"Włącz tę opcję, aby zachować wszystkie pobrane odcinki. Powyższe dwie opcje będą miały zastosowanie tylko do odcinków, które nie zostały pobrane",
	"podcast_tooltip_new" =>				"To jest nowy odcinek",
	"podcast_tooltip_notnew" =>				"Ten odcinek nie jest nowy, ale nie został odsłuchany",
	"podcast_tooltip_downloaded" =>			"Ten odcinek został pobrany. Kliknij, aby usunąć pobrany plik.",
	"podcast_tooltip_download" =>			"Pobierz ten odcinek na swój komputer",
	"podcast_tooltip_mark" =>				"Oznacz jako odsłuchane",
	"podcast_tooltip_delepisode" =>			"Usuń ten odcinek",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Proszę rozważyć obsługę Soma.FM jeśli lubisz tą stacje",

	// Your radio stations
	"label_radioinput" =>					"Wprowadź adres URL",

	//Album Art Manager
	"albumart_title" =>						"Okładka albumu",
	"albumart_getmissing" =>				"Zdobądź brakujące okładki",
	"albumart_showall" =>					"Show All Covers",
	"albumart_instructions" =>				"Kliknij okładkę, aby ją zmienić, lub przeciągnij obraz z dysku twardego lub innego okna przeglądarki",
	"albumart_onlyempty" =>					"Pokaż tylko albumy bez okładek",
	"albumart_allartists" =>				"Wszyscy artyści",
	"albumart_googlesearch" =>				"Wyszukiwanie Bing",
	"albumart_local" =>						"Obrazy lokalne",
	"albumart_upload" =>					"Prześlij plik",
	"albumart_uploadbutton" =>				"Wgrywać",
	"albumart_newtab" =>					"Google w nowej karcie",
	"albumart_dragdrop" =>					"Możesz przeciągać i upuszczać obrazy z dysku twardego lub innego okna przeglądarki bezpośrednio na obraz (w większości przeglądarek)",
	"albumart_showmore" =>					"Pokaż więcej wyników",
	"albumart_googleproblem" =>				"Był problem. Bing powiedział",
	"albumart_getthese" =>					"Zdobądź te okładki",
	"albumart_nocovercount" =>				"albumy bez okładki",
	"albumart_getting" =>					"Getting",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr nie mógł połączyć się z serwerem MPD lub Mopidy",
	"setup_connecterror" =>					"Wystąpił błąd podczas komunikowania się z serwerem MPD lub Mopidy: ",
	"setup_request" =>						"Poprosiłeś o stronę konfiguracji",
	"setup_addressnote" =>					"Uwaga: localhost w tym kontekście oznacza komputer, na którym uruchomiony jest serwer WWW",
	"setup_port" =>							"Port",
	"setup_advanced" =>						"Opcje zaawansowane",
	"setup_password" =>						"Hasło",
	"setup_unixsocket" =>					"UNIX-domain socket",
	"setup_websocket_port" =>				"Websocket Port",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Zaloguj się do Last.FM",
	"lastfm_login1" =>						"Kliknij poniższy link, aby otworzyć witrynę Last.FM. Wprowadź szczegóły logowania Last.FM w razie potrzeby, dodaj RompЯ do zaufanych programów aby uzyskania dostępu do konta",
	"lastfm_login2" =>						"Po zakończeniu możesz zamknąć nową kartę, ale nie zamykaj tego okna dialogowego!",
	"lastfm_loginbutton" =>					"Kliknij tutaj, aby się zalogować",
	"lastfm_login3" =>						"Po zalogowaniu się do Last.FM kliknij przycisk OK poniżej, aby zakończyć proces",
	"lastfm_loginfailed" =>					"Nie udało się zalogować do Last.FM",
	"label_loved" =>						"Ulubiony",
	"label_lovefailed" =>					"Nie udało się zrobić ulubionym",
	"label_unloved" =>						"Niechciany",
	"label_unlovefailed" =>					"Nie udało się usunąć ulubiony",
	"label_scrobblefailed" =>				"Śledzenie (scrobble) nie powiodło się",

	// Info Panel
	"info_gettinginfo" =>					"Uzyskanie informacji...",
	"info_newtab" =>						"Widok w nowej zakładce",

	// File Info panel
	"button_fileinfo" =>					"Panel info.(Informacje o utworze/kolekcji)",
	"info_file" =>							"Plik",
	"info_from_beets" =>					"(z serwera beets)",
	"info_format" =>						"Format:",
	"info_bitrate" =>						"Bitrate:",
	"info_samplerate" =>					"Sample Rate:",
	"info_mono" =>							"Mono",
	"info_stereo" =>						"Stereo",
	"info_channels" =>						"Kanały",
	"info_date" =>							"Data:",
	"info_genre" =>							"Gatunek:",
	"info_performers" =>					"Wykonawcy:",
	"info_composers" =>						"Kompozytorzy:",
	"info_comment" =>						"Komentarz:",
	"info_label" =>							"Etykieta:",
	"info_disctitle" =>						"Tytuł dysku:",
	"info_encoder" =>						"Enkoder:",
	"info_year" =>							"Rok:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Panel info.(Last.FM)",
	"label_notrackinfo" =>					"Nie można znaleźć informacji o tym utworze",
	"label_noalbuminfo" =>					"Nie można znaleźć informacji o tym albumie",
	"label_noartistinfo" =>					"Nie można znaleźć informacji o tym artyście",
	"lastfm_listeners" =>					"Słuchających:",
	"lastfm_plays" =>						"Granych:",
	"lastfm_yourplays" =>					"Ty grałeś:",
	"lastfm_toptags" =>						"Najlepsze TAGI:",
	"lastfm_addtags" =>						"DODAJ TAG",
	"lastfm_addtagslabel" =>				"Add tags, comma separated",
	"button_add" =>							"DODAJ",
	"lastfm_yourtags" =>					"TWOJE TAGI:",
	"lastfm_simar" =>						"Podobni artyści",
	"lastfm_removetag" =>					"Usuń Tag",
	"lastfm_releasedate" =>					"Data wydania",
	"lastfm_viewtrack" =>					"Zobacz utwór na Last.FM",
	"lastfm_tagerror" =>					"Nie udało się zmodyfikować tagów",
	"lastfm_loved" =>						"Ulubiony",
	"lastfm_lovethis" =>					"Uwielbiam ten utwór",
	"lastfm_unlove" =>						"Nie lubię tego utworu",
	"lastfm_notfound" =>					"%s Nie znaleziono",

	// Lyrics info panel
	"button_lyrics" =>						"Panel info.(Lyrics)",
	"lyrics_lyrics" =>						"Lyrics",
	"lyrics_nonefound" =>					"Lyrics nic nie znalazł",
	"lyrics_info" =>						"Aby korzystać z Lyrics (tekstów piosenek), musisz upewnić się, że Twoje pliki lokalne są otagowane przez Lyrics",
	"lyrics_nopath" =>						"Aby korzystać z Lyrics (tekstów piosenek), musisz upewnić się, że Twoje pliki lokalne są otagowane przez Lyrics i ustawić ścieżkę do muzyki w preferencjach",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"ROK",
	"title_title" =>						"TYTUŁ",
	"title_type" =>							"TYP",
	"title_label" =>						"ETYKIETA",
	"label_pages" =>						"STRONY",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"FIRMY / WYDAWNICTWA",
	"discogs_personnel" =>					"PERSONEL",
	"discogs_videos" =>						"FILMY",
	"discogs_styles" =>						"STYLE",
	"discogs_genres" =>						"GATUNKI",
	"discogs_tracklisting" =>				"LISTA UTWORÓW",
	"discogs_realname" =>					"PRAWDZIWE NAZWISKO:",
	"discogs_aliases" =>					"ALIASY:",
	"discogs_alsoknown" =>					"ZNANY(A) RÓWNIEŻ JAKO:",
	"discogs_external" =>					"LINKI ZEWNĘTRZNE",
	"discogs_bandmembers" =>				"CZŁONKOWE ZESPOŁU",
	"discogs_memberof" =>					"CZŁONEK",
	"discogs_discography" =>				"%s DYSKOGRAFIA",

	// Discogs info panel
	"button_discogs" =>						"Panel info.(Discogs)",
	"discogs_error" =>						"Nie znaleziono nic na Discogs",
	"discogs_nonsense" =>					"Nie można uzyskać rozsądnej odpowiedzi na Discogs",
	"discogs_noalbum" =>					"Nie można znaleźć tego albumu na Discogs",
	"discogs_notrack" =>					"Nie można znaleźć tego utworu na Discogs",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Panel info.(Musicbrainz)",
	"musicbrainz_error" =>					"Nie otrzymano odpowiedzi z MusicBrainz",
	"musicbrainz_contacterror" =>			"Wystąpił błąd kontaktowy z Musicbrainz",
	"musicbrainz_noartist" =>				"Nie można znaleźć tego artysty na Musicbrainz",
	"musicbrainz_noalbum" =>				"Nie można znaleźć tego albumu na Musicbrainz",
	"musicbrainz_notrack" =>				"Nie można znaleźć tego utworu na Musicbrainz",
	"musicbrainz_noinfo" =>					"Nie można uzyskać informacji z Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Obecny",
	"musicbrainz_origin" =>					"POCHODZENIE",
	"musicbrainz_active" =>					"AKTYWNY",
	"musicbrainz_rating" =>					"OCENA",
	"musicbrainz_notes" =>					"NOTATKI",
	"musicbrainz_tags" =>					"TAGI",
	"musicbrainz_externaldiscography" =>	"Dyskografia (%s)",
	"musicbrainz_officalhomepage" =>		"Oficjalna strona główna (%s)",
	"musicbrainz_fansite" =>				"Witryna fanów (%s)",
	"musicbrainz_lyrics" =>					"Lyrics (%s)",
	"musicbrainz_social" =>					"Sieć społecznościowa (%s)",
	"musicbrainz_streaming" =>				"Bezpłatny streaming (%s)",
	"musicbrainz_microblog" =>				"Mikroblog",
	"musicbrainz_review" =>					"Recenzja (%s)",
	"musicbrainz_purchase" =>				"Zakup (%s)",
	"musicbrainz_novotes" =>				"(Brak rankingu)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 z %s głosów",
	"musicbrainz_appears" =>				"TEN UTWÓR POJAWIA SIĘ NA",
	"musicbrainz_credits" =>				"KREDYTY",
	"musicbrainz_status" =>					"STATUS",
	"musicbrainz_date" =>					"DATA",
	"musicbrainz_country" =>				"KRAJ",
	"musicbrainz_disc" =>					"DYSK",
	"musicbrainz_album_releases" =>			"WYDANIA TEGO ALBUMU",

	// SoundCloud info panel
	"button_soundcloud" =>					"Panel info.(SoundCloud)",
	"soundcloud_trackinfo" =>				"Informacje o utworze",
	"soundcloud_plays" =>					"Odtwarza",
	"soundcloud_downloads" =>				"Pobieranie",
	"soundcloud_faves" =>					"Ulubione",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"Państwo",
	"soundcloud_license" =>					"Licencja",
	"soundcloud_buy" =>						"Kup utwór",
	"soundcloud_view" =>					"Zobacz na SoundCloud",
	"soundcloud_user" =>					"SoundCloud Użytkownik",
	"soundcloud_fullname" =>				"Pełne imię i nazwisko",
	"soundcloud_Country" =>					"Kraj",
	"soundcloud_city" =>					"Miasto",
	"soundcloud_website" =>					"Odwiedź stronę internetową",
	"soundcloud_not" =>						"Ten panel wyświetli tylko informacje o muzyce z SoundCloud",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Panel info.(Wikipedia)",
	"wiki_nothing" =>						"Nic nie mam na Wikipedii",
	"wiki_fail" =>							"Wikipedia nie mogła znaleźć niczego związanego z '%s'",
	"wiki_suggest" =>						"Wikipedia nie była w stanie znaleźć żadnych pasujących stron '%s'",
	"wiki_suggest2" =>						"Oto kilka sugestii, jakie podano",

	// Keybindings editor
	"title_keybindings" =>					"Skróty klawiatury",
	"button_volup" =>						"Pogłośnij",
	"button_voldown" =>						"Przycisz",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"gwiazdki",
	"star" =>								"gwiazdka",
	"label_tags" =>							"Tagi",
	"label_wishlist" =>						"Lista życzeń",
	"label_viewwishlist" =>					"Zobacz swoją listę życzeń",
	"label_addtow" =>						"Dodano do listy życzeń",
	"config_synctags" =>					"Trzymaj tagi zsynchronizowane z Last.FM",
	"config_loveis" =>						"Last.FM zaznacz ulubione utwory",
	"playlist_xstar" =>						"%s lub więcej gwiazdek",
	"button_about" =>						"O programie RompЯ",
	"label_notfound" =>						"Nie znaleziono utworu",
	// Eg + 3 more

	//New in 0.52
	"config_alarm_ramp" =>					"Stopniowe pogłaśnianie",

	// New in 0.60
	"spotify_error" =>						"Brak odpowiedzi ze Spotify",
	"spotify_noinfo" =>						"Nie można uzyskać informacji z Spotify",
	"button_infospotify" =>					"Panel info.(Spotify)",
	"config_icontheme" =>					"IKONY",
	"label_radio" =>						"Radio",
	"label_pop" =>							"Popularność",
	"label_albumsby" =>						"Albumy tego artysty",
	"label_singleartistradio" =>			"Utwory artysty",
	"label_mostplayed" =>					"Ulubione utwory",
	"label_neverplayed" =>					"Nigdy nie odtwarzane utwory",
	"label_radio_fartist" =>				"Ulubieni artyści",
	"label_pluginplaylists" =>				"Radio spersonalizowane",
	"label_recentlyadded_random" =>			"Ostatnio dodane utwory (losowo)",
	"label_recentlyadded_byalbum" =>		"Ostatnio dodane albumy",
	"setup_mpd" =>							"MPD / Mopidy Ustawienia",
	"settings_appearance" =>				"Wygląd",
	"settings_panels" =>					"Panels",
	"settings_language" =>					"Język",
	"settings_interface" =>					"Interfejs",
	"label_charts" =>						"Top 40",
	"button_subscribe" =>					"Subskrybować",
	"config_composergenre" =>				" .. tylko jeśli Gatunek to:",
	"config_displaycomposer" =>				"Wyświetl kompozytora/wykonawcę podczas odtwarzania",
	"label_radio_mix" =>					"Ulubieni artyści i powiązani artyści",
	"label_gotnotracks" =>					"Nie znaleziono żadnych utworów",
	"config_artistfirst" =>					"Preferowane informacje na szczycie kolekcji",
	"config_nosortprefixes" =>				"Zignoruj ten prefiks podczas sortowania",
	"button_skipforward" =>					"Przewiń do przodu",
	"button_skipbackward" =>				"Przewiń do tyłu",
	"config_snoozetime" =>					"Czas drzemki (Minuty)",
	"config_ramptime" =>					"Czas zaniku (Sekundy)",
	"button_rateone" =>						"Oceń 1 gwiazdką",
	"button_ratetwo" =>						"Oceń 2 gwiazdkami",
	"button_ratethree" =>					"Oceń 3 gwiazdkami",
	"button_ratefour" =>					"Oceń 4 gwiazdkami",
	"button_ratefive" =>					"Oceń 5 gwiazdkami",
	"button_updatecollection" =>			"Zaktualizuj kolekcję muzyki",
	"label_favealbums" =>					"Ulubione albumy",
	"button_nextsource" =>					"Panel info. - Źródło cyklu",
	"button_infopanel" =>					"Panel Info.",
	"config_coversize" =>					"ROZMIAR OKŁADKI ALBUMU",
	"podcast_sortmode" =>					"Kolejność sortowania",
	"podcast_newestfirst" =>				"Najnowszy jako pierwszy",
	"podcast_oldestfirst" =>				"Najstarszy jako pierwszy",
	"podcast_hidedescriptions" =>			"Ukryj opisy",

	// New in 0.64/0.65/0.70
	"label_metabackup" =>					"Kopia zapasowa metadanych",
	"button_backup" =>						"Utwórz kopię zapasową",
	"button_restore" =>						"Przywróć kopię zapasową",
	"button_collectioncontrols" =>			"Kontrola sortowania kolekcji muzycznej",
	"button_createplaylist" =>				"UTWÓRZ LISTĘ ODTWARZANIA",
	"label_renameplaylist" =>				"Zmień nazwę listy odtwarzania",
	"button_plugins" =>						"Wszelkie dobre rzeczy / informacje / backup itd",
	"label_filename" =>						"Nazwa pliku",
	"label_resultscollection" =>			"Kolekcja",
	"label_resultstree" =>					"Drzewo katalogowe",
	"label_displayresultsas" =>				"Wyświetl wyniki wyszukiwania muzyki jako:",
	"label_files" =>						"Pliki",
	"label_albumartist" =>					"Artysta albumu",
	"config_collectionfolders" =>			"Zbuduj kolekcję z:",
	"button_videos" =>						"Powiązane filmy",
	"label_allrandom" =>					"Wszystkie utwory losowo",
	"label_randomalbums" =>					"Wszystkie albumy losowo",
	"config_background" =>					"Obraz tła",
	"lastfm_error" =>						"Nie można znaleźć żadnej informacji na Last.FM",
	"config_skin" =>						"SKÓRA",

	// New in 0.71
	"label_albumsbyartist" =>				"Albumy (według artysty)",
	"config_wheelspeed" =>					"Prędkość przewijania kółka myszki",

	"label_radio_recommend" =>				"Rekomendacje na podstawie tego %s",
	"label_amendalbum" =>					"Zmień szczegóły albumu",
	"label_radio_recommended" =>			"Rekomendacje dla Ciebie",

	//CHANGED in 0.60
	"config_country" =>						"KRAJ (dla Spotify)",
	"setup_labeladdresses" =>				"Jeśli masz problemy z połączeniem, spróbuj użyć adresu IP zamiast 'localhost'",
	"setup_ipaddress" =>					"Serwer Mopidy lub MPD",

	"config_cdplayermode" =>				"Tryb odtwarzacza CD (nie dodawaj utworów do kolejki, rozpocznij odtwarzanie albumu od wybranego utworu)",

	"label_recentlyplayed" =>				"Ostatnio grane utwory",
	"label_simar_radio" =>					"Artyści podobni do",

	"label_tradsearch" =>					"Zaawansowane wyszukiwanie",

	"played_never" =>						"Ten utwór nigdy nie był odtwarzany",
	"played_once" =>						"Ten utwór był odtwarzany raz",
	"played_twice" =>						"Ten utwór był odtwarzany dwukrotnie",
	"played_n" =>							"Ten utwór był odtwarzany %s ",
	"played_last" =>						"Ostatni raz grano w %s",
	"added_on" =>							"Został dodany do kolekcji %s",
	"button_infoyou" =>						"Odkrywca",
	"discover_now" =>						"Sugestie utworów na podstawie %s",
	"config_discovembobulate" =>			"Otwórz Odkrywcę przy starcie",
	"label_spotify_mix" =>					"Cotygodniowy miks Spotify",
	"label_spotify_dj" =>					"Spotify Swim",
	"label_spottery_lottery" =>				"Spotify Surprise!",
	"label_dailymix" =>						"Twój codzienny miks",
	"label_luckydip" =>						"Twój szczęśliwy traf",
	"label_startshere" =>					"Twoje Odkrywanie zaczyna się tutaj",
	"label_getspotify" =>					"Bądź online, aby zacząć odkrywać",
	"because_liked" =>						"Lubisz %s, więc może ci się spodobać:",
	"because_listened" =>					"Podobne do %s:",
	"albumart_findsmall" =>					"Znajdź małe obrazy",
	"button_sleep" =>						"Wyłącznik czasowy",
	"label_tuneinradio" =>					"TuneIn Radio Directory",
	"label_generalsettings" =>				"Ustawienia ogólne",
	"config_beetsserver" =>					"Lokalizacja serwera Beets  (ip.adres:port)",
	"config_players" =>						"Odtwarzacz AUDIO",
	"button_edit_players" =>				"Ustawienia Odtwarzacza",

	"label_play_all" =>						"Odtwórz wszystko tego artysty",
	"label_last_played" =>					"Ostatnio grane:",
	"label_station_website" =>				"Strona internetowa stacji",

	"label_play_whole_album" =>				"Odtwórz cały album",
	"label_from_collection" =>				"Odtwarzaj wszystkie utwory z kolekcji",
	"label_with_ratings" =>					"Odtwarzaj tylko utwory z ocenami",
	"label_with_tags" =>					"Odtwarzaj tylko utwory z tagami",
	"label_with_tagandrat" =>				"Odtwarzaj tylko utwory z tagami i ocenami",
	"label_with_tagorrat" =>				"Odtwarzaj tylko utwory z tagami lub ocenami",
	"config_google_credentials" =>			"Dane uwierzytelniające API Bing",
	"config_read_the_docs" =>				"Przeczytaj dokumentację",
	"label_dateadded" =>					"Dodano datę",
	"label_radiostation" =>					"Stacja radiowa",
	"label_opmlimporter" =>					"OPML Importowanie",
	"config_playerintitlebar" =>			"Pokaż nazwę odtwarzacza w tytule przeglądarki internetowej",
	"label_communityradio" =>				"Wspólnota - Radio Browser",
	"label_volume" =>						"Głośność",
	"button_debuginfo" =>					"Informacje o debugowaniu",
	"config_podcast_defaults" =>			"Domyślne opcje nowych podcastów",
	"config_marknewasunlistened" =>			"Oznacz nowe odcinki jako nieodsłuchane przed odświeżeniem",
	"config_albumartinplaylist" =>			"Pokaż okładkę albumu w kolejce odtwarzania",
	"label_resume" =>						"Wznawiać",
	"label_sortby" =>						"Sortuj według",
	"label_then" =>							"Następnie",
	"label_publisher" =>					"Wydawca",
	"label_category" =>						"Kategoria",
	"label_new_episodes" =>					"Nowe odcinki",
	"label_unlistened_episodes" =>			"Nieodsłuchane odcinki",
	"label_loading" =>						"Ściągam...",
	"label_choosefile" =>					"Wybierz plik A",
	"label_choosefiles" =>					"Wybierz plik(i)",
	"label_changevery" =>					"Zmień każdy",
	"label_albumstolistento" =>				"Albumy do słuchania",
	"no_albumtolistento" =>					"Możesz dodać dowolny album Spotify do tej listy z Panelu informacyjnego. Następnie możesz wrócić i przejrzeć go w dowolnym momencie.",
	"label_addedtolistenlater" =>			"Dodano do albumów do odsłuchania",
	"label_all_time" =>						"Cała kolekcja",
	"label_today" =>						"Dodano dzisiaj",
	"label_thisweek" =>						"Dodano w tym tygodniu",
	"label_thismonth" =>					"Dodano w tym miesiącu",
	"label_thisyear" =>						"Dodano w tym roku",
	"label_searchtrack" =>					"Wyszukaj ten utwór",
	"label_removefromwl" =>					"Usuń utwór z listy życzeń",
	"label_gethelp" =>						"Kliknij, aby uzyskać pomoc",
	"label_podcastcontrols" =>				"Wyszukiwanie podcastów i kontrola sortowaniem",
	"label_closepanel" =>					"Zamknij ten panel",
	"label_hidepanel" =>					"Ukryj ten panel",
	"label_removefromplaylist" =>			"Usuń z playlisty",
	"label_addtolistenlater" =>				"Dodaj do albumów, aby ich odsłuchać",
	"label_removefromlistenlater" =>		"Usuń z albumów do odsłuchania",
	"label_addtocollection" =>				"Dodaj album do kolekcji muzyki",
	"label_addtoradio" =>					"Dodaj do swoich stacji radiowych",
	"button_logout" =>						"Wyloguj się",
	"label_transferplaylist" =>				"Przenieść kolejkę na nowego odtwarzacza?",
	"label_yes" =>							"Tak",
	"label_no" =>							"Nie",
	"podcast_refresh_all" =>				"Odśwież wszystkie podcasty",
	"label_global_controls" =>				"Kontrola globalna",
	"label_topleft" =>						"Lewy górny róg",
	"label_topright" =>						"Prawy górny róg",
	"label_bottomleft" =>					"Lewy dolny róg",
	"label_bottomright" =>					"Prawy dolny róg",
	"label_centre" =>						"Wyśrodkowany",
	"label_bottomcentre" =>					"Wyśrodkowany na dole",
	"label_topcentre" =>					"Wyśrodkowany na górze",
	"config_preferlocal" =>					"Wolisz muzykę lokalną od źródeł internetowych",
	"config_lastfm_playcounts" =>			"Użyj licznika odtworzeń utworów z Last.fm",
	"config_sync_lastfm_playcounts" =>		"Synchronizuj liczbę odtworzeń z last.FM",
	"label_lfm_playcountimporter" =>		"Last.FM importer liczby odtwarzań",
	"label_mustlogintolfm" =>				"Musisz zostać zalogowany do  Last.FM , aby użyć tej funkcji",
	"label_lfm_syncing" =>					"Synchronizacja liczby odtworzeń z Last.FM",
	"label_lfm_nonew" =>					"Od ostatniego importu do kolekcji muzycznej nie dodano żadnych nowych utworów %s",
	"config_smart_chunksize" =>				"Liczba nadchodzących utworów do wyświetlenia",
	"warning_smart_debug" =>				"OSTRZEŻENIE! Uruchomienie Radia Spersonalizowanego z włączonym debugowaniem może spowodować awarię przeglądarki!",
	"label_unplayabletracks" =>				"Nieodtwarzalne utwory",
	"label_no_unplayable" =>				"W Twojej kolekcji nie ma utworów, których nie można odtworzyć",
	"label_removefromcol" =>				"Usuń z kolekcji",
	"label_audiobooks" =>					"Poezja mówiona",
	"config_hideaudiobooks" =>				"Ukryj Poezje mówioną",
	"config_audiobook_directory" =>			"Katalog zawierający pliki Poezji mówionej",
	"error_imageupload" =>					"Nie udało się przesłać obrazu",
	"error_toomanyimages" =>				"Zbyt wiele obrazów lub plik obrazu jest zbyt duży",
	"error_sendingcommands" =>				"Nie udało się wysłać poleceń do %s",
	"error_cantdeleteplayer" =>				"Nie możesz usunąć aktualnie używanego odtwarzacza",
	"error_duplicateplayer" =>				"Nie możesz mieć dwóch odtwarzaczy o tej samej nazwie",
	"error_backupfail" =>					"Nie udała się %s kopia zapasowa",
	"error_nogenres" =>						"Proszę wybrać kilka gatunków",
	"error_collectionupdate" =>				"Aktualizacja kolekcji muzycznej nie powiodła się",
	"error_nocol" =>						"Już aktualizujemy kolekcję!",
	"error_dupkey" =>						"Klucz '%s' jest już używany przez '%s'",
	"error_dlpfail" =>						"Wystąpił błąd podczas sprawdzania postępu pobierania!",
	"error_refreshfail" =>					"Odświeżenie podcastu nie powiodło się",
	"error_trfailed" =>						"Transfer listy odtwarzania nie powiódł się",
	"error_trackexists" =>					"Ten utwór jest już w kolekcji",
	"error_nosearchnow" =>					"Nie można wyszukiwać podczas aktualizacji kolekcji",
	"label_backupcreated" =>				"Kopia zapasowa została utworzona",
	"label_sleepon" =>						"Wyłącznik czasowy uruchomiony",
	"label_addedtocol" =>					"Dodano utwór do kolekcji",
	"label_addedtosw" =>					"Dodano utwór do Poezji mówionej",
	"label_addedradio" =>					"Dodano do Twoich stacji radiowych",
	"label_updatedone" =>					"Zaktualizowano kolekcję muzyki",
	"label_addingalbum" =>					"Dodanie albumu do kolekcji",
	"error_truncated" =>					"Historia przeglądarki została obcięta/skrócona - nie można wyświetlić artysty",
	"error_noplayer" =>						"Nie udało się uzyskać odpowiedzi z odtwarzacza!",
	"label_preparing" =>					"Przygotowywanie. Proszę czekać kiedy RompЯ oblicza...",
	"label_scanningf" =>					"Skanowanie folderu %s",
	"label_fremaining" =>					"%s pozostałe foldery",
	"label_scanningp" =>					"Skanowanie listy odtwarzania %s",
	"importer_status" =>					"Zrobione %s of %s. Upłynęło %s, Pozostało %s",
	"label_playcount" =>					"Liczba odtworzeń",
	"label_lfm_playcount" =>				"Liczba odtworzeń Last.FM",
	"label_norecdata" =>					"Gdy RompЯ zbierze trochę danych, tutaj pokaże rekomendacje. Włącz muzykę!",
	"label_dailymixdesc" =>					"Playlista tylko dla Ciebie, miks utworów, które znasz i nowej muzyki, którą możesz pokochać. Wydana przez %s",
	"label_luckydipdesc" =>					"Stacja radiowa tylko dla Ciebie, grająca szerszy zakres muzyki i artystów, których znasz, jak i tych, których jeszcze nie lubisz. Wydana przez %s",
	"label_goonlogin" =>					"Zaloguj się do Last.FM i zacznij scrobblować (śledzić). RompЯ może cię wtedy zachwycić nową muzyką, którą pokochasz!",
	"label_nospotify" =>					"Użyj Mopidy ze Spotify, YouTube Music , lub subskrypcję Qobuz, dzięki czemu RompR może Cię zachwycić muzyką, którą pokochasz!",
	"label_spotimixdesc" =>					"Stacja radiowa z sugestiami na podstawie ostatnio słuchanych utworów. Obsługiwane przez RompЯ i Spotify",
	"label_spotiswimdesc" =>				"Skanowanie / eksplorowanie olbrzymiej bazy audio Spotify. Obsługiwane przez RompЯ i Spotify",
	"label_opmlexp" =>						"OPML Exportowanie",
	"button_opmlexp" =>						"Eksportuj podcasty jako OPML",
	"button_selectall" =>					"Wybierz WSZYSTKO",
	"button_selectnone" =>					"Wybierz Brak",
	"button_import" =>						"Importuj wybrane",
	"label_onlyspotify" =>					"Ten panel jest dostępny tylko wtedy, gdy Twój odtwarzacz obsługuje Spotify",
	// NOTE: Sunday MUST be first
	"label_daylabels" => array("Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"),
	"label_alarm_play_specific" =>			"Graj ten utwór/pozycję :",
	"label_alarm_to_play" =>				"Upuść przedmiot tutaj",
	"label_alarm_to_play_click" =>			"Kliknij, aby wybrać element do odtworzenia",
	"label_every_day" =>					"Każdego dnia",
	"label_every_wday" =>					"Każdy dzień powszedni",
	"label_every_wend" =>					"W każdy weekend",
	"label_new_alarm" =>					"Utwórz nowy Alarm...",
	"label_delete_alarm" =>					"Usuń ten Alarm",
	"config_hidesearcher" =>				"Ukryj panel wyszukiwania",
	"label_refreshinprogress" =>			"Podcasty są już odświeżane. Spróbuj ponownie później",
	"button_addtoplaylist" =>				"Dodaj do zapisanej listy odtwarzania",
	"config_snapcast" =>					"Snapcast",
	"config_snapcast_server" =>				"Snapcast Serwer",
	"config_snapcast_port" =>				"TCP Port",
	"config_snapcast_http" =>				"HTTP Port",
	"snapcast_notthere" =>					"Nie można nawiązać połączenia z serwerem Snapcast",
	"snapcast_group" =>						"Grupa ",
	"snapcast_changegroup" =>				"Zmień grupę",
	"snapcast_latency" =>					"Opóźnienie ",
	"snapcast_setlatency" =>				"Ustaw opóźnienie",
	"snapcast_notconnected" =>				"(Nie połączone)",
	"label_lastfm_mix_7day" =>				"Last.FM Codzienny Mix",
	"label_lastfm_mix_1month" =>			"Last.FM Miesięczny Mix",
	"label_lastfm_mix_12month" =>			"Last.FM Roczny Mix",
	"label_lastfm_mix_overall" =>			"Last.FM Mix przez cały czas",
	"label_lastfm_dip_7day" =>				"Last.FM poleca",
	"label_lastfm_dip_1month" =>			"Last.FM Lucky Dip",
	"label_lastfm_dip_12month" =>			"Last.FM Podsumowanie roku",
	"label_lastfm_dip_overall" =>			"Last.FM Nostalgiczna Podróż",
	"config_alarm_stopafter" =>				"Zatrzymaj po (minuty)",
	"label_move_to_audiobooks" =>			"Przenieś do Poezji mówionej",
	"label_move_to_collection" =>			"Przenieś się do kolekcji muzyki",
	"label_removealbum" =>					"Usuń album z kolekcji",
	"label_subbed_podcasts" =>				"Subskrybowane podcasty",
	"podcast_tooltip_unlistened" =>			"Oznacz jako nieodsłuchane",
	"label_addtoqueue" =>					"Dodaj do kolejki odtwarzania",
	"label_resetresume" =>					"Zresetuj pozycję wznowienia",
	"label_sameascollection" =>				"Tak samo jak kolekcja",
	"label_duration_seconds" =>				"Czas trwania (sekundy)",
	"label_year" =>							"Rok",
	"label_is" =>							"jest",
	"label_is_not" =>						"nie jest",
	"label_contains" =>						"zawiera",
	"label_does_not_contain" =>				"nie zawiera",
	"label_exists" =>						"istnieje",
	"label_lessthan" =>						"jest mniejsze niż",
	"label_equals" =>						"jest równy",
	"label_greaterthan" =>					"jest większy niż",
	"label_any_rule" =>						"Utwory muszą spełniać co najmniej jedną regułę",
	"label_all_rules" =>					"Utwory muszą być zgodne ze wszystkimi zasadami",
	"label_choose_one" =>					"Wybierz jedną opcję...",
	"error_norules" =>						"Musisz stworzyć pewne zasady",
	"label_ruleoptions" =>					"Opcje reguł",
	"label_genres" =>						"Gatunki",
	"label_createcustom" =>					"Utwórz własną stację radiową",
	"label_edit" =>							"Edytuj",
	"label_dayssince" =>					"Dni od ostatniego odtwarzania",
	"label_disc" =>							"Numer dysku",
	"label_tracktitle" =>					"Tytuł utworu",
	"label_albumtitle" =>					"Tytuł albumu",
	"label_tracknumber" =>					"Numer utworu",
	"config_use_original_releasedate" =>	"Użyj oryginalnej daty premiery dla albumu, jeśli jest dostępna",
	"label_cantataimporter" =>				"Import ocen z prog. Cantata",
	"podcast_writetags" =>					"Zapisz Tagi/znaczniki ID3 do pobranych plików",
	"label_youtubedl" =>					"Pobierz dźwięk",
	"label_youtubedl_all" =>				"Pobierz wszystkie utwory z YouTube",
	"error_playergone" =>					"Odtwarzacz '%s' przestał odpowiadać!",
	"label_collinfo" =>						"Informacje o kolekcji",
	"label_incoll" =>						"Ten utwór jest już w kolekcji muzyki",
	"label_notincoll" =>					"Ten utwór nie znajduje się w kolekcji muzycznej. Kliknij, aby go dodać",
	"label_image_search" =>					'Aby korzystać z wyszukiwarki Bing, potrzebny jest klucz API wyszukiwarki obrazów Bing. Przeczytaj dokumentację.',
	"config_hidemastervolume" =>			'Użyj Snapcast jako głównej metody regulacji głośności',
	"setup_mopidy_scan" =>					'Zezwól RompR na uruchomienie lokalnego skanowania Mopidy podczas tworzenia kolekcji muzycznej',
	"setup_mopidy_scan_title" =>			'Mopidy specjalne opcje',
	"label_upnext" =>						'Następne',
	// "config_consumeworkaround" =>			'Work Around Mopidy Consume Bug (Read the Docs First)',
	// "warn_consumearound" =>					'Please DISABLE consume before enabling this option',
	// "msg_consumearound" =>					'Read the Docs about this option. You must be running romonitor for it to work',
	"podcast_display_nud" =>				'Nowe, Pobrane, & Nieodsłuchane',
	"label_usetrackimages" =>				'Przeskanuj każdy utwór w poszukiwaniu obrazu',
	"label_unusetrackimages" =>				'Nie skanuj każdego utworu w poszukiwaniu obrazu',
	"config_audiobook_tags" =>				'Ustaw/zaznacz utwór jako Poezja mówiona podczas dodawania tagów',
	"label_random_order" => 				'Losowa kolejność',
	"label_remove_all" => 					'Usuń wszystkie',
	"manage_bgs" =>							'Zarządzaj obrazami tła',
	"label_bg_global" =>					'Używaj we wszystkich przeglądarkach',
	"label_bg_only" =>						'Tylko dla tej przeglądarki',
	"label_playfromhere" =>					'Graj stąd',
	"config_browserid" =>					'ID przeglądarki',
	"button_clearwishlist" =>				'Wyczyść listę życzeń',
	"label_mfyc" =>							'Muzyka z Twojej kolekcji',
	"label_mfsp" =>							'Muzyka od Spotify',
	"label_mfe" =>							'Muzyka od Everywhere',
	"label_playqueue" =>					'Kolejka odtwarzania',
	"label_numplays" =>						'%s Odtwarza',
	"button_bookmarks" =>					'Dodaj zakładkę',
	"label_remcur" =>						'Usuń bieżący obraz',
	"button_nextbg" => 						'Następny obraz tła',
	"button_delbg" => 						'Usuń bieżący obraz tła',
	"label_name" =>							'Nazwa',
	"play_even_if_playing" =>				'Nawet jeśli gra inny',
	"setup_mpd_special"	=>					'MPD Specjalne opcje',
	"label_ui_defaults" =>					'Domyślne',
	"button_save_defaults" =>				'Zapisz jako domyślne dla wszystkich przeglądarek',
	"label_recommenddesc" =>				'Stacja radiowa z rekomendacjami opartymi na tym, czego słuchasz. Tworzona przez %s',
	"label_rmixdesc" =>						'Stacja radiowa z muzyką i artystami których kochasz. Tworzona przez %s',
	"config_stupid_round_corners" =>		'Wypełnienie u dołu ekranu (pomocna w przypadku telefonów z zaokrąglonymi rogami lub elementami sterującymi, które przeszkadzają)',
	"config_clearfirst" =>					'Przed rozpoczęciem opróżnij kolejkę odtwarzania',
	"label_classicalrules" =>				'Zasady sortowania muzyki klasycznej',
	"config_classicalrules" =>				'Użyj różnych zasad do sortowania muzyki klasycznej',
	"config_sortbyartist" =>				"Użyj wykonawcy do posortowania kolekcji",
	"config_sortbycomposer" =>				"Użyj kompozytora do posortowania kolekcji",
	"label_classicalgenre" =>				"Wykryj muzykę klasyczną używając gatunku(ów)",
	"label_classicalfolder" =>				"Wykryj muzykę klasyczną przez ścieżkę do folderu",
	"label_showallresults" =>				"Pokaż wszystkie utwory",
	"label_bythisartist" =>					"Przez tego artystę z Twojej kolekcji",
	"label_generic_error" =>				"Coś poszło nie tak",
	"label_genrebyartist" =>				"Gatunek (Artysty)",
	"label_ratingbyartist" =>				"Ocena (Artysty)",
	"label_tagbyartist" =>					"Tag (Artysty)",
	"label_playtaggedwith" =>				'Odtwarzaj tagowane utwory "%s*',
	"config_headerbar" =>					'Pozycja paska ikony'

	// ----------------------------------------------------
	// Proobaly Unused
	// ----------------------------------------------------
	//"label_smartsetup" =>					"Preparing. Please Wait A Moment....",

]);

?>
