<?php

language::add_translations([

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Музыкальная Коллекция",
	"button_file_browser" =>				"Файл Браузер",
	"button_internet_radio" =>				"Интернет Радио Станции",
	"button_albumart" =>					"Album Art Менеджер",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Панель Переключить источники",
	"button_back" =>						"Предыдущая",
	"button_history" =>						"История",
	"button_forward" =>						"Следующая",
	"button_toggleplaylist" =>				"Переключить плейлист",

	// Tooltips for playlist buttons
	"button_alarm" =>						"Будильник",
	"button_prefs" =>						"RompЯ Настройки",
	"button_clearplaylist" =>				"Очистить плейлист",
	"button_loadplaylist" =>				"Загрузить сохраненный плейлист",
	"button_saveplaylist" =>				"Сохранить плейлист",

	// Tooltips for playback controls
	"button_previous" =>					"Предыдущий трек",
	"button_play" =>						"Пуск/Пауза",
	"button_stop" =>						"Стоп",
	"button_stopafter" =>					"Стоп После текущей дорожки",
	"button_next" =>						"Следующий трек",
	"button_love" =>						"Любимый трек",
	"button_volume" =>						"Перетащите, чтобы изменить громкость",

	// Configuration menu entries
	"config_theme" =>						"ТЕМА",
	"config_hidealbumlist" =>				"Скрыть коллекцию музыки",
	"config_hidefileslist" =>				"Скрыть список файлов",
	"config_hideradio" =>					"Скрыть радиостанции",
	"config_hidepodcasts" =>				"Скрыть подкасты",
	"config_hideplaylistslist" =>			"Скрыть Сохранённый Плейлист",
	"config_hidepluginplaylistslist" =>		"Скрыть персональное радио",
	"config_hidebrowser" =>					"Скрыть Панель Информации",
	"config_lastfmlang" =>					"Язык для Last.FM и Wikipedia",
	"config_lastfmdefault" =>				"Язык по умолчанию (Английский)",
	"config_lastfminterface" =>				"Язык интерфейса RompЯ",
	"config_lastfmbrowser" =>				"Язык по умолчанию для браузера",
	"config_autoscroll" =>					"Автопрокрутка списка воспроизведения на текущий трек",
	"config_autocovers" =>					"Автоматическая загрузка обложек",
	"config_musicfolders" =>				"Чтобы использовать art из своих музыкальных папок или получить текст из ваших файлов, введите путь к своей музыке в этом поле:",
	"config_crossfade" =>					"Продолжительность Crossfade (секунд)",
	"config_doubleclick" =>					"Дважды щелкните, чтобы добавить, нажмите, чтобы выбрать",
	"config_singleclick" =>					"Нажмите, чтобы добавить, нет выбора",
	"config_sortbydate" =>					"Сортировка альбомов по дате",
	"config_notvabydate" =>					"Don't Apply Date Sorting to 'Various Artists'",
	"config_updateonstart" =>				"Обновлять музыкальную коллекцию при Старте",
	"config_updatenow" =>					"Обновить коллекцию музыки сейчас",
	"config_rescan" =>						"Пересканировать всю Local Music",
	"config_editshortcuts" =>				"Редактирование сочетаний клавиш...",
	"config_audiooutputs" =>				"Аудио Выходы",
	"config_lastfmusername" =>				"Last.FM Пользователь",
	"config_loginbutton" =>					"Логин",
	"config_scrobbling" =>					"Scrobble треки в Last.FM",
	"config_autocorrect" =>					"Используйте Last.FM для автоматического исправления имен исполнителей и т.д.",
	"config_tagloved" =>					"Tag Loved Tracks With:",
	"config_fontsize" =>					"ШРИФТ",
	"config_fontname" =>					"РАЗМЕР",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Сохранить",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Искать Музыку",
	"label_yourradio" =>					"Твои Радио Станции",
	"label_podcasts" =>						"Подкасты",
	"label_somafm" =>						"Soma FM",
	"label_emptyinfo" =>					"Это информационная панель. Интересные вещи появятся здесь, когда играете какую-нибудь музыку",
	"button_playlistcontrols" =>			"Управление Плейлистом",
	"button_random" =>						"ПЕРЕМЕШАТЬ",
	"button_crossfade" =>					"CROSSFADE",
	"button_repeat" =>						"ПОВТОРЯТЬ",
	"button_consume" =>						"ПОГЛОЩАТЬ",
	"label_yes" =>							"Да",
	"label_no" =>							"Нет",
	"label_updating" =>						"Обновление музыкальной коллекции",
	"label_update_error" =>					"Не удалось создать музыкальную коллекцию.",
	"label_playlisterror" =>				"Что-то пошло не так, как получить плейлист!",
	"button_OK" =>							"Принять",
	"button_cancel" =>						"Отменить",
	"error_playlistname" =>					"Имя плейлиста не может содержать косые черты",
	"label_savedpl" =>						"Список воспроизведения сохранен как %s",

	// Search Forms
	"label_searchfor" =>					"Искать",
	"label_searching" =>					"Поиск...",
	"label_searchresults" =>				"Результаты Поиска",

	// General multipurpose labels
	"label_tracks" =>						"треки",
	"label_albums" =>						"альбомы",
	"label_artists" =>						"артисты",
	"label_track" =>						"Трек",
	"label_album" =>						"Альбом",
	"label_artist" =>						"Артист",
	"label_anything" =>						"Что угодно",
	"label_genre" =>						"Жанр",
	"label_composer" =>						"Композитор",
	"label_performer" =>					"Исполнитель",
	"label_rating" =>						"Рейтинг",
	"label_tag" =>							"Тег",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"Там была ошибка. Обновите страницу и повторите попытку.",
	"label_days" =>							"дней",
	"label_noalbums" =>						"No Individual Albums Returned By Search",
	"label_duration" =>						"Длительность",
	"label_playererror" =>					"Ошибка плеера",
	"button_playradio" =>					"Пуск",

	// Playlist and Now Playing
	"label_notforradio" =>					"Не поддерживается для радиопотоков",
	"label_incoming" =>						"Входящие...",
	"label_addingtracks" =>					"Треки в очереди",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"от",
	"label_on" =>							"на",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"из",

	// Podcasts
	"podcast_entrybox" =>					"Введите URL-адрес RSS-канала подкаста в этом поле или перетащите его значок сюда",
	// Podcast tooltips
	"podcast_delete" =>						"Удалить этот подкаст",
	"podcast_configure" =>					"Настроить этот подкаст",
	"podcast_refresh" =>					"Обновить этот подкаст",
	"podcast_download_all" =>				"Скачать все эпизоды этого подкаста",
	"podcast_mark_all" =>					"Отметить все эпизоды как прослушанные",
	"podcast_undelete" =>					"Восстановить удаленные эпизоды",
	"podcast_removedownloaded" =>			"Удаление загруженных файлов",
	// Podcast display options
	"podcast_display" =>					"Показывать",
	"podcast_display_all" =>				"Все",
	"podcast_display_onlynew" =>			"Только новые",
	"podcast_display_unlistened" =>			"Новые и незарегистрированные",
	"podcast_display_downloadnew" =>		"Новые и Скачаные",
	"podcast_display_downloaded" =>			"Только скачаные",
	// Podcast refresh options
	"podcast_refresh" =>					"Обновлять",
	"podcast_refresh_never" =>				"Вручную",
	"podcast_refresh_hourly" =>				"Ежечасно",
	"podcast_refresh_daily" =>				"Ежедневно",
	"podcast_refresh_weekly" =>				"Еженедельно",
	"podcast_refresh_monthly" =>			"Ежемесячно",
	// Podcast auto expire
	"podcast_expire" =>						"Хранить эпизоды за",
	"podcast_expire_tooltip" =>				"Любые эпизоды старше этого значения будут удалены из списка. Изменения этого параметра вступят в силу при следующем обновлении подкаста",
	"podcast_expire_never" =>				"Когда-либо",
	"podcast_expire_week" =>				"Одну неделю",
	"podcast_expire_2week" =>				"Две недели",
	"podcast_expire_month" =>				"Один месяц",
	"podcast_expire_2month" =>				"Два месяца",
	"podcast_expire_6month" =>				"Шесть месяцев",
	"podcast_expire_year" =>				"Год",
	// Podcast number to keep
	"podcast_keep" =>						"Сохранять",
	"podcast_keep_tooltip" =>				"В этом списке будет показано только много эпизодов. Изменения этого параметра вступят в силу при следующем обновлении подкаста",
	"podcast_keep_0" =>						"Неограниченно",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Хранить все загруженные эпизоды",
	"podcast_kd_tooltip" =>					"Включите эту опцию, чтобы сохранить все загруженные эпизоды. Вышеуказанные два варианта будут применяться только к эпизодам, которые не были загружены",
	"podcast_tooltip_new" =>				"Это новый эпизод",
	"podcast_tooltip_notnew" =>				"Этот эпизод не новый, но его не слушали",
	"podcast_tooltip_downloaded" =>			"Этот эпизод был загружен",
	"podcast_tooltip_download" =>			"Загрузите этот эпизод на свой компьютер",
	"podcast_tooltip_mark" =>				"Отметить как прослушанный",
	"podcast_tooltip_delepisode" =>			"Удалить этот эпизод",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Пожалуйста, подумайте о поддержке Soma.FM, если вам нравятся эти станции",

	// Your radio stations
	"label_radioinput" =>					"Введите URL-адрес интернет-станции",

	//Album Art Manager
	"albumart_title" =>						"Обложки альбомов",
	"albumart_getmissing" =>				"Получить пропущенные обложки",
	"albumart_showall" =>					"Показать все обложки",
	"albumart_instructions" =>				"Щелкните обложку, чтобы изменить ее, или перетащите изображение с жесткого диска или другого окна браузера.",
	"albumart_onlyempty" =>					"Показать только альбомы без обложек",
	"albumart_allartists" =>				"Все артисты",
	"albumart_googlesearch" =>				"Bing Поиск",
	"albumart_local" =>						"Локальные изображения",
	"albumart_upload" =>					"Файл загружен",
	"albumart_uploadbutton" =>				"Загрузить",
	"albumart_newtab" =>					"Поиск в Google в новой вкладке",
	"albumart_dragdrop" =>					"Вы можете перетаскивать изображения с вашего жесткого диска или другого окна браузера непосредственно на изображение (в большинстве браузеров)",
	"albumart_showmore" =>					"Показать больше результатов",
	"albumart_googleproblem" =>				"Была проблема. Bing сказал",
	"albumart_getthese" =>					"Получить эти обложки",
	"albumart_nocovercount" =>				"альбомы без обложки",
	"albumart_getting" =>					"Получение",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr не смог подключиться к серверу mpd или mopidy",
	"setup_connecterror" =>					"При общении с вашим сервером в mpd или mopidy произошла ошибка: ",
	"setup_request" =>						"Вы запросили страницу настройки",
	"setup_addressnote" =>					"Примечание: localhost в этом контексте означает компьютер, на котором запущен сервер Apache",
	"setup_port" =>							"Порт",
	"setup_advanced" =>						"Расширенные опции",
	"setup_password" =>						"Пароль",
	"setup_unixsocket" =>					"UNIX-domain сокет",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Войти в Last.FM",
	"lastfm_login1" =>						"Нажмите кнопку ниже, чтобы открыть сайт Last.FM на новой вкладке. Введите данные для входа в Last.FM, если необходимо, затем предоставите RompЯ разрешение на доступ к вашей учетной записи",
	"lastfm_login2" =>						"Вы можете закрыть новую вкладку, когда закончите, но не закрывайте это диалоговое окно!",
	"lastfm_loginbutton" =>					"Нажмите здесь чтоб войти",
	"lastfm_login3" =>						"После того, как вы вошли в Last.FM, нажмите кнопку «ОК» ниже, чтобы завершить процесс",
	"lastfm_loginfailed" =>					"Не удалось войти в Last.FM",
	"label_loved" =>						"Любимый",
	"label_lovefailed" =>					"Failed To Make Love",
	"label_unloved" =>						"Unloved",
	"label_unlovefailed" =>					"Failed To Remove Love",
	"label_scrobblefailed" =>				"Failed to scrobble",

	// Info Panel
	"info_gettinginfo" =>					"Получение информации...",
	"info_newtab" =>						"Просмотреть в новой вкладке",

	// File Info panel
	"button_fileinfo" =>					"Панель информации (информация о файле)",
	"info_file" =>							"Файл:",
	"info_from_beets" =>					"(from beets server)",
	"info_format" =>						"Формат:",
	"info_bitrate" =>						"Битрейт:",
	"info_samplerate" =>					"Частота Дискретизации:",
	"info_mono" =>							"Моно",
	"info_stereo" =>						"Стерео",
	"info_channels" =>						"Каналы",
	"info_date" =>							"Дата:",
	"info_genre" =>							"Жанры:",
	"info_performers" =>					"Исполнитель:",
	"info_composers" =>						"Композитор:",
	"info_comment" =>						"Коментарий:",
	"info_label" =>							"Метка:",
	"info_disctitle" =>						"Название диска:",
	"info_encoder" =>						"Энкодер:",
	"info_year" =>							"Год:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Панель информации (Last.FM)",
	"label_notrackinfo" =>					"Не удалось найти информацию об этом треке",
	"label_noalbuminfo" =>					"Не удалось найти информацию об этом альбоме",
	"label_noartistinfo" =>					"Не удалось найти информацию об этом артисте",
	"lastfm_listeners" =>					"Слушателей:",
	"lastfm_plays" =>						"Прослушано:",
	"lastfm_yourplays" =>					"Вами прослушано:",
	"lastfm_toptags" =>						"ТОП-ТЕГИ:",
	"lastfm_addtags" =>						"ДОБАВИТЬ ТЕГИ",
	"lastfm_addtagslabel" =>				"Добавить теги, разделяя запятой",
	"button_add" =>							"ДОБАВИТЬ",
	"lastfm_yourtags" =>					"ВАШИ ТЕГИ:",
	"lastfm_simar" =>						"Похожие исполнители",
	"lastfm_removetag" =>					"Убрать метку",
	"lastfm_releasedate" =>					"Дата выпуска",
	"lastfm_viewtrack" =>					"Посмотреть дорожку на Last.FM",
	"lastfm_tagerror" =>					"Failed to modify tags",
	"lastfm_loved" =>						"Любимый",
	"lastfm_lovethis" =>					"Love This Track",
	"lastfm_unlove" =>						"Unlove This Track",
	"lastfm_notfound" =>					"%s Не найдено",

	// Lyrics info panel
	"button_lyrics" =>						"Панель информации (Текст песни)",
	"lyrics_lyrics" =>						"Текст песни",
	"lyrics_nonefound" =>					"Никаких текстов не найдено",
	"lyrics_info" =>						"Чтобы использовать средство просмотра текстов, вам необходимо убедиться, что ваши локальные файлы отмечены лирикой",
	"lyrics_nopath" =>						"Чтобы использовать средство просмотра текстов, вам необходимо убедиться, что ваши локальные файлы отмечены лирикой и задайте путь музыки в настройках",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"ГОД",
	"title_title" =>						"НАЗВАНИЕ",
	"title_type" =>							"ТИП",
	"title_label" =>						"МЕТКА",
	"label_pages" =>						"СТРАНИЦЫ",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"КОМПАНИИ",
	"discogs_personnel" =>					"ПЕРСОНАЛИИ",
	"discogs_videos" =>						"ВИДЕО",
	"discogs_styles" =>						"СТИЛИ",
	"discogs_genres" =>						"ЖАНРЫ",
	"discogs_tracklisting" =>				"ОТСЛЕЖИВАНИЕ",
	"discogs_realname" =>					"НАСТОЯЩЕЕ ИМЯ:",
	"discogs_aliases" =>					"ПСЕВДОНИМ:",
	"discogs_alsoknown" =>					"ТАКЖЕ ИЗВЕСТЕН КАК:",
	"discogs_external" =>					"ВНЕШНИЕ ССЫЛКИ",
	"discogs_bandmembers" =>				"УЧАСТНИКИ ГРУППЫ",
	"discogs_memberof" =>					"ЧЛЕН ГРУППЫ",
	"discogs_discography" =>				"%s ДИСКОГРАФИЯ",

	// Discogs info panel
	"button_discogs" =>						"Панель информации (Discogs)",
	"discogs_error" =>						"Discogs ничего не обнаружил",
	"discogs_nonsense" =>					"Не удалось получить разумный ответ от Discogs",
	"discogs_noalbum" =>					"Не удалось найти этот альбом на Discogs",
	"discogs_notrack" =>					"Не удалось найти этот трек в Discogs",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Панель информации (Musicbrainz)",
	"musicbrainz_error" =>					"Не получил ответа от MusicBrainz",
	"musicbrainz_contacterror" =>			"Произошла ошибка, связанная с Musicbrainz",
	"musicbrainz_noartist" =>				"Не удалось найти этого исполнителя на Musicbrainz",
	"musicbrainz_noalbum" =>				"Не удалось найти этот альбом на Musicbrainz",
	"musicbrainz_notrack" =>				"Не удалось найти этот трек на Musicbrainz",
	"musicbrainz_noinfo" =>					"Не удалось получить информацию от Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Present",
	"musicbrainz_origin" =>					"ORIGIN",
	"musicbrainz_active" =>					"ACTIVE",
	"musicbrainz_rating" =>					"РЕЙТИНГ",
	"musicbrainz_notes" =>					"ЗАМЕТКИ",
	"musicbrainz_tags" =>					"ТЕГИ",
	"musicbrainz_externaldiscography" =>		"Дискография (%s)",
	"musicbrainz_officalhomepage" =>		"Официальная страница (%s)",
	"musicbrainz_fansite" =>				"Фан Сайт (%s)",
	"musicbrainz_lyrics" =>					"Текст песни (%s)",
	"musicbrainz_social" =>					"Социальные сети",
	"musicbrainz_microblog" =>				"Микроблог",
	"musicbrainz_review" =>					"Обзор (%s)",
	"musicbrainz_novotes" =>				"(Нет голосов)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 из %s голосов",
	"musicbrainz_appears" =>				"ЭТОТ ТРЕК РАЗМЕЩЁН",
	"musicbrainz_credits" =>				"CREDITS",
	"musicbrainz_status" =>					"СОСТОЯНИЕ",
	"musicbrainz_date" =>					"ДАТА",
	"musicbrainz_country" =>				"СТРАНА",
	"musicbrainz_disc" =>					"ДИСК",

	// SoundCloud info panel
	"button_soundcloud" =>					"Панель информации (SoundCloud)",
	"soundcloud_trackinfo" =>				"Информация о треке",
	"soundcloud_plays" =>					"Играть",
	"soundcloud_downloads" =>				"Загрузки",
	"soundcloud_faves" =>					"Faves",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"Состояние",
	"soundcloud_license" =>					"Лицензия",
	"soundcloud_buy" =>						"Купить трек",
	"soundcloud_view" =>					"Просмотр в SoundCloud",
	"soundcloud_user" =>					"Пользователь SoundCloud",
	"soundcloud_fullname" =>				"Полное имя",
	"soundcloud_Country" =>					"Страна",
	"soundcloud_city" =>					"Город",
	"soundcloud_website" =>					"Посетите вебсайт",
	"soundcloud_not" =>						"Эта панель будет отображать только информацию о музыке из SoundCloud",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Панель информации (Wikipedia)",
	"wiki_nothing" =>						"Не получил ничего от Википедии",
	"wiki_fail" =>							"Википедия не могла найти ничего, что связано с '%s'",
	"wiki_suggest" =>						"Wikipedia не удалось найти ни одной страницы '%s'",
	"wiki_suggest2" =>						"Вот некоторые предложения, которые он придумал",

	// Keybindings editor
	"title_keybindings" =>					"Горячие клавиши",
	"button_volup" =>						"Прибавить звук",
	"button_voldown" =>						"Убавить звук",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"звёзд",
	"star" =>								"звезда",
	"label_tags" =>							"Теги",
	"label_wishlist" =>						"Список пожеланий",
	"label_viewwishlist" =>					"Просмотр Список пожеланий",
	"label_addtow" =>						"Добавлен Список пожеланий",
	"config_synctags" =>					"Keep Tags in Sync With Last.FM",
	"config_loveis" =>						"Last.FM Love Means",
	"playlist_xstar" =>						"%s или больше звезд",
	"button_about" =>						"О RompЯ",
	"label_notfound" =>						"Трек не найден",
	// Eg + 3 more

	//New in 0.52
	"config_alarm_ramp" =>					"Fade In",

	// New in 0.60
	"spotify_error" =>						"Нет ответа от Spotify",
	"spotify_noinfo" =>						"Не удалось получить информацию от Spotify",
	"button_infospotify" =>					"Панель информации (Spotify)",
	"config_icontheme" =>					"ИКОНКИ",
	"label_radio" =>						"Радио",
	"label_pop" =>							"Популярности",
	"label_albumsby" =>						"Альбомы этого исполнителя",
	"label_singleartistradio" =>			"Треки этого исполнителя",
	"label_mostplayed" =>					"Избранные треки",
	"label_neverplayed" =>					"Не прослушанные треки",
	"label_radio_fartist" =>				"Любимые артисты",
	"label_pluginplaylists" =>				"Персонализированное радио",
	"label_recentlyadded_random" =>			"Недавно добавленные треки (Случайно)",
	"label_recentlyadded_byalbum" =>		"Недавно добавленные альбомы",
	"setup_mpd" =>							"MPD/Mopidy Настройки",
	"settings_appearance" =>				"Appearance",
	"settings_panels" =>					"Панели",
	"settings_language" =>					"Язык",
	"settings_interface" =>					"Интерфейс",
	"label_charts" =>						"Топ 40",
	"button_subscribe" =>					"Подписывайся",
	"config_sortbycomposer" =>				"Использовать Композитора при сортировки Исполнителей",
	"config_composergenre" =>				" .. только если Жанр:",
	"config_displaycomposer" =>				"Показывать Композитор/Исполнитель в текущей игре",
	"label_radio_mix" =>					"Любимые артисты и похожие исполнители",
	"label_gotnotracks" =>					"Не найдено ни одного трека",
	"config_artistfirst" =>					"Артисты в начале коллекции",
	"config_nosortprefixes" =>				"Игнорировать эти префиксы при сортировке артистов",
	"button_skipforward" =>					"Пропустить вперед",
	"button_skipbackward" =>				"Пропустить назад",
	"config_snoozetime" =>					"Отложить время (Минут)",
	"config_ramptime" =>					"Время затихания (Секунд)",
	"button_rateone" =>						"Оценка 1 Звезда",
	"button_ratetwo" =>						"Оценка 2 Звезды",
	"button_ratethree" =>					"Оценка 3 Звезды",
	"button_ratefour" =>					"Оценка 4 Звезды",
	"button_ratefive" =>					"Оценка 5 Звёзд",
	"button_updatecollection" =>			"Обновить музыкальную коллекцию",
	"label_favealbums" =>					"Любимые альбомы",
	"button_nextsource" =>					"Панель информации - Cycle Source",
	"button_infopanel" =>					"Панель информации",
	"config_coversize" =>					"РАЗМЕР ОБЛОЖКИ АЛЬБОМА",
	"podcast_sortmode" =>					"Порядок сортировки",
	"podcast_newestfirst" =>				"Сначала новые",
	"podcast_oldestfirst" =>				"Сначала старые",
	"podcast_hidedescriptions" =>			"Скрыть описания",

	// New in 0.64/0.65/0.70
	"label_metabackup" =>					"Резервное копирование метаданных",
	"button_backup" =>						"Создать резервную копию",
	"button_restore" =>						"Восстановить из резервной копии",
	"button_collectioncontrols" =>			"Настройки сортировки музыкальной коллекции",
	"button_createplaylist" =>				"СОЗДАТЬ ПЛЕЙЛИСТ",
	"label_renameplaylist" =>				"Переименовать Плейлист",
	"button_plugins" =>						"Дополнения",
	"label_filename" =>						"Имя файла",
	"label_resultscollection" =>			"Коллекция",
	"label_resultstree" =>					"Дерево каталогов",
	"label_displayresultsas" =>				"Показать результаты как:",
	"label_files" =>						"Файлы",
	"label_albumartist" =>					"Исполнитель Альбома",
	"config_collectionfolders" =>			"Создать коллекцию из:",
	"button_videos" =>						"Похожее видео",
	"label_allrandom" =>					"Все треки в случайном порядке",
	"config_background" =>					"ФОНОВОЕ ИЗОБРАЖЕНИЕ",
	"lastfm_error" =>						"Не удалось найти информацию на Last.FM",
	"config_skin" =>						"СКИН",

	// New in 0.71
	"label_albumsbyartist" =>				"Альбомы (по исполнителю)",
	"config_wheelspeed" =>					"Скорость прокрутки колесика мыши",

	"label_radio_recommend" =>				"Рекомендации, основанные на этом %s",
	"label_amendalbum" =>					"Изменить информацию об альбоме",

	//CHANGED in 0.60
	"config_country" =>						"СТРАНА (для Spotify)",
	"setup_labeladdresses" =>				"Если возникли проблемы с подключением, попробуйте использовать IP-адрес вместо «localhost»",
	"setup_ipaddress" =>					"Mopidy или mpd сервер",

	"config_cdplayermode" =>				"Режим CD Player (не записывает треки в очередь, запускает альбом с выбранного трека)",

	"label_recentlyplayed" =>				"Недавно прослушанные треки",
	"label_simar_radio" =>					"Артисты, похожие на",

	"label_tradsearch" =>					"Использовать традиционный поиск с несколькими терминами",

	"played_never" =>						"Этот трек никогда не слушали",
	"played_once" =>						"Этот трек был прослушан один раз",
	"played_twice" =>						"Этот трек был прослушан дважды",
	"played_n" =>							"Этот трек был прослушан в %s раз",
	"played_last" =>						"В последний раз %s",
	"added_on" =>							"Он был добавлен в сборник %s",
	"button_infoyou" =>						"The Discoverator",
	"discover_now" =>						"Отслеживание предложений на основе %s",
	"config_discovembobulate" =>			"Открывать Discoverator при Старте",
	"label_spotify_mix" =>					"Spotify Недельный Mix",
	"label_spotify_dj" =>					"Spotify Swim",
	"label_spottery_lottery" =>				"Spotify Сюрприз!",
	"label_dailymix" =>						"Your Daily Mix",
	"label_luckydip" =>						"Your Lucky Dip",
	"label_startshere" =>					"Ваше открытие начинается здесь",
	"label_getspotify" =>					"Получить Spotify, чтобы начать поиск",
	"because_liked" =>						"Вам нравится %s, так что вам может понравиться:",
	"because_listened" =>					"Похожий на %s:",
	"albumart_findsmall" =>					"Найти небольшие изображения",
	"button_sleep" =>						"Таймер Сна",
	"label_tuneinradio" =>					"Радиостанция TuneIn",
	"label_generalsettings" =>				"Общие настройки",
	"config_beetsserver" =>					"Расположение сервера Beets (ip.address:port)",
	"config_players" =>						"Плеер",
	"button_edit_players" =>				"Изменить Плеер",

	"label_play_all" =>						"Играть Всё",
	"label_last_played" =>					"Последний проигранный:",
	"label_station_website" =>				"Сайт станции",

	"label_play_whole_album" =>				"Воспроизвести весь альбом",
	"label_from_collection" =>				"Воспроизвести только треки из коллекции",
	"label_with_ratings" =>					"Воспроизвести только треки с рейтингами",
	"label_with_tags" =>					"Воспроизвести только треки с тегами",
	"label_with_tagandrat" =>				"Играть только треки с тегами и рейтингами",
	"label_with_tagorrat" =>				"Воспроизвести только треки с тегами или рейтингами",
	"config_google_credentials" =>			"Bing API Credentials",
	"config_read_the_docs" =>				"Пожалуйста, прочтите документацию",
	"label_dateadded" =>					"Дата Добавлена",
	"label_radiostation" =>					"Радио Станция",
	"label_opmlimporter" =>					"OPML Импортёр",
	"config_playerintitlebar" =>			"Паказывать имя плеера в Titlebar",
	"label_communityradio" =>				"Community Radio Browser",
	"label_volume" =>						"Громкость",
	"button_debuginfo" =>					"Отладочная информация",
	"config_podcast_defaults" =>			"Параметры по умолчанию для новых подкастов",
	"config_marknewasunlistened" =>			"Отметить новые эпизоды как незарегистрированные перед обновлением",
	"config_albumartinplaylist" =>			"Показать обложку альбома в текущем плейлисте",
	"label_resume" =>						"Продолжить",
	"label_sortby" =>						"Сортировать по",
	"label_then" =>							"Затем",
	"label_publisher" =>					"Издателью",
	"label_category" =>						"Категории",
	"label_new_episodes" =>					"Новым эпизодам",
	"label_unlistened_episodes" =>			"Незарегистрированные Эпизоды",
	"label_loading" =>						"Загружаю...",
	"label_choosefile" =>					"Выберите файл",
	"label_choosefiles" =>					"Выберите файл(ы)",
	"label_changevery" =>					"Изменить каждый",
	"label_albumstolistento" =>				"Альбомы для прослушивания",
	"no_albumtolistento" =>					"Можно добавить любой альбом Spotify в этот список из информационной панели, после чего вы сможете вернуться и проверить их на досуге.",
	"label_addedtolistenlater" =>			"Добавлено в альбомы, для прослушивания",
	"label_all_time" =>						"Вся коллекция",
	"label_today" =>						"Добавлено сегодня",
	"label_thisweek" =>						"Добавлено на этой неделе",
	"label_thismonth" =>					"Добавлено в этом месяце",
	"label_thisyear" =>						"Добавлено в этом году",
	"label_searchtrack" =>					"Поиск этого трека",
	"label_removefromwl" =>					"Удалить трек из списка пожеланий",
	"label_gethelp" =>						"Нажать для помощи",
	"label_podcastcontrols" =>				"Элементы поиска и сортировки подкастов",
	"label_closepanel" =>					"Закрыть панель",
	"label_hidepanel" =>					"Скрыть панель",
	"label_removefromplaylist" =>			"Удалить из списка воспроизведения",
	"label_addtolistenlater" =>				"Добавить в альбомы для прослушивания",
	"label_removefromlistenlater" =>		"Удалить из альбомов для прослушивания",
	"label_addtocollection" =>				"Добавить альбом в коллекцию музыки",
	"label_addtoradio" =>					"Добавить в свои радиостанции",
	"button_logout" =>						"Выйти",
	"label_transferplaylist" =>				"Перенестри плейлист в новый плеер?",
	"label_yes" =>							"Да",
	"label_no" =>							"Нет",
	"podcast_refresh_all" =>				"Обновить все подкасты",
	"label_global_controls" =>				"Глобальный контроль",
	"label_topleft" =>						"Сверху слева",
	"label_topright" =>						"Сверху справа",
	"label_bottomleft" =>					"Снизу слева",
	"label_bottomright" =>					"Снизу справа",
	"label_centre" =>						"По центру",

	// ----------------------------------------------------
	// Missing Translations
	// ----------------------------------------------------
	//"config_preferlocal" =>				"Prefer Local Music to Internet Sources",
	//"config_lastfm_playcounts" =>			"Use Last.FM Playcounts",
	//"config_sync_lastfm_playcounts" =>		"Synchronise Last.FM Playcounts At Start",
	//"label_lfm_playcountimporter" =>		"Last.FM Playcount Importer",
	//"label_mustlogintolfm" =>				"You must be logged in to Last.FM to use this feature",
	//"label_lfm_syncing" =>				"Syncing Last.FM Playcounts",
	//"label_lfm_nonew" =>					"No new tracks have been added to the Music Collection since the last import on %s",
	//"config_smart_chunksize" =>			"Number of upcoming tracks to display",
	//"warning_smart_debug" =>				"WARNING! Running Personal Radio with debugging enabled may crash your browser!",
	//"label_unplayabletracks" =>			"Unplayable Tracks",
	//"label_no_unplayable" =>				"There are no unplayable tracks in your Collection",
	//"label_removefromcol" =>				"Remove From Collection",
	//"label_audiobooks" =>					"Spoken Word",
	//"config_hideaudiobooks" =>			"Hide Spoken Word",
	//"config_audiobook_directory" =>		"Directory Containing Spoken Word Files",
	//"error_imageupload" =>				"Failed To Upload Image",
	//"error_toomanyimages" =>				"Too many images, or image file too big",
	//"error_sendingcommands" =>			"Failed Sending Commands To %s",
	//"error_cantdeleteplayer" =>			"You cannot delete the player you're currently using",
	//"error_duplicateplayer" =>			"You cannot have two players with the same name",
	//"error_backupfail" =>					"Failed to %s backup",
	//"error_nogenres" =>					"Please choose some Genres",
	//"error_collectionupdate" =>			"Music Collection Update Failed",
	//"error_nocol" =>						"Already Updating Collection!",
	//"error_dupkey" =>						"Key '%s' is already used by '%s'",
	//"error_dlpfail" =>					"Something went wrong checking the download progress!",
	//"error_refreshfail" =>				"Podcast Refresh Failed",
	//"error_trfailed" =>					"Failed to Transfer Playlist",
	//"error_trackexists" =>				"That track is already in the collection",
	//"error_nosearchnow" =>				"Cannot Search while updating collection",
	//"label_backupcreated" =>				"Backup Created",
	//"label_sleepon" =>					"Sleep Timer Enabled",
	//"label_addedtocol" =>					"Added track to Collection",
	//"label_addedtosw" =>					"Added track to Spoken Word",
	//"label_addedradio" =>					"Added To Your Radio Stations",
	//"label_updatedone" =>					"Music Collection Updated",
	//"label_addingalbum" =>				"Adding Album To Collection",
	//"error_truncated" =>					"Browser history has been truncated - artist cannot be displayed",
	//"error_noplayer" =>					"Could not get a response from the player!",
	//"label_preparing" =>					"Preparing. Please Wait While RompЯ Calculates...",
	//"label_scanningf" =>					"Scanning Folder %s",
	//"label_fremaining" =>					"%s folders remaining",
	//"label_scanningp" =>					"Scanning Playlist %s",
	//"importer_status" =>					"Done %s of %s. Elapsed %s, Remaining %s",
	//"label_playcount" =>					"Playcount",
	//"label_lfm_playcount" =>				"Last.FM Playcount",
	//"label_norecdata" =>					"Once RompЯ has gathered some data, it will show recommendations here. Play some music!",
	//"label_dailymixdesc" =>				"A playlist just for you, a mix of tracks you know and new music you might love. Powered by Last.FM %s",
	//"label_luckydipdesc" =>				"A radio station just for you, playing a wider range of music by artists you know and artists you don't yet love. Powered by Last.FM %s",
	//"label_goonlogin" =>					"Log in to Last.FM and start scrobbling. RompЯ can then delight you with new music you're going to love!",
	//"label_nospotify" =>					"Use Mopidy with a Youtube Music subscription, and start scrobbbling to Last.FM so RompЯ can delight you with new music you're going to love!",
	//"label_spotimixdesc" =>				"A radio station of suggestions based on your recent listening. Powered by RompЯ and Spotify",
	//"label_spotiswimdesc" =>				"Scanning the vastness of Spotify. Powered by RompЯ and Spotify",
	//"label_opmlexp" =>					"OPML Export",
	//"button_opmlexp" =>					"Export Podcasts As OPML",
	//"button_selectall" =>					"Select All",
	//"button_selectnone" =>				"Select None",
	//"button_import" =>					"Import Selected",
	//"label_onlyspotify" =>				"This panel is only applicable if your player can play Spotify",
	//"label_daylabels" =>					array("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),
	//"label_alarm_play_specific" =>		"Play This Item :",
	//"label_alarm_to_play" =>				"Drop Item Here",
	//"label_every_day" =>					"Every Day",
	//"label_every_wday" =>					"Every Weekday",
	//"label_every_wend" =>					"Every Weekend",
	//"label_new_alarm" =>					"Create New Alarm...",
	//"label_delete_alarm" =>				"Delete This Alarm",
	//"config_hidesearcher" =>				"Hide Search Panel",
	//"label_refreshinprogress" =>			"Podcasts are already being refreshed. Try again later",
	//"button_addtoplaylist" =>				"Add To Saved Playlist",
	//"config_snapcast" =>					"Snapcast",
	//"config_snapcast_server" =>			"Snapcast Server",
	//"config_snapcast_port" =>				"Port",
	//"snapcast_notthere" =>				"Could not contact Snapcast server",
	//"snapcast_group" =>					"Group ",
	//"snapcast_changegroup" =>				"Change Group",
	//"snapcast_latency" =>					"Latency ",
	//"snapcast_setlatency" =>				"Set Latency",
	//"snapcast_notconnected" =>			"(Not Connected)",
	//"label_lastfm_mix_7day" =>			"Last.FM Daily Mix",
	//"label_lastfm_mix_1month" =>			"Last.FM Monthly Mix",
	//"label_lastfm_mix_12month" =>			"Last.FM Yearly Mix",
	//"label_lastfm_mix_overall" =>			"Last.FM All Time Mix",
	//"label_lastfm_dip_7day" =>			"Last.FM Recommends",
	//"label_lastfm_dip_1month" =>			"Last.FM Lucky Dip",
	//"label_lastfm_dip_12month" =>			"Last.FM Review of the Year",
	//"label_lastfm_dip_overall" =>			"Last.FM Nostalgia Trip",
	//"config_alarm_stopafter" =>			"Stop After (mins)",
	//"label_move_to_audiobooks" =>			"Move To Spoken Word",
	//"label_move_to_collection" =>			"Move To Music Collection",
	//"label_removealbum" =>				"Remove Album From Collection",
	//"label_subbed_podcasts" =>			"Subscribed Podcasts",
	//"podcast_tooltip_unlistened" =>		"Mark as Unlistened",
	//"label_addtoqueue" =>					"Add to Play Queue",
	//"label_resetresume" =>				"Reset Resume Position",
	//"label_sameascollection" =>			"Same As Collection",
	//"label_duration_seconds" =>			"Duration (seconds)",
	//"label_year" =>						"Year",
	//"label_is" =>							"is",
	//"label_is_not" =>						"is not",
	//"label_contains" =>					"contains",
	//"label_does_not_contain" =>			"does not contain",
	//"label_exists" =>						"exists",
	//"label_lessthan" =>					"is less than",
	//"label_equals" =>						"is equal to",
	//"label_greaterthan" =>				"is greater than",
	//"label_any_rule" =>					"Tracks must match at least one rule",
	//"label_all_rules" =>					"Tracks must match all rules",
	//"label_choose_one" =>					"Choose One...",
	//"error_norules" =>					"You must create some rules",
	//"label_ruleoptions" =>				"Rule Options",
	//"label_genres" =>						"Genres",
	//"label_createcustom" =>				"Create Custom Radio Station",
	//"label_edit" =>						"Edit",
	//"label_dayssince" =>					"Days since Last Played",
	//"label_disc" =>						"Disc Number",
	//"label_tracktitle" =>					"Track Title",
	//"label_albumtitle" =>					"Album Title",
	//"label_tracknumber" =>				"Track Number",
	//"config_use_original_releasedate" =>		"Use Original Release Date for Album Date, if present",
	//"label_cantataimporter" =>			"Import Ratings from Cantata",
]);

?>
