<?php
// The first term here is the name that will appear in the drop-down list
// This has the form $langname['file_name without .php extension'] = "Display Name";
// Try to name your file as the two-letter language code so RompR can pick a suitable
// default language automatically.
$langname['ru'] = "Русский";
$languages['ru'] = array (
	// The Sources Chooser Button tooltips
	"button_local_music" => "Музыкальная Коллекция",
	"button_file_browser" => "Файл Браузер",
	"button_internet_radio" => "Интернет Радио Станции",
	"button_albumart" => "Album Art Менеджер",
	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" => "Панель Переключить источники",
	"button_back" => "Предидущая",
	"button_history" => "История",
	"button_forward" => "Следующая",
	"button_toggleplaylist" => "Переключить плейлист",
	// Tooltips for playlist buttons
	"button_alarm" => "Будильник",
	"button_prefs" => "RompЯ Настройки",
	"button_clearplaylist" => "Очистить плейлист",
	"button_loadplaylist" => "Загрузить сохраненный плейлист",
	"button_saveplaylist" => "Сохранить плейлист",
	// Tooltips for playback controls
	"button_previous" => "Предыдущий трек",
	"button_play" => "Пуск/Пауза",
	"button_stop" => "Стоп",
	"button_stopafter" => "Стоп После текущей дорожки",
	"button_next" => "Следующий трек",
	"button_love" => "Любимый трек",
	"button_ban" => "Запретить этот трек",
	"button_volume" => "Перетащите, чтобы изменить громкость",
	"button_closewindow" => "Закрыть окно",
	// Configuration menu entries
	"config_language" => "ЯЗЫК",
	"config_theme" => "ТЕМА",
	"config_hidealbumlist" => "Скрыть коллекцию музыки",
	"config_hidefileslist" => "Скрыть список файлов",
	"config_hideradio" => "Скрыть радиостанции",
	"config_hidepodcasts" => "Скрыть подкасты",
	"config_hideplaylistslist" => "Скрыть Сохранённый Плейлист",
	"config_hidepluginplaylistslist" => "Скрыть персональное радио",
	"config_hidebrowser" => "Скрыть Панель Информации",
	"config_fullbio" => "Получить полную биографию исполнителя с Last.FM",
	"config_lastfmlang" => "Язык для Last.FM и Wikipedia",
	"config_lastfmdefault" => "Язык по умолчанию (Английский)",
	"config_lastfminterface" => "Язык интерфейса RompЯ",
	"config_lastfmbrowser" => "Язык по умолчанию для браузера",
	"config_lastfmlanguser" => "Этот конкретный язык:",
	"config_langinfo" => "Last.FM и Wikipedia вернется на английский язык, если информация не будет найдена на вашем языке",
	"config_autoscroll" => "Автопрокрутка списка воспроизведения на текущий трек",
	"config_autocovers" => "Автоматическая загрузка обложек",
	"config_musicfolders" => "Чтобы использовать art из своих музыкальных папок или получить текст из ваших файлов, введите путь к своей музыке в этом поле:",
	"config_crossfade" => "Продолжительность Crossfade (секунд)",
	"config_clicklabel" => "Выбор музыки Нажмите Behaviour",
	"config_doubleclick" => "Дважды щелкните, чтобы добавить, нажмите, чтобы выбрать",
	"config_singleclick" => "Нажмите, чтобы добавить, нет выбора",
	"config_sortbydate" => "Сортировка альбомов по дате",
	"config_notvabydate" => "Don't Apply Date Sorting to 'Various Artists'",
	"config_updateonstart" => "Обновлять музыкальную коллекцию при Старте",
	"config_updatenow" => "Обновить коллекцию музыки сейчас",
	"config_rescan" => "Пересканировать всю Local Music",
	"config_editshortcuts" => "Редактирование сочетаний клавиш...",
	"config_audiooutputs" => "Аудио Выходы",
	"config_lastfmusername" => "Last.FM Пользователь",
	"config_loginbutton" => "Логин",
	"config_scrobbling" => "Scrobble tracks to Last.FM",
	"config_scrobblepercent" => "Percentage of track to play before scrobbling",
	"config_autocorrect" => "Use Last.FM to auto-correct artist names etc",
	"config_tagloved" => "Tag Loved Tracks With:",
	"config_fontsize" => "ШРИФТ",
	"config_fontname" => "РАЗМЕР",
	"config_alarm_on" => "Включить Будильник",
	"config_showartistbanners" => "Показать Баннеры Артистов",
	// Various buttons for the playlist dropdowns
	"button_imsure" => "Я уверен в этом",
	"button_save" => "Сохранить",
	// General Labels and buttons in the main layout
	"label_lastfm" => "Last.FM",
	"button_searchmusic" => "Искать Музыку",
	"label_yourradio" => "Твои Радио Станции",
	"label_podcasts" => "Подкасты",
	"label_somafm" => "Soma FM",
	"label_icecast" => "Icecast Радио",
	"label_emptyinfo" => "Это информационная панель. Интересные вещи появятся здесь, когда играете какую-нибудь музыку",
	"button_playlistcontrols" => "Управление Плейлистом",
	"button_random" => "ПЕРЕМЕШАТЬ",
	"button_crossfade" => "CROSSFADE",
	"button_repeat" => "ПОВТОРЯТЬ",
	"button_consume" => "ПОГЛОЩАТЬ",
	"label_yes" => "Да",
	"label_no" => "Нет",
	"label_updating" => "Обновление музыкальной коллекции",
	"label_update_error" => "Не удалось создать музыкальную коллекцию.",
	"label_notsupported" => "Операция не поддерживается!",
	"label_playlisterror" => "Что-то пошло не так, как получить плейлист!",
	"label_downloading" => "Загрузка...",
	"button_OK" => "Принять",
	"button_cancel" => "Отменить",
	"error_playlistname" => "Имя плейлиста не может содержать косые черты",
	"label_savedpl" => "Список воспроизведения сохранен как %s",
	"label_loadingstations" => "Загрузка станции...",
	// Search Forms
	"label_searchfor" => "Искать",
	"label_searching" => "Поиск...",
	"button_search" => "Поиск",
	"label_searchresults" => "Результаты Поиска",
	"label_multiterms" => "Несколько вариантов поиска можно использовать сразу",
	"label_limitsearch" => "Поиск конкретных бэкэндов",
	// General multipurpose labels
	"label_tracks" => "треки",
	"label_albums" => "альбомы",
	"label_artists" => "артисты",
	"label_track" => "Трек",
	"label_album" => "Альбом",
	"label_artist" => "Артист",
	"label_anything" => "Что угодно",
	"label_genre" => "Жанр",
	"label_composer" => "Композитор",
	"label_performer" => "Исполнитель",
	"label_rating" => "Рейтинг",
	"label_tag" => "Тег",
	"label_discogs" => "Discogs",
	"label_musicbrainz" => "Musicbrainz",
	"label_wikipedia" => "Wikipedia",
	"label_general_error" => "Там была ошибка. Обновите страницу и повторите попытку.",
	"label_days" => "дней",
	"label_hours" => "часов",
	"label_minutes" => "минут",
	"label_noalbums" => "No Individual Albums Returned By Search",
	"label_notracks" => "No Individual Tracks Returned By Search",
	"label_duration" => "Длительность",
	"label_playererror" => "Ошибка плеера",
	"label_tunefailed" => "Не удалось настроить радиостанцию",
	"label_noneighbours" => "Не нашли соседей",
	"label_nofreinds" => "У вас 0 друзей",
	"label_notags" => "Не найдено ни одного тега",
	"label_noartists" => "Не нашли лучших артистов",
	"mopidy_tooold" => "Ваша версия Mopidy слишком старая. Обновите версию %s или выше",
	"button_playradio" => "Пуск",
	// Playlist and Now Playing
	"label_waitingforstation" => "Ожидание информации о станции...",
	"label_notforradio" => "Не поддерживается для радиопотоков",
	"label_incoming" => "Входящие...",
	"label_addingtracks" => "Треки в очереди",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" => "от",
	"label_on" => "на",
	// Now playing - 1:45 of 6:50
	"label_of" => "из",
	// Podcasts
	"podcast_rss_error" => "Не удалось загрузить RSS-канал",
	"podcast_remove_error" => "Не удалось удалить подкаст",
	"podcast_general_error" => "Операция не удалась :(",
	"podcast_entrybox" => "Введите URL-адрес RSS-канала подкаста в этом поле или перетащите его значок сюда",
	// Podcast tooltips
	"podcast_delete" => "Удалить этот подкаст",
	"podcast_configure" => "Настроить этот подкаст",
	"podcast_refresh" => "Обновить этот подкаст",
	"podcast_download_all" => "Скачать все эпизоды этого подкаста",
	"podcast_mark_all" => "Отметить все эпизоды как прослушанные",
	"podcast_undelete" => "Восстановить удаленные эпизоды",
	"podcast_removedownloaded" => "Удаление загруженных файлов",
	// Podcast display options
	"podcast_display" => "Показывать",
	"podcast_display_all" => "Все",
	"podcast_display_onlynew" => "Только новые",
	"podcast_display_unlistened" => "Новые и незарегистрированные",
	"podcast_display_downloadnew" => "Новые и Скачаные",
	"podcast_display_downloaded" => "Только скачаные",
	// Podcast refresh options
	"podcast_refresh" => "Обновлять",
	"podcast_refresh_never" => "Вручную",
	"podcast_refresh_hourly" => "Ежечасно",
	"podcast_refresh_daily" => "Ежедневно",
	"podcast_refresh_weekly" => "Еженедельно",
	"podcast_refresh_monthly" => "Ежемесячно",
	// Podcast auto expire
	"podcast_expire" => "Хранить эпизоды за",
	"podcast_expire_tooltip" => "Любые эпизоды старше этого значения будут удалены из списка. Изменения этого параметра вступят в силу при следующем обновлении подкаста",
	"podcast_expire_never" => "Когда-либо",
	"podcast_expire_week" => "Одну неделю",
	"podcast_expire_2week" => "Две недели",
	"podcast_expire_month" => "Один месяц",
	"podcast_expire_2month" => "Два месяца",
	"podcast_expire_6month" => "Шесть месяцев",
	"podcast_expire_year" => "Год",
	// Podcast number to keep
	"podcast_keep" => "Сохранять",
	"podcast_keep_tooltip" => "В этом списке будет показано только много эпизодов. Изменения этого параметра вступят в силу при следующем обновлении подкаста",
	"podcast_keep_0" => "Неограниченно",
	// Podcast other options
	"podcast_keep_downloaded" => "Хранить все загруженные эпизоды",
	"podcast_kd_tooltip" => "Включите эту опцию, чтобы сохранить все загруженные эпизоды. Вышеуказанные два варианта будут применяться только к эпизодам, которые не были загружены",
	"podcast_auto_download" => "Автоматическая загрузка новых эпизодов",
	"podcast_tooltip_new" => "Это новый эпизод",
	"podcast_tooltip_notnew" => "Этот эпизод не новый, но его не слушали",
	"podcast_tooltip_downloaded" => "Этот эпизод был загружен",
	"podcast_tooltip_download" => "Загрузите этот эпизод на свой компьютер",
	"podcast_tooltip_mark" => "Отметить как прослушанный",
	"podcast_tooltip_delepisode" => "Удалить этот эпизод",
	"podcast_expired" => "Этот эпизод истек",
	// eg 2 days left to listen
	"podcast_timeleft" => "%s левый, чтобы слушать",
	// Soma FM Chooser Panel
	"label_soma" => "Soma.FM - это радиостанция, поддерживаемая без рекламы, из Сан-Франциско",
	"label_soma_beg" => "Пожалуйста, подумайте о поддержке Soma.FM, если вам нравятся эти станции",
	// Your radio stations
	"label_radioinput" => "Введите URL-адрес интернет-станции в этом поле или перетащите его кнопку воспроизведения сюда",
	//Album Art Manager
	"albumart_title" => "Обложки альбомов",
	"albumart_getmissing" => "Получить пропущенные обложки",
	"albumart_showall" => "Показать все обложки",
	"albumart_instructions" => "Щелкните обложку, чтобы изменить ее, или перетащите изображение с жесткого диска или другого окна браузера.",
	"albumart_onlyempty" => "Показать только альбомы без обложек",
	"albumart_allartists" => "Все артисты",
	"albumart_unused" => "Неиспользуемые изображения",
	"albumart_deleting" => "Удаление...",
	"albumart_error" => "Это не сработало",
	"albumart_googlesearch" => "Google Поиск",
	"albumart_local" => "Локальные изображения",
	"albumart_upload" => "Файл загружен",
	"albumart_uploadbutton" => "Загрузить",
	"albumart_newtab" => "Поиск в Google в новой вкладке",
	"albumart_dragdrop" => "Вы можете перетаскивать изображения с вашего жесткого диска или другого окна браузера непосредственно на изображение (в большинстве браузеров)",
	"albumart_showmore" => "Показать больше результатов",
	"albumart_googleproblem" => "Была проблема. Google сказал",
	"albumart_getthese" => "Получить эти обложки",
	"albumart_deletethese" => "Удалить эти обложки",
	"albumart_nocollection" => "Создайте свою музыкальную коллекцию, прежде чем пытаться загружать обложки",
	"albumart_nocovercount" => "альбомы без обложки",
	"albumart_getting" => "Получение",
	// Setup page (rompr/?setup)
	"setup_connectfail" => "Rompr could not connect to an mpd or mopidy server",
	"setup_connecterror" => "There was an error when communicating with your mpd or mopidy server : ",
	"setup_request" => "You requested the setup page",
	"setup_addressnote" => "Примечание: localhost в этом контексте означает компьютер, на котором запущен сервер Apache",
	"setup_port" => "Порт",
	"setup_advanced" => "Расширенные опции",
	"setup_leaveblank" => "Оставьте их пустыми, если не знаете, что они вам нужны",
	"setup_password" => "Пароль",
	"setup_unixsocket" => "UNIX-domain сокет",
	// Intro Window
	"intro_title" => "Информация об этой версии",
	"intro_welcome" => "Добро пожаловать в RompeR версия",
	"intro_viewingmobile" => "Вы просматриваете мобильную версию RompЯ. Чтобы просмотреть стандартную версию, перейдите к",
	"intro_viewmobile" => "Для просмотра мобильной версии перейдите к",
	"intro_basicmanual" => "Руководство RompR находится на:",
	"intro_forum" => "Форум находится в:",
	"intro_mopidy" => "ВАЖНАЯ информация для пользователей Mopidy",
	"intro_mopidywiki" => "Если вы используете Mopidy, пожалуйста, прочитайте Wiki",
	"intro_mopidyversion" => "Вы должны использовать Mopidy %s или выше",
	// Last.FM
	"lastfm_loginwindow" => "Войти в Last.FM",
	"lastfm_login1" => "Нажмите кнопку ниже, чтобы открыть сайт Last.FM на новой вкладке. Введите данные для входа в Last.FM, если необходимо, затем предоставите RompЯ разрешение на доступ к вашей учетной записи",
	"lastfm_login2" => "Вы можете закрыть новую вкладку, когда закончите, но не закрывайте это диалоговое окно!",
	"lastfm_loginbutton" => "Нажмите здесь чтоб войти",
	"lastfm_login3" => "После того, как вы вошли в Last.FM, нажмите кнопку «ОК» ниже, чтобы завершить процесс",
	"lastfm_loginfailed" => "Не удалось войти в Last.FM",
	"label_loved" => "Любимый",
	"label_lovefailed" => "Failed To Make Love",
	"label_unloved" => "Unloved",
	"label_unlovefailed" => "Failed To Remove Love",
	"label_banned" => "Banned",
	"label_banfailed" => "Failed To Ban",
	"label_scrobbled" => "Scrobbled",
	"label_scrobblefailed" => "Failed to scrobble",
	// Info Panel
	"info_gettinginfo" => "Получение информации...",
	"info_newtab" => "Просмотреть в новой вкладке",
	// File Info panel
	"button_fileinfo" => "Панель информации (информация о файле)",
	"info_file" => "Файл:",
	"info_from_beets" => "(from beets server)",
	"info_format" => "Формат:",
	"info_bitrate" => "Битрейт:",
	"info_samplerate" => "Частота Дискретизации:",
	"info_mono" => "Моно",
	"info_stereo" => "Стерео",
	"info_channels" => "Каналы",
	"info_date" => "Дата:",
	"info_genre" => "Жанры:",
	"info_performers" => "Исполнитель:",
	"info_composers" => "Композитор:",
	"info_comment" => "Коментарий:",
	"info_label" => "Метка:",
	"info_disctitle" => "Название диска:",
	"info_encoder" => "Энкодер:",
	"info_year" => "Год:",
	// Last.FM Info Panel
	"button_infolastfm" => "Панель информации (Last.FM)",
	"label_notrackinfo" => "Не удалось найти информацию об этом треке",
	"label_noalbuminfo" => "Не удалось найти информацию об этом альбоме",
	"label_noartistinfo" => "Не удалось найти информацию об этом артисте",
	"lastfm_listeners" => "Listeners:",
	"lastfm_plays" => "Прослушано:",
	"lastfm_yourplays" => "Вами прослушано:",
	"lastfm_toptags" => "ТОП-ТЕГИ:",
	"lastfm_readfullbio" => "Читать полную биографию",
	"lastfm_addtags" => "ДОБАВИТЬ ТЕГИ",
	"lastfm_addtagslabel" => "Добавить теги, разделяя запятой",
	"button_add" => "ДОБАВИТЬ",
	"lastfm_yourtags" => "ВАШИ ТЕГИ:",
	"lastfm_buyoncd" => "КУПИТЬ НА CD:",
	"lastfm_download" => "СКАЧАТЬ:",
	"lastfm_simar" => "Похожие исполнители",
	"lastfm_removetag" => "Убрать метку",
	"lastfm_buyalbum" => "КУПИТЬ ЭТОТ АЛЬБОМ",
	"lastfm_releasedate" => "Дата выпуска",
	"lastfm_viewtrack" => "Посмотреть дорожку на Last.FM",
	"lastfm_buytrack" => "КУПИТЬ ЭТОТ ТРЕК",
	"lastfm_tagerror" => "Failed to modify tags",
	"lastfm_loved" => "Loved",
	"lastfm_lovethis" => "Love This Track",
	"lastfm_unlove" => "Unlove This Track",
	"lastfm_notfound" => "%s Не найдено",
	"lastfm_nobio" => "Нет полной биографии",
	// Lyrics info panel
	"button_lyrics" => "Панель информации (Текст песни)",
	"lyrics_lyrics" => "Текст песни",
	"lyrics_nonefound" => "Никаких текстов не найдено",
	"lyrics_info" => "Чтобы использовать средство просмотра текстов, вам необходимо убедиться, что ваши локальные файлы отмечены лирикой",
	"lyrics_nopath" => "Чтобы использовать средство просмотра текстов, вам необходимо убедиться, что ваши локальные файлы отмечены лирикой и задайте путь музыки в настройках",
	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" => "ГОД",
	"title_title" => "НАЗВАНИЕ",
	"title_type" => "ТИП",
	"title_label" => "МЕТКА",
	"label_pages" => "СТРАНИЦЫ",
	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" => "КОМПАНИИ",
	"discogs_personnel" => "ПЕРСОНАЛИИ",
	"discogs_videos" => "ВИДЕО",
	"discogs_styles" => "СТИЛИ",
	"discogs_genres" => "ЖАНРЫ",
	"discogs_tracklisting" => "TRACK LISTING",
	"discogs_realname" => "REAL NAME:",
	"discogs_aliases" => "ALIASES:",
	"discogs_alsoknown" => "ALSO KNOWN AS:",
	"discogs_external" => "EXTERNAL LINKS",
	"discogs_bandmembers" => "BAND MEMBERS",
	"discogs_memberof" => "MEMBER OF",
	"discogs_discography" => "%s DISCOGRAPHY",
	// Discogs info panel
	"button_discogs" => "Панель информации (Discogs)",
	"discogs_error" => "Nothing was found by Discogs",
	"discogs_nonsense" => "Couldn't get a sensible response from Discogs",
	"discogs_noalbum" => "Couldn't find this album on Discogs",
	"discogs_notrack" => "Couldn't find this track on Discogs",
	// Musicbrainz info panel
	"button_musicbrainz" => "Панель информации (Musicbrainz)",
	"musicbrainz_error" => "Не получил ответа от MusicBrainz",
	"musicbrainz_contacterror" => "Произошла ошибка, связанная с Musicbrainz",
	"musicbrainz_noartist" => "Could not find this artist on Musicbrainz",
	"musicbrainz_noalbum" => "Could not find this album on Musicbrainz",
	"musicbrainz_notrack" => "Could not find this track on Musicbrainz",
	"musicbrainz_noinfo" => "Could not get information from Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" => "Present",
	"musicbrainz_origin" => "ORIGIN",
	"musicbrainz_active" => "ACTIVE",
	"musicbrainz_rating" => "РЕЙТИНГ",
	"musicbrainz_notes" => "ЗАМЕТКИ",
	"musicbrainz_tags" => "ТЕГИ",
	"musicbrainz_externaldiscography" => "Дискография (%s)",
	"musicbrainz_officalhomepage" => "Официальная страница (%s)",
	"musicbrainz_fansite" => "Фан Сайт (%s)",
	"musicbrainz_lyrics" => "Текст песни (%s)",
	"musicbrainz_social" => "Социальные сети",
	"musicbrainz_microblog" => "Микроблог",
	"musicbrainz_review" => "Обзор (%s)",
	"musicbrainz_novotes" => "(Нет голосов)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" => "%s/5 из %s голосов",
	"musicbrainz_appears" => "THIS TRACK APPEARS ON",
	"musicbrainz_credits" => "CREDITS",
	"musicbrainz_status" => "СОСТОЯНИЕ",
	"musicbrainz_date" => "ДАТА",
	"musicbrainz_country" => "СТРАНА",
	"musicbrainz_disc" => "ДИСК",
	// SoundCloud info panel
	"button_soundcloud" => "Панель информации (SoundCloud)",
	"soundcloud_trackinfo" => "Информация о треке",
	"soundcloud_plays" => "Plays",
	"soundcloud_downloads" => "Downloads",
	"soundcloud_faves" => "Faves",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" => "State",
	"soundcloud_license" => "License",
	"soundcloud_buy" => "Buy Track",
	"soundcloud_view" => "View on SoundCloud",
	"soundcloud_user" => "SoundCloud User",
	"soundcloud_fullname" => "Full Name",
	"soundcloud_Country" => "Страна",
	"soundcloud_city" => "Город",
	"soundcloud_website" => "Посетите вебсайт",
	"soundcloud_not" => "Эта панель будет отображать только информацию о музыке из SoundCloud",
	// Wikipedia Info Panel
	"button_wikipedia" => "Панель информации (Wikipedia)",
	"wiki_nothing" => "Не получил ничего от Википедии",
	"wiki_fail" => "Википедия не могла найти ничего, что связано с '%s'",
	"wiki_suggest" => "Wikipedia was unable to find any pages matching '%s'",
	"wiki_suggest2" => "Here are some suggestions it came up with",
	// Keybindings editor
	"title_keybindings" => "Горячие клавиши",
	"button_volup" => "Volume Up",
	"button_voldown" => "Volume Down",
	// Extras for mobile version
	"button_playlist" => "Плейлист",
	"button_playman" => "Редактировать Плейлисы",
	"button_mob_history" => "Панель информации История",
	"label_streamradio" => "Местное и Национальное Радио",
	// Various Plugins, Rating, and Tagging
	"lastfm_import" => "Import Your Last.FM Library",
	"lastfm_pleaselogin" => "You must be logged in to Last.FM to do this",
	"label_nosql" => "Это невозможно с вашей конфигурацией",
	"label_onlyloved" => "Loved Tracks Only",
	"label_onlytagged" => "Tagged Tracks Only",
	"label_tagandlove" => "Tagged Tracks and Loved Tracks",
	"label_everything" => "Everything",
	"label_giveloved" => "Loved Tracks Get:",
	"stars" => "stars",
	"star" => "star",
	"norating" => "No Rating",
	"button_importnow" => "Import Now",
	"label_review" => "Review Results Before Importing",
	"label_addtowish" => "If A Track Can't Be Found, Add It To The Wishlist",
	"label_tags" => "Теги",
	"label_oneresult" => "Результат поиска",
	"label_progress" => "Progress",
	"label_wishlist" => "Список пожеланий",
	"label_viewwishlist" => "Просмотр Список пожеланий",
	"label_addtow" => "Добавлен Список пожеланий",
	"label_finished" => "Законченный",
	"config_tagrat" => "Рейтинги и теги",
	"config_synctags" => "Keep Tags in Sync With Last.FM",
	"config_loveis" => "Last.FM Love Means",
	"playlist_xstar" => "%s or More Stars",
	"playlist_5star" => "5 Star Tracks",
	"button_about" => "О RompЯ",
	"label_notfound" => "Трек не найден",
	// Eg + 3 more
	"label_moreresults" => "+ %s больше",
	"label_tagmanagertop" => "Перетащить из музыкальной коллекции или списка воспроизведения для добавления меток в дорожки",
	"label_ratingmanagertop" => "Перетащить из музыкальной коллекции или списка воспроизведения для добавления оценок треков",
	"button_createtag" => "СОЗДАТЬ ТЕГ",
	//New in 0.52
	"config_alarm_ramp" => "Fade In",
	"label_retrieve" => "Retrieve",
	// New in 0.60
	"spotify_error" => "No response from Spotify",
	"spotify_noinfo" => "Could not get information from Spotify",
	"button_infospotify" => "Панель информации (Spotify)",
	"config_icontheme" => "ИКОНКИ",
	"label_radio" => "Радио",
	"label_pop" => "Popularity",
	"label_albumsby" => "Albums By This Artist",
	"label_singleartistradio" => "Tracks By Artist",
	"label_mostplayed" => "Favourite Tracks",
	"label_neverplayed" => "Never Played Tracks",
	"label_radio_fartist" => "Favourite Artists",
	"label_pluginplaylists" => "Personalised Radio",
	"label_recentlyadded_random" => "Recently Added Tracks (Random)",
	"label_recentlyadded_byalbum" => "Recently Added Albums",
	"setup_mpd" => "MPD/Mopidy Настройки",
	"settings_appearance" => "Appearance",
	"settings_panels" => "Панели",
	"settings_language" => "Язык",
	"settings_interface" => "Интерфейс",
	"label_charts" => "Топ 40",
	"label_choosedomains" => "Search these sources:",
	"label_dragtoprio" => "(Drag to change priority)",
	"button_subscribe" => "Subscribe",
	"config_sortbycomposer" => "Use Composer as Sort Artist",
	"config_composergenre" => " .. only if Genre is:",
	"config_displaycomposer" => "Display Composer/Performer in Now Playing",
	"label_radio_mix" => "Favourite Artists and Related Artists",
	"label_gotnotracks" => "Didn't find any tracks",
	"config_artistfirst" => "Artists At Top Of Collection",
	"config_nosortprefixes" => "Ignore These Prefixes When Sorting Artists",
	"config_sortcollectionby" => "Display Collection As:",
	"config_sortoptions" => "Collection Sorting Options",
	"button_skipforward" => "Skip Forwards",
	"button_skipbackward" => "Skip Backwards",
	"button_alarmsnooze" => "Отключение будильника",
	"config_snoozetime" => "Snooze Time (Минут)",
	"config_ramptime" => "Fade Time (Секунд)",
	"button_rateone" => "Rate 1 Звезда",
	"button_ratetwo" => "Rate 2 Звезды",
	"button_ratethree" => "Rate 3 Звезды",
	"button_ratefour" => "Rate 4 Звезды",
	"button_ratefive" => "Rate 5 Звёзд",
	"button_updatecollection" => "Обновить музыкальную коллекцию",
	"label_favealbums" => "Любимые альбомы",
	"button_nextsource" => "Панель информации - Cycle Source",
	"button_now_playing" => "Сейчас играет",
	"button_infopanel" => "Панель информации",
	"config_coversize" => "ALBUM COVER SIZE",
	"podcast_sortmode" => "Порядок сортировки",
	"podcast_newestfirst" => "Сначала новые",
	"podcast_oldestfirst" => "Сначала старые",
	"podcast_hidedescriptions" => "Скрыть описания",
	// New in 0.64/0.65/0.70
	"label_metabackup" => "Резервное копирование метаданных",
	"button_backup" => "Создать резервную копию",
	"button_restore" => "Восстановить из резервной копии",
	"button_collectioncontrols" => "Настройки сортировки музыкальной коллекции",
	"label_playlistmanager" => "Плейлист Manager",
	"label_playlistmanagertop" => "Перетащить из коллекции музыки для добавления треков в плейлисты",
	"button_createplaylist" => "СОЗДАТЬ ПЛЕЙЛИСТ",
	"label_renameplaylist" => "Переименовать Плейлист",
	"button_plugins" => "Дополнения",
	"label_filename" => "Имя файла",
	"label_resultscollection" => "Коллекция",
	"label_resultstree" => "Дерево каталогов",
	"label_displayresultsas" => "Показать результаты как:",
	"label_files" => "Файлы",
	"label_allartist" => "Все артисты ",
	"button_findexact" => "Найти точное соответствие",
	"label_albumartist" => "Исполнитель Альбома",
	"config_collectionfolders" => "Создать коллекцию из:",
	"button_videos" => "Похожее видео",
	"google_error" => "Не удалось связаться с Google",
	"label_allrandom" => "Все треки в случайном порядке",
	"config_background" => "ФОНОВОЕ ИЗОБРАЖЕНИЕ",
	"lastfm_error" => "Не удалось найти информацию на Last.FM",
	"config_skin" => "СКИН",
	// New in 0.71
	"label_albumsbyartist" => "Альбомы (по исполнителю)",
	"config_wheelspeed" => "Скорость прокрутки колесика мыши",
	"label_searchcollectiononly" => "Искать только в Музыкальной коллекции",
	"label_lastfm_mix" => "Last FM Lucky Dip",
	"label_lastfm_track" => "Last.FM Mix Радио",
	"label_lastfm_choose" => "Основы Last.FM Рекомендации по вашему прослушиванию:",
	"label_radio_recommend" => "Рекомендации, основанные на этом %s",
	"label_amendalbum" => "Изменить информацию об альбоме",
	//CHANGED in 0.60
	"config_country" => "СТРАНА (для Last.FM и Spotify)",
	"setup_labeladdresses" => "Если возникли проблемы с подключением, попробуйте использовать IP-адрес вместо «localhost»",
	"setup_ipaddress" => "Mopidy или mpd сервер",
	"config_cdplayermode" => "Режим CD Player (не записывает треки в очередь, запускает альбом с выбранного трека)",
	"label_recentlyplayed" => "Недавно прослушанные треки",
	"label_simar_radio" => "Артисты, похожие на",
	"label_tradsearch_header" => "Тип Все, что вы ищете",
	"label_tradsearch" => "Использовать традиционный поиск с несколькими терминами",
	"played_never" => "Этот трек никогда не слушали",
	"played_once" => "Этот трек был прослушан один раз",
	"played_twice" => "Этот трек был прослушан дважды",
	"played_n" => "Этот трек был прослушан в %s раз",
	"played_last" => "В последний раз %s",
	"added_on" => "Он был добавлен в сборник %s",
	"button_infoyou" => "The Discoverator",
	"discover_albums" => "Рекомендуемые альбомы",
	"discover_now" => "Track Suggestions Based On %s",
	"config_discovembobulate" => "Open Discoverator On Start",
	"label_spotify_mix" => "Spotify Weekly Mix",
	"label_spotify_dj" => "Spotify Swim",
	"label_spottery_lottery" => "Spotify Surprise!",
	"label_dailymix" => "Your Daily Mix",
	"label_luckydip" => "Your Lucky Dip",
	"label_startshere" => "Ваше открытие начинается здесь",
	"label_getspotify" => "Получить Spotify, чтобы начать поиск",
	"because_liked" => "You like %s, so you might like:",
	"because_listened" => "Похожий на %s:",
	"albumart_findsmall" => "Найти небольшие изображения",
	"label_smartsetup" => "Подготовка. Пожалуйста, подождите....",
	"button_sleep" => "Таймер Сна",
	"button_filter" => "Фильтр",
	"label_tuneinradio" => "Радиостанция TuneIn",
	"label_generalsettings" => "Общие настройки",
	"config_beetsserver" => "Location of Beets Server (ip.address:port)",
	"config_mopidy_scan" => "Команда локального сканирования Mopidy",
	"config_players" => 'Плеер',
	"button_edit_players" => 'Изменить Плеер',
	
	"label_play_all" => "Играть Всё",
	"label_play_options" => "Параметры воспроизведения",
	"label_last_played" => "Последний проигранный:",
	"label_station_website" => "Сайт станции",
	
	"label_play_whole_album" => "Воспроизвести весь альбом",
	"label_from_collection" => "Воспроизвести только треки из коллекции",
	"label_with_ratings" => "Воспроизвести только треки с рейтингами",
	"label_with_tags" => "Воспроизвести только треки с тегами",
	"label_with_tagandrat" => "Играть только треки с тегами и рейтингами",
	"label_with_tagorrat" => "Воспроизвести только треки с тегами или рейтингами"
);
?>
