<?php

language::add_translations([

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"Kolekcija Muzike",
	"button_file_browser" =>				"Preglednik Fajlova",
	"button_internet_radio" =>				"Internet Radio Stanice",
	"button_albumart" =>					"Upravljač Omota Albuma",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"Prebaci Panel Izvora",
	"button_back" =>						"Nazad",
	"button_history" =>						"Istorija",
	"button_forward" =>						"Napred",
	"button_toggleplaylist" =>				"Prebaci Plejlistu",

	// Tooltips for playlist buttons
	"button_alarm" =>						"Alarm",
	"button_prefs" =>						"RompÐ¯ Podešavanja",
	"button_clearplaylist" =>				"Obriši Plejlistu",
	"button_loadplaylist" =>				"Učitaj Sačuvanu Plejlistu",
	"button_saveplaylist" =>				"Sačuvaj Plejlistu",

	// Tooltips for playback controls
	"button_previous" =>					"Prethodna Pesma",
	"button_play" =>						"Pusti/Pauziraj",
	"button_stop" =>						"Zaustavi",
	"button_stopafter" =>					"Zaustavi Nakon Trenutne Pesme",
	"button_next" =>						"Sledeća Pesma",
	"button_love" =>						"Označi kao Omiljenu",
	"button_ban" =>							"Banuj Ovu Pesmu",
	"button_volume" =>						"Jačina Zvuka",

	// Configuration menu entries
	"config_theme" =>						"TEMA",
	"config_hidealbumlist" =>				"Sakrij Kolekciju Muzike",
	"config_hidefileslist" =>				"Sakrij Listu Fajlova",
	"config_hideradio" =>					"Sakrij Radio Stanice",
	"config_hidepodcasts" =>				"Sakrij Podkaste",
	"config_hideplaylistslist" =>			"Sakrij Sačuvane Plejliste",
	"config_hidepluginplaylistslist" =>		"Sakrij Personalizovan Radio",
	"config_hidebrowser" =>					"Sakrij Info Panel",
	"config_lastfmlang" =>					"Jezik za Last.FM i Vikipediju",
	"config_lastfmdefault" =>				"Podrazumevani jezik (Engleski)",
	"config_lastfminterface" =>				"Jezik RompÐ¯ interfejsa",
	"config_lastfmbrowser" =>				"Podrazumevani jezik pretraživača",
	"config_autoscroll" =>					"Automatsko pomeranje plejliste na trenutnu pesmu",
	"config_autocovers" =>					"Automatsko preuzimanje omota",
	"config_musicfolders" =>				"Da biste koristili umetnička dela iz vaših muzičkih foldera ili dobili stihove iz vaših fajlova, unesite putanju do vaše muzike u ovo polje:",
	"config_crossfade" =>					"Trajanje Prelaska (sekunde)",
	"config_doubleclick" =>					"Dupli klik za puštanje, Jedan klik za odabir",
	"config_singleclick" =>					"Jedan klik za puštanje",
	"config_sortbydate" =>					"Sortiranje Albuma po Datumu",
	"config_notvabydate" =>					"Ne primenjuj sortiranje po datumu na 'Razni Umetnici'",
	"config_updateonstart" =>				"Ažuriraj Kolekciju Muzike na Početku",
	"config_updatenow" =>					"Ažuriraj Kolekciju Muzike Sada",
	"config_rescan" =>						"Potpuno Skeniranje Lokalne Muzike",
	"config_editshortcuts" =>				"Uredi Prečice na Tastaturi...",
	"config_audiooutputs" =>				"Audio Izlazi",
	"config_lastfmusername" =>				"Last.FM Korisničko Ime",
	"config_loginbutton" =>					"Prijavi se",
	"config_scrobbling" =>					"Skrobl pesme na Last.FM",
	"config_noscrobble_audiobook" =>		"Ne skrobl Govorni Sadržaj",
	"config_noscrobble_podcast" =>			"Ne skrobl Podkast pesme",
	"config_autocorrect" =>					"Koristi Last.FM za auto-korekciju imena umetnika itd",
	"config_tagloved" =>					"Označi Omiljene Pesme Sa:",
	"config_fontsize" =>					"VELIČINA FONTA",
	"config_fontname" =>					"STIL FONTA",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"Sačuvaj",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"Pretraži Muziku",
	"label_yourradio" =>					"Vaše Radio Stanice",
	"label_podcasts" =>						"Podkasti",
	"label_somafm" =>						"Soma FM",
	"label_emptyinfo" =>					"Ovo je informacioni panel. Zanimljive stvari će se pojaviti ovde kada pustite neku muziku",
	"button_playlistcontrols" =>			"Kontrole Plejliste",
	"button_random" =>						"MEŠANJE",
	"button_crossfade" =>					"PRELAZAK",
	"button_repeat" =>						"PONAVLJANJE",
	"button_consume" =>						"KONZUMIRAJ",
	"label_yes" =>							"Da",
	"label_no" =>							"Ne",
	"label_updating" =>						"Ažuriranje Kolekcije Muzike",
	"label_update_error" =>					"Neuspešno generiranje kolekcije muzike.",
	"label_playlisterror" =>				"Nešto je pošlo po zlu pri dobijanju plejliste!",
	"button_OK" =>							"OK",
	"button_cancel" =>						"Otkaži",
	"error_playlistname" =>					"Ime plejliste ne može da sadrži kosme crte",
	"label_savedpl" =>						"Plejlista sačuvana kao %s",

	// Search Forms
	"label_searchfor" =>					"Pretraži",
	"label_searching" =>					"Pretražuje...",
	"label_searchresults" =>				"Rezultati Pretrage",

	// General multipurpose labels
	"label_tracks" =>						"pesme",
	"label_albums" =>						"albumi",
	"label_artists" =>						"umetnici",
	"label_track" =>						"Pesma",
	"label_album" =>						"Album",
	"label_artist" =>						"Umetnik",
	"label_anything" =>						"Bilo Šta",
	"label_genre" =>						"Žanr",
	"label_composer" =>						"Kompozitor",
	"label_performer" =>					"Izvođač",
	"label_rating" =>						"Ocena",
	"label_tag" =>							"Oznaka",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Vikipedija",
	"label_general_error" =>				"Došlo je do greške. Molimo osvežite stranicu i pokušajte ponovo",
	"label_days" =>							"dana",
	"label_noalbums" =>						"Nema Pronađenih Albuma",
	"label_duration" =>						"Trajanje",
	"label_playererror" =>					"Greška Plejer",
	"button_playradio" =>					"Pusti",

	// Playlist and Now Playing
	"label_notforradio" =>					"Nije podržano za radio tokove",
	"label_incoming" =>						"Dolazi...",
	"label_addingtracks" =>					"Dodavanje Pesama u Red",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"od",
	"label_on" =>							"na",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"od",

	// Podcasts
	"podcast_entrybox" =>					"Pretplati se na RSS feed:",
	// Podcast tooltips
	"podcast_delete" =>						"Obriši ovaj Podkast",
	"podcast_configure" =>					"Konfiguriši ovaj Podkast",
	"podcast_refresh" =>					"Osveži ovaj Podkast",
	"podcast_download_all" =>				"Preuzmi Sve Epizode ovog Podkasta",
	"podcast_mark_all" =>					"Označi Sve Epizode kao Odslušane",
	"podcast_undelete" =>					"Poništi Brisanje Obrisanih Epizoda",
	"podcast_removedownloaded" =>			"Ukloni Preuzete Fajlove",
	// Podcast display options
	"podcast_display" =>					"Prikaži",
	"podcast_display_all" =>				"Sve",
	"podcast_display_onlynew" =>			"Samo Novo",
	"podcast_display_unlistened" =>			"Novo i Neodslušano",
	"podcast_display_downloadnew" =>		"Novo i Preuzeto",
	"podcast_display_downloaded" =>			"Samo Preuzeto",
	// Podcast refresh options
	"podcast_refresh" =>					"Osveži",
	"podcast_refresh_never" =>				"Ručno",
	"podcast_refresh_hourly" =>				"Svakog Sata",
	"podcast_refresh_daily" =>				"Dnevno",
	"podcast_refresh_weekly" =>				"Nedeljno",
	"podcast_refresh_monthly" =>			"Mesečno",
	// Podcast auto expire
	"podcast_expire" =>						"Čuvaj Epizode",
	"podcast_expire_tooltip" =>				"Sve epizode starije od ove vrednosti biće uklonjene sa liste. Promene ove opcije stupićeju na snagu sledeći put kada osvežite podkast",
	"podcast_expire_never" =>				"Uvek",
	"podcast_expire_week" =>				"Jednu Nedelju",
	"podcast_expire_2week" =>				"Dve Nedelje",
	"podcast_expire_month" =>				"Jedan Mesec",
	"podcast_expire_2month" =>				"Dva Meseca",
	"podcast_expire_6month" =>				"Šest Meseci",
	"podcast_expire_year" =>				"Godinu Dana",
	// Podcast number to keep
	"podcast_keep" =>						"Broj za Čuvanje",
	"podcast_keep_tooltip" =>				"Lista će uvek pokazati samo ovoliko epizoda. Promene ove opcije stupićeju na snagu sledeći put kada osvežite podkast",
	"podcast_keep_0" =>						"Neograničeno",
	// Podcast other options
	"podcast_keep_downloaded" =>			"Čuvaj sve preuzete epizode",
	"podcast_kd_tooltip" =>					"Omogućite ovu opciju da sačuvate sve preuzete epizode. Gornje dve opcije će se tada primeniti samo na epizode koje nisu preuzete",
	"podcast_tooltip_new" =>				"Ovo je nova epizoda",
	"podcast_tooltip_notnew" =>				"Ova epizoda nije nova ali nije odslušana",
	"podcast_tooltip_downloaded" =>			"Ova epizoda je preuzeta. Kliknite da uklonite preuzeti fajl.",
	"podcast_tooltip_download" =>			"Preuzmite ovu epizodu na vaš kompjuter",
	"podcast_tooltip_mark" =>				"Označi kao odslušano",
	"podcast_tooltip_delepisode" =>			"Obriši ovu epizodu",

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"Molimo razmislite o podršci Soma.FM-u ako vam se dopate ove stanice",

	// Your radio stations
	"label_radioinput" =>					"Unesite URL",

	//Album Art Manager
	"albumart_title" =>						"Omot Albuma",
	"albumart_getmissing" =>				"Dobij Nedostajuće Omote",
	"albumart_showall" =>					"Prikaži Sve Omote",
	"albumart_instructions" =>				"Kliknite na omot da ga promenite, ili prevucite sliku sa vašeg hard diska ili drugog prozora pretraživača",
	"albumart_onlyempty" =>					"Prikaži Samo Albume Bez Omota",
	"albumart_allartists" =>				"Svi Umetnici",
	"albumart_googlesearch" =>				"Brave Pretraga",
	"albumart_local" =>						"Lokalne Slike",
	"albumart_upload" =>					"Upload Fajla",
	"albumart_uploadbutton" =>				"Upload",
	"albumart_newtab" =>					"Google Pretraga u Novom Tabu",
	"albumart_dragdrop" =>					"Možete prevući i pustiti slike sa vašeg hard diska ili drugog prozora pretraživača direktno na sliku (u većini pretraživača)",
	"albumart_showmore" =>					"Prikaži Više Rezultata",
	"albumart_googleproblem" =>				"Bilo je problema. Brave je rekao",
	"albumart_getthese" =>					"Dobij Ove Omote",
	"albumart_nocovercount" =>				"albumi bez omota",
	"albumart_getting" =>					"Dobijanje",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr se nije mogao povezati na mpd ili mopidy server",
	"setup_connecterror" =>					"Došlo je do greške pri komunikaciji sa vašim mpd ili mopidy serverom : ",
	"setup_request" =>						"Zatražili ste stranicu za podešavanje",
	"setup_addressnote" =>					"Napomena: localhost u ovom kontekstu znači kompjuter na kome se pokreće veb server",
	"setup_port" =>							"Port",
	"setup_advanced" =>						"Napredne opcije",
	"setup_password" =>						"Lozinka",
	"setup_unixsocket" =>					"UNIX-domain socket",
	"setup_websocket_port" =>				"Websocket Port",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"Prijavite se na Last.FM",
	"lastfm_login1" =>						"Molimo kliknite na link ispod da otvorite Last.FM veb sajt u novom tabu. Unesite vaše Last.FM podatke za prijavu ako je potrebno, zatim dajte RompÐ¯-u dozvolu da pristupi vašem nalogu",
	"lastfm_login2" =>						"Možete zatvoriti novi tab kada završite, ali ne zatvarajte ovaj dijalog!",
	"lastfm_loginbutton" =>					"Kliknite Ovde za Prijavu",
	"lastfm_login3" =>						"Kada se prijavite na Last.FM, kliknite OK dugme ispod da završite proces",
	"lastfm_loginfailed" =>					"Neuspešna prijava na Last.FM",
	"label_loved" =>						"Omiljena",
	"label_lovefailed" =>					"Neuspešno Označavanje kao Omiljena",
	"label_unloved" =>						"Nije Omiljena",
	"label_unlovefailed" =>					"Neuspešno Uklanjanje Oznake Omiljene",
	"label_scrobblefailed" =>				"Neuspešno skroblovanje",

	// Info Panel
	"info_gettinginfo" =>					"Dobijanje Informacija...",
	"info_newtab" =>						"Prikaži u Novom Tabu",

	// File Info panel
	"button_fileinfo" =>					"Info Panel (Informacije o Kolekciji)",
	"info_file" =>							"Fajl",
	"info_from_beets" =>					"(sa beets servera)",
	"info_format" =>						"Format:",
	"info_bitrate" =>						"Bitrate:",
	"info_samplerate" =>					"Sample Rate:",
	"info_mono" =>							"Mono",
	"info_stereo" =>						"Stereo",
	"info_channels" =>						"Kanali",
	"info_date" =>							"Datum:",
	"info_genre" =>							"Žanr:",
	"info_performers" =>					"Izvođači:",
	"info_composers" =>						"Kompozitori:",
	"info_comment" =>						"Komentar:",
	"info_label" =>							"Labela:",
	"info_disctitle" =>						"Naslov Diska:",
	"info_encoder" =>						"Enkoder:",
	"info_year" =>							"Godina:",

	// Last.FM Info Panel
	"button_infolastfm" =>					"Info Panel (Last.FM)",
	"label_notrackinfo" =>					"Nije moguće pronaći informacije o ovoj pesmi",
	"label_noalbuminfo" =>					"Nije moguće pronaći informacije o ovom albumu",
	"label_noartistinfo" =>					"Nije moguće pronaći informacije o ovom umetniku",
	"lastfm_listeners" =>					"Slušaoci:",
	"lastfm_plays" =>						"Puštanja:",
	"lastfm_yourplays" =>					"Vaša Puštanja:",
	"lastfm_toptags" =>						"TOP OZNAKE:",
	"lastfm_addtags" =>						"DODAJ OZNAKE",
	"lastfm_addtagslabel" =>				"Dodajte oznake, odvojene zarezom",
	"button_add" =>							"DODAJ",
	"lastfm_yourtags" =>					"VAŠE OZNAKE:",
	"lastfm_simar" =>						"Slični Umetnici",
	"lastfm_removetag" =>					"Ukloni Oznaku",
	"lastfm_releasedate" =>					"Datum Izdavanja",
	"lastfm_viewtrack" =>					"Prikaži pesmu na Last.FM",
	"lastfm_tagerror" =>					"Neuspešno menjanje oznaka",
	"lastfm_loved" =>						"Omiljena",
	"lastfm_lovethis" =>					"Označi Ovu Pesmu kao Omiljenu",
	"lastfm_unlove" =>						"Ukloni Oznaku Omiljene sa Ove Pesme",
	"lastfm_notfound" =>					"%s Nije Pronađen",

	// Lyrics info panel
	"button_lyrics" =>						"Info Panel (Stihovi)",
	"lyrics_lyrics" =>						"Stihovi",
	"lyrics_nonefound" =>					"Nisu pronađeni stihovi",
	"lyrics_info" =>						"Da biste koristili prikazivač stihova potrebno je da se vaši lokalni fajlovi označene sa stihovima",
	"lyrics_nopath" =>						"Da biste koristili prikazivač stihova potrebno je da se vaši lokalni fajlovi označene sa stihovima i postavite putanju muzike u podešavanjima",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"GODINA",
	"title_title" =>						"NASLOV",
	"title_type" =>							"TIP",
	"title_label" =>						"LABELA",
	"label_pages" =>						"STRANICE",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"KOMPANIJE",
	"discogs_personnel" =>					"OSOBLJE",
	"discogs_videos" =>						"VIDEI",
	"discogs_styles" =>						"STILOVI",
	"discogs_genres" =>						"ŽANROVI",
	"discogs_tracklisting" =>				"LISTA PESAMA",
	"discogs_realname" =>					"PRAVO IME:",
	"discogs_aliases" =>					"PSEUDONIMI:",
	"discogs_alsoknown" =>					"TAKOĐE POZNAT KAO:",
	"discogs_external" =>					"SPOLJNI LINKOVI",
	"discogs_bandmembers" =>				"ČLANOVI BENDA",
	"discogs_memberof" =>					"ČLAN OD",
	"discogs_discography" =>				"%s DISKOGRAFIJA",

	// Discogs info panel
	"button_discogs" =>						"Info Panel (Discogs)",
	"discogs_error" =>						"Ništa nije pronađeno na Discogs-u",
	"discogs_nonsense" =>					"Nije moguće dobiti razuman odgovor od Discogs-a",
	"discogs_noalbum" =>					"Nije moguće pronaći ovaj album na Discogs-u",
	"discogs_notrack" =>					"Nije moguće pronaći ovu pesmu na Discogs-u",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"Info Panel (Musicbrainz)",
	"musicbrainz_error" =>					"Nije dobijen odgovor od MusicBrainz-a",
	"musicbrainz_contacterror" =>			"Došlo je do greške pri kontaktiranju Musicbrainz-a",
	"musicbrainz_noartist" =>				"Nije moguće pronaći ovog umetnika na Musicbrainz-u",
	"musicbrainz_noalbum" =>				"Nije moguće pronaći ovaj album na Musicbrainz-u",
	"musicbrainz_notrack" =>				"Nije moguće pronaći ovu pesmu na Musicbrainz-u",
	"musicbrainz_noinfo" =>					"Nije moguće dobiti informacije od Musicbrainz-a",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Trenutno",
	"musicbrainz_origin" =>					"POREKLO",
	"musicbrainz_active" =>					"AKTIVAN",
	"musicbrainz_rating" =>					"OCENA",
	"musicbrainz_notes" =>					"NAPOMENE",
	"musicbrainz_tags" =>					"OZNAKE",
	"musicbrainz_externaldiscography" =>	"Diskografija (%s)",
	"musicbrainz_officalhomepage" =>		"Zvanična Početna Stranica (%s)",
	"musicbrainz_fansite" =>				"Fan Sajt (%s)",
	"musicbrainz_lyrics" =>					"Stihovi (%s)",
	"musicbrainz_social" =>					"Društvena Mreža (%s)",
	"musicbrainz_streaming" =>				"Besplatan Strim (%s)",
	"musicbrainz_microblog" =>				"Mikroblog",
	"musicbrainz_review" =>					"Recenzija (%s)",
	"musicbrainz_purchase" =>				"Kupovina (%s)",
	"musicbrainz_novotes" =>				"(Nema Glasova)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 od %s glasova",
	"musicbrainz_appears" =>				"OVA PESMA SE POJAVLJUJE NA",
	"musicbrainz_credits" =>				"ZASLUGE",
	"musicbrainz_status" =>					"STATUS",
	"musicbrainz_date" =>					"DATUM",
	"musicbrainz_country" =>				"ZEMLJA",
	"musicbrainz_disc" =>					"DISK",
	"musicbrainz_album_releases" =>			"IZDANJA OVOG ALBUMA",

	// SoundCloud info panel
	"button_soundcloud" =>					"Info Panel (SoundCloud)",
	"soundcloud_trackinfo" =>				"Info o Pesmi",
	"soundcloud_plays" =>					"Puštanja",
	"soundcloud_downloads" =>				"Preuzimanja",
	"soundcloud_faves" =>					"Omiljene",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"Stanje",
	"soundcloud_license" =>					"Licenca",
	"soundcloud_buy" =>						"Kupi Pesmu",
	"soundcloud_view" =>					"Prikaži na SoundCloud-u",
	"soundcloud_user" =>					"SoundCloud Korisnik",
	"soundcloud_fullname" =>				"Puno Ime",
	"soundcloud_Country" =>					"Zemlja",
	"soundcloud_city" =>					"Grad",
	"soundcloud_website" =>					"Posetite Veb Sajt",
	"soundcloud_not" =>						"Ovaj panel će prikazati informacije samo o muzici sa SoundCloud-a",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"Info Panel (Vikipedija)",
	"wiki_nothing" =>						"Ništa nije dobijeno sa Vikipedije",
	"wiki_fail" =>							"Vikipedija nije mogla pronaći ništa povezano sa '%s'",
	"wiki_suggest" =>						"Vikipedija nije mogla pronaći stranice koje se poklapaju sa '%s'",
	"wiki_suggest2" =>						"Evo nekoliko predloga koje je smislila",

	// Keybindings editor
	"title_keybindings" =>					"Prečice na Tastaturi",
	"button_volup" =>						"Pojačaj Zvuk",
	"button_voldown" =>						"Smanji Zvuk",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"zvezde",
	"star" =>								"zvezda",
	"label_tags" =>							"Oznake",
	"label_wishlist" =>						"Lista Želja",
	"label_viewwishlist" =>					"Prikaži Vašu Listu Želja",
	"label_addtow" =>						"Dodano u Listu Želja",
	"config_synctags" =>					"Držite Oznake Sinhronizovane sa Last.FM",
	"config_loveis" =>						"Last.FM Omiljena Znači",
	"playlist_xstar" =>						"%s ili Više Zvezda",
	"button_about" =>						"O RompÐ¯-u",
	"label_notfound" =>						"Pesma Nije Pronađena",
	// Eg + 3 more

	//New in 0.52
	"config_alarm_ramp" =>					"Postupno Pojačavanje",

	// New in 0.60
	"spotify_error" =>						"Nema odgovora od Spotify-a",
	"spotify_noinfo" =>						"Nije moguće dobiti informacije od Spotify-a",
	"button_infospotify" =>					"Info Panel (Spotify)",
	"config_icontheme" =>					"IKONE",
	"label_radio" =>						"Radio",
	"label_pop" =>							"Popularnost",
	"label_albumsby" =>						"Albumi Ovog Umetnika",
	"label_singleartistradio" =>			"Pesme po Umetniku",
	"label_mostplayed" =>					"Omiljene Pesme",
	"label_neverplayed" =>					"Nikad Puštane Pesme",
	"label_radio_fartist" =>				"Omiljeni Umetnici",
	"label_pluginplaylists" =>				"Personalizovan Radio",
	"label_recentlyadded_random" =>			"Nedavno Dodane Pesme (Nasumično)",
	"label_recentlyadded_byalbum" =>		"Nedavno Dodani Albumi",
	"setup_mpd" =>							"MPD/Mopidy Podešavanja",
	"settings_appearance" =>				"Izgled",
	"settings_panels" =>					"Paneli",
	"settings_language" =>					"Jezik",
	"settings_interface" =>					"Interfejs",
	"label_charts" =>						"Top 40",
	"button_subscribe" =>					"Pretplati se",
	"config_composergenre" =>				" .. samo ako je Žanr:",
	"config_displaycomposer" =>				"Prikaži Kompozitor/Izvođač u Trenutno Pušteno",
	"label_radio_mix" =>					"Omiljeni Umetnici i Povezani Umetnici",
	"label_gotnotracks" =>					"Nisu pronađene pesme",
	"config_artistfirst" =>					"Umetnici na Vrhu Kolekcije",
	"config_nosortprefixes" =>				"Ignoriši Ove Prefikse pri Sortiranju",
	"button_skipforward" =>					"Preskoči Napred",
	"button_skipbackward" =>				"Preskoči Nazad",
	"config_snoozetime" =>					"Vreme Dremanja (Min)",
	"config_ramptime" =>					"Vreme Prelaska (Sek)",
	"button_rateone" =>						"Oceni 1 Zvezdu",
	"button_ratetwo" =>						"Oceni 2 Zvezde",
	"button_ratethree" =>					"Oceni 3 Zvezde",
	"button_ratefour" =>					"Oceni 4 Zvezde",
	"button_ratefive" =>					"Oceni 5 Zvezda",
	"button_updatecollection" =>			"Ažuriraj Kolekciju Muzike",
	"label_favealbums" =>					"Omiljeni Albumi",
	"button_nextsource" =>					"Info Panel - Kruži Izvor",
	"button_infopanel" =>					"Info Panel",
	"config_coversize" =>					"VELIČINA OMOTA ALBUMA",
	"podcast_sortmode" =>					"Redosled Sortiranja",
	"podcast_newestfirst" =>				"Najnoviji Prvo",
	"podcast_oldestfirst" =>				"Najstariji Prvo",
	"podcast_hidedescriptions" =>			"Sakrij Opise",

	// New in 0.64/0.65/0.70
	"label_metabackup" =>					"Backup Metapodataka",
	"button_backup" =>						"Napravi Backup",
	"button_restore" =>						"Vrati Backup",
	"button_collectioncontrols" =>			"Kontrole Sortiranja Kolekcije Muzike",
	"button_createplaylist" =>				"NAPRAVI PLEJLISTU",
	"label_renameplaylist" =>				"Preimenuj Plejlistu",
	"button_plugins" =>						"Sve Vrste Dobrih Stvari",
	"label_filename" =>						"Ime Fajla",
	"label_resultscollection" =>			"Kolekcija",
	"label_resultstree" =>					"Stablo Direktorijuma",
	"label_displayresultsas" =>				"Prikaži Rezultate Pretrage Muzike Kao:",
	"label_files" =>						"Fajlovi",
	"label_albumartist" =>					"Umetnik Albuma",
	"config_collectionfolders" =>			"Izgradi Kolekciju Od:",
	"button_videos" =>						"Povezani Videi",
	"label_allrandom" =>					"Sve Pesme Nasumično",
	"label_randomalbums" =>					"Svi Albumi Nasumično",
	"config_background" =>					"Pozadinska Slika",
	"lastfm_error" =>						"Nije moguće pronaći informacije na Last.FM",
	"config_skin" =>						"KOŽA",

	// New in 0.71
	"label_albumsbyartist" =>				"Albumi (po Umetniku)",
	"config_wheelspeed" =>					"Brzina Skrolovanja Mišem",

	"label_radio_recommend" =>				"Preporuke zasnovane na ovom %s",
	"label_amendalbum" =>					"Izmeni Detalje Albuma",
	"label_radio_recommended" =>			"Preporuke za Vas",

	//CHANGED in 0.60
	"config_country" =>						"ZEMLJA (za Spotify)",
	"setup_labeladdresses" =>				"Ako imate probleme sa konekcijom, pokušajte da koristite IP adresu umesto 'localhost'",
	"setup_ipaddress" =>					"Mopidy ili mpd server",

	"config_cdplayermode" =>				"CD Player Režim (ne stavljaj pesme u red, počni album od odabrane pesme)",

	"label_recentlyplayed" =>				"Nedavno Puštane Pesme",
	"label_simar_radio" =>					"Umetnici Slični sa",

	"label_tradsearch" =>					"Napredna Pretraga",

	"played_never" =>						"Ova pesma nikad nije puštana",
	"played_once" =>						"Ova pesma je puštana jednom",
	"played_twice" =>						"Ova pesma je puštana dva puta",
	"played_n" =>							"Ova pesma je puštana %s puta",
	"played_last" =>						"Poslednji put je puštana %s",
	"added_on" =>							"Dodana je u kolekciju %s",
	"button_infoyou" =>						"Otkrivač",
	"discover_now" =>						"Predlozi Pesama Zasnovani na %s",
	"label_spotify_mix" =>					"Spotify Nedeljni Miks",
	"label_spotify_dj" =>					"Spotify Plivanje",
	"label_spottery_lottery" =>				"Spotify Iznenađenje!",
	"label_dailymix" =>						"Vaš Dnevni Miks",
	"label_luckydip" =>						"Vaša Sreća",
	"label_startshere" =>					"Vaše Otkrivanje Počinje Ovde",
	"label_getspotify" =>					"Idite Online da Počnete Otkrivanje",
	"because_liked" =>						"Sviđa vam se %s, pa bi vam se moglo svideti:",
	"because_listened" =>					"Slično sa %s:",
	"albumart_findsmall" =>					"Pronađi Male Slike",
	"button_sleep" =>						"Tajmer za Spavanje",
	"label_tuneinradio" =>					"TuneIn Radio Direktorijum",
	"label_generalsettings" =>				"Opšta Podešavanja",
	"config_beetsserver" =>					"Lokacija Beets Servera (ip.adresa:port)",
	"config_players" =>						"Plejeri",
	"button_edit_players" =>				"Uredi Plejere",

	"label_play_all" =>						"Pusti Sve od ovog Umetnika",
	"label_last_played" =>					"Poslednji Put Puštano:",
	"label_station_website" =>				"Veb Sajt Stanice",

	"label_play_whole_album" =>				"Pusti Ceo Album",
	"label_from_collection" =>				"Pusti Sve Pesme iz Kolekcije",
	"label_with_ratings" =>					"Pusti Samo Pesme sa Ocenama",
	"label_with_tags" =>					"Pusti Samo Pesme sa Oznakama",
	"label_with_tagandrat" =>				"Pusti Samo Pesme sa Oznakama i Ocenama",
	"label_with_tagorrat" =>				"Pusti Samo Pesme sa Oznakama ili Ocenama",
	"config_read_the_docs" =>				"Molimo Pročitajte Dokumentaciju",
	"label_dateadded" =>					"Datum Dodavanja",
	"label_radiostation" =>					"Radio Stanica",
	"label_opmlimporter" =>					"OPML Uvoznik",
	"config_playerintitlebar" =>			"Prikaži Ime Plejera u Naslovnoj Liniji",
	"label_communityradio" =>				"Preglednik Zajedničkih Radio Stanica",
	"label_volume" =>						"Jačina Zvuka",
	"button_debuginfo" =>					"Debug Informacije",
	"config_podcast_defaults" =>			"Podrazumevane Opcije za Nove Podkaste",
	"config_marknewasunlistened" =>			"Označi Nove Epizode kao Neodslušane Pre Osvežavanja",
	"config_albumartinplaylist" =>			"Prikaži Omot Albuma u Redu za Puštanje",
	"label_resume" =>						"Nastavi",
	"label_sortby" =>						"Sortiraj po",
	"label_then" =>							"Zatim",
	"label_publisher" =>					"Izdavač",
	"label_category" =>						"Kategorija",
	"label_new_episodes" =>					"Nove Epizode",
	"label_unlistened_episodes" =>			"Neodslušane Epizode",
	"label_loading" =>						"Učitava...",
	"label_choosefile" =>					"Odaberite Fajl",
	"label_choosefiles" =>					"Odaberite Fajl(ove)",
	"label_changevery" =>					"Menjaj Svaki",
	"label_albumstolistento" =>				"Albumi za Slušanje",
	"no_albumtolistento" =>					"Možete dodati bilo koji Spotify album na ovu listu iz Info Panela, zatim se možete vratiti i proveriti ih u svoje vreme.",
	"label_addedtolistenlater" =>			"Dodano u Albume za Slušanje",
	"label_all_time" =>						"Cela Kolekcija",
	"label_today" =>						"Dodano Danas",
	"label_thisweek" =>						"Dodano Ove Nedelje",
	"label_thismonth" =>					"Dodano Ovog Meseca",
	"label_thisyear" =>						"Dodano Ove Godine",
	"label_searchtrack" =>					"Pretraži Ovu Pesmu",
	"label_removefromwl" =>					"Ukloni Pesmu iz Liste Želja",
	"label_gethelp" =>						"Kliknite za Pomoć",
	"label_podcastcontrols" =>				"Kontrole Pretrage i Sortiranja Podkasta",
	"label_closepanel" =>					"Zatvori ovaj Panel",
	"label_hidepanel" =>					"Sakrij Ovaj Panel",
	"label_removefromplaylist" =>			"Ukloni iz Plejliste",
	"label_addtolistenlater" =>				"Dodaj u Albume za Slušanje",
	"label_removefromlistenlater" =>		"Ukloni iz Albuma za Slušanje",
	"label_addtocollection" =>				"Dodaj Album u Kolekciju Muzike",
	"label_addtoradio" =>					"Dodaj u Vaše Radio Stanice",
	"button_logout" =>						"Odjavi se",
	"label_transferplaylist" =>				"Prebaci Red za Puštanje na Novi Plejer?",
	"label_yes" =>							"Da",
	"label_no" =>							"Ne",
	"podcast_refresh_all" =>				"Osveži Sve Podkaste",
	"label_global_controls" =>				"Globalne Kontrole",
	"label_topleft" =>						"Gore Levo",
	"label_topright" =>						"Gore Desno",
	"label_bottomleft" =>					"Dole Levo",
	"label_bottomright" =>					"Dole Desno",
	"label_centre" =>						"Centrirano",
	"label_bottomcentre" =>					"Centrirano na Dnu",
	"label_topcentre" =>					"Centrirano na Vrhu",
	"config_preferlocal" =>					"Preferiraj Lokalnu Muziku nad Internet Izvorima",
	"config_lastfm_playcounts" =>			"Koristi Last.FM Brojače Puštanja",
	"config_sync_lastfm_playcounts" =>		"Sinhronizuj Brojače Puštanja sa last.FM",
	"label_lfm_playcountimporter" =>		"Last.FM Uvoznik Brojača Puštanja",
	"label_mustlogintolfm" =>				"Morate biti prijavljeni na Last.FM da biste koristili ovu funkciju",
	"label_lfm_syncing" =>					"Sinhronizacija Last.FM Brojača Puštanja",
	"label_lfm_nonew" =>					"Nisu dodane nove pesme u Kolekciju Muzike od poslednjeg uvoza %s",
	"config_smart_chunksize" =>				"Broj predstojećih pesama za prikaz",
	"warning_smart_debug" =>				"UPOZORENJE! Pokretanje Personalnog Radija sa omogućenim debug režimom može srušiti vaš pretraživač!",
	"label_unplayabletracks" =>				"Nepuštive Pesme",
	"label_no_unplayable" =>				"Nema nepuštavih pesama u vašoj Kolekciji",
	"label_removefromcol" =>				"Ukloni iz Kolekcije",
	"label_audiobooks" =>					"Govorni Sadržaj",
	"config_hideaudiobooks" =>				"Sakrij Govorni Sadržaj",
	"config_audiobook_directory" =>			"Direktorijum koji Sadrži Fajlove Govornog Sadržaja",
	"error_imageupload" =>					"Neuspešan Upload Slike",
	"error_toomanyimages" =>				"Previše slika, ili je fajl slike prevelik",
	"error_sendingcommands" =>				"Neuspešno Slanje Komandi %s",
	"error_cantdeleteplayer" =>				"Ne možete obrisati plejer koji trenutno koristite",
	"error_duplicateplayer" =>				"Ne možete imati dva plejera sa istim imenom",
	"error_backupfail" =>					"Neuspešan %s backup",
	"error_nogenres" =>						"Molimo odaberite neke Žanrove",
	"error_collectionupdate" =>				"Ažuriranje Kolekcije Muzike Neuspešno",
	"error_nocol" =>						"Već Ažuriram Kolekciju!",
	"error_dupkey" =>						"Ključ '%s' već koristi '%s'",
	"error_dlpfail" =>						"Nešto je pošlo po zlu pri proveri napretka preuzimanja!",
	"error_refreshfail" =>					"Osvežavanje Podkasta Neuspešno",
	"error_trfailed" =>						"Neuspešan Transfer Plejliste",
	"error_trackexists" =>					"Ta pesma već postoji u kolekciji",
	"error_nosearchnow" =>					"Ne mogu da pretražujem dok se ažurira kolekcija",
	"label_backupcreated" =>				"Backup Kreiran",
	"label_sleepon" =>						"Tajmer za Spavanje Omogućen",
	"label_addedtocol" =>					"Dodana pesma u Kolekciju",
	"label_addedtosw" =>					"Dodana pesma u Govorni Sadržaj",
	"label_addedradio" =>					"Dodano u Vaše Radio Stanice",
	"label_updatedone" =>					"Kolekcija Muzike Ažurirana",
	"label_addingalbum" =>					"Dodavanje Albuma u Kolekciju",
	"error_truncated" =>					"Istorija pretraživača je skraćena - umetnik ne može biti prikazan",
	"error_noplayer" =>						"Nije moguće dobiti odgovor od plejera!",
	"label_preparing" =>					"Priprema. Molimo Sačekajte Dok RompÐ¯ Kalkuliše...",
	"label_scanningf" =>					"Skeniranje Foldera %s",
	"label_fremaining" =>					"%s foldera preostalo",
	"label_scanningp" =>					"Skeniranje Plejliste %s",
	"importer_status" =>					"Završeno %s od %s. Prošlo %s, Preostalo %s",
	"label_playcount" =>					"Broj Puštanja",
	"label_lfm_playcount" =>				"Last.FM Broj Puštanja",
	"label_norecdata" =>					"Kada RompÐ¯ sakupi neke podatke, prikazaće preporuke ovde. Pustite neku muziku!",
	"label_dailymixdesc" =>					"Plejlista samo za vas, mešavina pesama koje poznajete i nove muzike koju biste mogli voleti. Pokretano od %s",
	"label_luckydipdesc" =>					"Radio stanica samo za vas, pušta širi spektar muzike od umetnika koje poznajete i umetnika koje još ne volite. Pokretano od %s",
	"label_goonlogin" =>					"Prijavite se na Last.FM i počnite sa skroblovanjem. RompÐ¯ će vas tada obradovati novom muzikom koju ćete voleti!",
	"label_nospotify" =>					"Koristite Mopidy sa Spotify, Youtube Music, ili Qobuz pretplatom tako da vas RompÐ¯ može obradovati novom muzikom koju ćete voleti!",
	"label_spotimixdesc" =>					"Radio stanica predloga zasnovanih na vašem nedavnom slušanju. Pokretano od RompÐ¯ i Spotify",
	"label_spotiswimdesc" =>				"Skeniranje prostranstva Spotify-a. Pokretano od RompÐ¯ i Spotify",
	"label_opmlexp" =>						"OPML Izvoz",
	"button_opmlexp" =>						"Izvezi Podkaste kao OPML",
	"button_selectall" =>					"Odaberi Sve",
	"button_selectnone" =>					"Odaberi Nijedan",
	"button_import" =>						"Uvezi Odabrane",
	// NOTE: Sunday MUST be first
	"label_daylabels" => array("Nedelja", "Ponedeljak", "Utorak", "Sreda", "Četvrtak", "Petak", "Subota"),
	"label_alarm_play_specific" =>			"Pusti Ovu Stavku :",
	"label_alarm_to_play" =>				"Ubaci Stavku Ovde",
	"label_alarm_to_play_click" =>			"Kliknite da Odaberete Stavku za Puštanje",
	"label_every_day" =>					"Svaki Dan",
	"label_every_wday" =>					"Svaki Radni Dan",
	"label_every_wend" =>					"Svaki Vikend",
	"label_new_alarm" =>					"Napravi Novi Alarm...",
	"label_delete_alarm" =>					"Obriši Ovaj Alarm",
	"config_hidesearcher" =>				"Sakrij Panel Pretrage",
	"label_refreshinprogress" =>			"Podkasti se već osvežavaju. Pokušajte ponovo kasnije",
	"button_addtoplaylist" =>				"Dodaj u Sačuvanu Plejlistu",
	"config_snapcast" =>					"Snapcast",
	"config_snapcast_server" =>				"Snapcast Server",
	"config_snapcast_port" =>				"TCP Port",
	"config_snapcast_http" =>				"HTTP Port",
	"snapcast_notthere" =>					"Nije moguće kontaktirati Snapcast server",
	"snapcast_group" =>						"Grupa ",
	"snapcast_changegroup" =>				"Promeni Grupu",
	"snapcast_latency" =>					"Kašnjenje ",
	"snapcast_setlatency" =>				"Postavi Kašnjenje",
	"snapcast_notconnected" =>				"(Nije Povezan)",
	"label_lastfm_mix_7day" =>				"Last.FM Dnevni Miks",
	"label_lastfm_mix_1month" =>			"Last.FM Mesečni Miks",
	"label_lastfm_mix_12month" =>			"Last.FM Godišnji Miks",
	"label_lastfm_mix_overall" =>			"Last.FM Sveukupni Miks",
	"label_lastfm_dip_7day" =>				"Last.FM Preporučuje",
	"label_lastfm_dip_1month" =>			"Last.FM Sreća",
	"label_lastfm_dip_12month" =>			"Last.FM Pregled Godine",
	"label_lastfm_dip_overall" =>			"Last.FM Nostalgija",
	"config_alarm_stopafter" =>				"Zaustavi Nakon (min)",
	"label_move_to_audiobooks" =>			"Prebaci u Govorni Sadržaj",
	"label_move_to_collection" =>			"Prebaci u Kolekciju Muzike",
	"label_removealbum" =>					"Ukloni Album iz Kolekcije",
	"label_subbed_podcasts" =>				"Pretplaćeni Podkasti",
	"podcast_tooltip_unlistened" =>			"Označi kao Neodslušano",
	"label_addtoqueue" =>					"Dodaj u Red za Puštanje",
	"label_resetresume" =>					"Resetuj Poziciju Nastavka",
	"label_sameascollection" =>				"Isto kao Kolekcija",
	"label_duration_seconds" =>				"Trajanje (sekunde)",
	"label_year" =>							"Godina",
	"label_is" =>							"je",
	"label_is_not" =>						"nije",
	"label_contains" =>						"sadrži",
	"label_does_not_contain" =>				"ne sadrži",
	"label_exists" =>						"postoji",
	"label_lessthan" =>						"je manje od",
	"label_equals" =>						"jednako je",
	"label_greaterthan" =>					"je veće od",
	"label_any_rule" =>						"Pesme moraju odgovarati bar jednom pravilu",
	"label_all_rules" =>					"Pesme moraju odgovarati svim pravilima",
	"label_choose_one" =>					"Odaberite Jedno...",
	"error_norules" =>						"Morate kreirati neka pravila",
	"label_ruleoptions" =>					"Opcije Pravila",
	"label_genres" =>						"Žanrovi",
	"label_createcustom" =>					"Kreiraj Prilagođenu Radio Stanicu",
	"label_edit" =>							"Uredi",
	"label_dayssince" =>					"Dana od Poslednjeg Puštanja",
	"label_disc" =>							"Broj Diska",
	"label_tracktitle" =>					"Naslov Pesme",
	"label_albumtitle" =>					"Naslov Albuma",
	"label_tracknumber" =>					"Broj Pesme",
	"config_use_original_releasedate" =>	"Koristi Originalni Datum Izdavanja za Datum Albuma, ako postoji",
	"label_cantataimporter" =>				"Uvezi Ocene iz Cantata",
	"podcast_writetags" =>					"Piši ID3 Oznake u Preuzete Fajlove",
	"label_youtubedl" =>					"Preuzmi Audio",
	"label_youtubedl_all" =>				"Preuzmi Sve Youtube Pesme",
	"error_playergone" =>					"Plejer '%s' je prestao da odgovara!",
	"label_collinfo" =>						"Informacije o Kolekciji",
	"label_incoll" =>						"Ova pesma je u Kolekciji Muzike",
	"label_notincoll" =>					"Ova pesma nije u Kolekciji Muzike. Kliknite da je dodate",
	"label_image_search" =>					'Potreban vam je Brave Search API ključ da biste koristili Brave Search. Molimo pročitajte dokumentaciju.',
	"config_hidemastervolume" =>			'Koristi Snapcast Jačinu kao Glavnu Kontrolu Jačine',
	"setup_mopidy_scan" =>					'Dozvoli RompR-u da pokrene mopidy local scan pri kreiranju Kolekcije Muzike',
	"setup_mopidy_scan_title" =>			'Mopidy Specijalne Opcije',
	"label_upnext" =>						'Sledeće',
	// "config_consumeworkaround" =>			'Zaobiđi Mopidy Consume Bug (Prvo Pročitaj Dokumentaciju)',
	// "warn_consumearound" =>					'Molimo ONEMOGUĆITE consume pre omogućavanja ove opcije',
	// "msg_consumearound" =>					'Pročitajte Dokumentaciju o ovoj opciji. Morate pokretati romonitor da bi radila',
	"podcast_display_nud" =>				'Novo, Neodslušano i Preuzeto',
	"label_usetrackimages" =>				'Skeniraj svaku pesmu za sliku',
	"label_unusetrackimages" =>				'Ne skeniraj svaku pesmu za sliku',
	"config_audiobook_tags" =>				'Postavi pesmu kao Govorni Sadržaj pri dodavanju oznaka',
	"label_random_order" => 				'Nasumični Redosled',
	"label_remove_all" => 					'Ukloni Sve',
	"manage_bgs" =>							'Upravljaj Pozadinskim Slikama',
	"label_bg_global" =>					'Koristi u Svim Pretraživačima',
	"label_bg_only" =>						'Samo za Ovaj Pretraživač',
	"label_playfromhere" =>					'Pusti Odavde',
	"config_browserid" =>					'ID Pretraživača',
	"button_clearwishlist" =>				'Obriši Listu Želja',
	"label_mfyc" =>							'Muzika iz Vaše Kolekcije',
	"label_mfe" =>							'Muzika Odsvuda',
	"label_playqueue" =>					'Red za Puštanje',
	"label_numplays" =>						'%s Puštanja',
	"button_bookmarks" =>					'Dodaj Bookmark',
	"label_remcur" =>						'Ukloni Trenutnu Sliku',
	"button_nextbg" => 						'Sledeća Pozadinska Slika',
	"button_delbg" => 						'Obriši Trenutnu Pozadinsku Sliku',
	"label_name" =>							'Ime',
	"play_even_if_playing" =>				'Čak i Ako se Već Pušta',
	"setup_mpd_special"	=>					'MPD Specijalne Opcije',
	"label_ui_defaults" =>					'Podrazumevano',
	"button_save_defaults" =>				'Sačuvaj kao Podrazumevano za Sve Pretraživače',
	"label_recommenddesc" =>				'Radio Stanica preporuka zasnovanih na vašem slušanju. Pokretano od %s',
	"label_rmixdesc" =>						'Radio Stanica muzike umetnika koje volite i umetnika poput njih. Pokretano od %s',
	"config_stupid_round_corners" =>		'Padding na dnu ekrana (da pomogne na telefonima sa okruglim uglovima ili kontrolama koje smetaju)',
	"config_clearfirst" =>					'Isprazni Red za Puštanje pre početka',
	"label_classicalrules" =>				'Pravila Sortiranja Klasične Muzike',
	"config_classicalrules" =>				'Koristi Različita Pravila za Sortiranje Klasične Muzike',
	"config_sortbyartist" =>				"Koristi Umetnika Pesme kao Umetnika za Sortiranje",
	"config_sortbycomposer" =>				"Koristi Kompozitora kao Umetnika za Sortiranje",
	"label_classicalgenre" =>				"Detektuj Klasičnu Muziku Koristeći Žanr(ove)",
	"label_classicalfolder" =>				"Detektuj Klasičnu Muziku po Putanji Foldera",
	"label_showallresults" =>				"Prikaži Sve Pesme",
	"label_bythisartist" =>					"Od Ovog Umetnika iz Vaše Kolekcije",
	"label_generic_error" =>				"Nešto je pošlo po zlu",
	"label_genrebyartist" =>				"Žanr (po Umetniku)",
	"label_ratingbyartist" =>				"Ocena (po Umetniku)",
	"label_tagbyartist" =>					"Oznaka (po Umetniku)",
	"label_playtaggedwith" =>				'Pusti Pesme Označene sa "%s"',
	"config_headerbar" =>					'Pozicija Trake sa Ikonama',
	"label_interrupt" =>					'Prekini Red za Puštanje',
	"label_notwhilestopped" =>				'Nije podržano dok je puštanje zaustavljeno',
	"config_brave_credentials" =>			"Brave Search API Podaci",
	"config_audiobook_genres" =>			"Detektuj Govorni Sadržaj po Žanr(ovima)"

	// ----------------------------------------------------
	// Proobaly Unused
	// ----------------------------------------------------
	//"label_smartsetup" =>					"Priprema. Molimo Sačekajte Trenutak....",

]);
?>
