<?php

language::add_translations([

	// The Sources Chooser Button tooltips
	"button_local_music" =>					"音乐集",
	"button_file_browser" =>				"文件浏览器",
	"button_internet_radio" =>				"互联网电台",
	"button_albumart" =>					"专辑封面管理",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" =>				"开关源面板",
	"button_back" =>						"上一个",
	"button_history" =>						"历史",
	"button_forward" =>						"下一个",
	"button_toggleplaylist" =>				"开关播放列表",

	// Tooltips for playlist buttons
	"button_alarm" =>						"闹钟",
	"button_prefs" =>						"RompЯ偏好设置",
	"button_clearplaylist" =>				"清空播放列表",
	"button_loadplaylist" =>				"载入保存的播放列表",
	"button_saveplaylist" =>				"保存播放列表",

	// Tooltips for playback controls
	"button_previous" =>					"上一曲目",
	"button_play" =>						"播放/暂停",
	"button_stop" =>						"停止播放",
	"button_stopafter" =>					"当前曲目后停止播放",
	"button_next" =>						"下一曲目",
	"button_love" =>						"收藏曲目",
	"button_ban" =>							"屏蔽曲目",
	"button_volume" =>						"音量",

	// Configuration menu entries
	"config_theme" =>						"主题",
	"config_hidealbumlist" =>				"隐藏音乐集",
	"config_hidefileslist" =>				"隐藏文件列表",
	"config_hideradio" =>					"隐藏电台",
	"config_hidepodcasts" =>				"隐藏播客",
	"config_hideplaylistslist" =>			"隐藏保存的播放列表",
	"config_hidepluginplaylistslist" =>		"隐藏个性化电台",
	"config_hidebrowser" =>					"隐藏信息面板",
	"config_lastfmlang" =>					"Last.FM和Wikipedia的语言",
	"config_lastfmdefault" =>				"缺省语言(English)",
	"config_lastfminterface" =>				"RompЯ的界面语言",
	"config_lastfmbrowser" =>				"浏览器的缺省语言",
	"config_autoscroll" =>					"自动滚动播放列表到当前曲目",
	"config_autocovers" =>					"自动下载封面",
	"config_musicfolders" =>				"要使用音乐目录下的封面或从文件中获取歌词，请在方框中输入音乐的路径：",
	"config_crossfade" =>					"淡入淡出时长(秒)",
	"config_doubleclick" =>					"双击播放，单击选择",
	"config_singleclick" =>					"单击播放",
	"config_sortbydate" =>					"按日期排序专辑",
	"config_notvabydate" =>					"不要将按日期排序应用到'群星专辑'",
	"config_updateonstart" =>				"启动时更新音乐集",
	"config_updatenow" =>					"立即更新音乐集",
	"config_rescan" =>						"重新完整扫描本地音乐",
	"config_editshortcuts" =>				"编辑快捷键...",
	"config_audiooutputs" =>				"音频输出",
	"config_lastfmusername" =>				"Last.FM用户名",
	"config_loginbutton" =>					"登录",
	"config_scrobbling" =>					"转录曲目到Last.FM",
	"config_noscrobble_audiobook" =>		"不要转录听书曲目",
	"config_noscrobble_podcast" =>			"不要转录播客曲目",
	"config_autocorrect" =>					"使用Last.FM自动修正歌手名称等",
	"config_tagloved" =>					"收藏曲目的标记：",
	"config_fontsize" =>					"字体大小",
	"config_fontname" =>					"字体类型",

	// Various buttons for the playlist dropdowns
	"button_save" =>						"保存",

	// General Labels and buttons in the main layout
	"label_lastfm" =>						"Last.FM",
	"button_searchmusic" =>					"搜索音乐",
	"label_yourradio" =>					"你的电台",
	"label_podcasts" =>						"播客",
	"label_somafm" =>						"Soma FM",
	"label_emptyinfo" =>					"这是信息面板，当你播放音乐的时候有趣的信息将显示在这里",
	"button_playlistcontrols" =>			"播放列表控制",
	"button_random" =>						"乱序播放",
	"button_crossfade" =>					"淡入淡出",
	"button_repeat" =>						"重复播放",
	"button_consume" =>						"消耗模式",
	"label_yes" =>							"是",
	"label_no" =>							"否",
	"label_updating" =>						"正在更新音乐集",
	"label_update_error" =>					"生成音乐集失败。",
	"label_playlisterror" =>				"获取播放列表时发生错误！",
	"button_OK" =>							"确认",
	"button_cancel" =>						"取消",
	"error_playlistname" =>					"播放列表的名称中不能包含斜杠",
	"label_savedpl" =>						"播放列表另存为%s",

	// Search Forms
	"label_searchfor" =>					"搜索",
	"label_searching" =>					"搜索中...",
	"label_searchresults" =>				"搜索结果",

	// General multipurpose labels
	"label_tracks" =>						"曲目",
	"label_albums" =>						"专辑",
	"label_artists" =>						"歌手",
	"label_track" =>						"曲目",
	"label_album" =>						"专辑",
	"label_artist" =>						"歌手",
	"label_anything" =>						"其他",
	"label_genre" =>						"类型",
	"label_composer" =>						"作曲",
	"label_performer" =>					"演唱",
	"label_rating" =>						"评级",
	"label_tag" =>							"标签",
	"label_discogs" =>						"Discogs",
	"label_musicbrainz" =>					"Musicbrainz",
	"label_wikipedia" =>					"Wikipedia",
	"label_general_error" =>				"出现错误，请刷新页面并重试",
	"label_days" =>							"天",
	"label_noalbums" =>						"未找到专辑",
	"label_duration" =>						"时长",
	"label_playererror" =>					"播放器错误",
	"button_playradio" =>					"播放",

	// Playlist and Now Playing
	"label_notforradio" =>					"不支持无线电流",
	"label_incoming" =>						"接收中...",
	"label_addingtracks" =>					"正在添加曲目",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" =>							"来自",
	"label_on" =>							"专辑",
	// Now playing - 1:45 of 6:50
	"label_of" =>							"/",

	// Podcasts
	"podcast_entrybox" =>					"订阅到RSS提要：",
	// Podcast tooltips
	"podcast_delete" =>						"删除此播客",
	"podcast_configure" =>					"配置此播客",
	"podcast_refresh" =>					"刷新此播客",
	"podcast_download_all" =>				"下载此播客的所有片段",
	"podcast_mark_all" =>					"标记所有片段为已听",
	"podcast_undelete" =>					"取消删除已删除的片段",
	"podcast_removedownloaded" =>			"移除已经下载的文件",
	// Podcast display options
	"podcast_display" =>					"显示",
	"podcast_display_all" =>				"所有",
	"podcast_display_onlynew" =>			"新的",
	"podcast_display_unlistened" =>			"新的和未听过的",
	"podcast_display_downloadnew" =>		"新的和已下载的",
	"podcast_display_downloaded" =>			"已下载的",
	// Podcast refresh options
	"podcast_refresh" =>					"刷新",
	"podcast_refresh_never" =>				"手动",
	"podcast_refresh_hourly" =>				"每小时",
	"podcast_refresh_daily" =>				"每天",
	"podcast_refresh_weekly" =>				"每周",
	"podcast_refresh_monthly" =>			"每月",
	// Podcast auto expire
	"podcast_expire" =>						"保存片段时长",
	"podcast_expire_tooltip" =>				"所有超过此值的片段都会从列表中移除。对这个选项的修改将在下一次刷新播客的时候生效",
	"podcast_expire_never" =>				"永久",
	"podcast_expire_week" =>				"一周",
	"podcast_expire_2week" =>				"两周",
	"podcast_expire_month" =>				"一个月",
	"podcast_expire_2month" =>				"两个月",
	"podcast_expire_6month" =>				"半年",
	"podcast_expire_year" =>				"一年",
	// Podcast number to keep
	"podcast_keep" =>						"保留的数量",
	"podcast_keep_tooltip" =>				"列表将只显示这个数量的片段，对这个选项的修改将在下一次刷新播客的时候生效",
	"podcast_keep_0" =>						"无限",
	// Podcast other options
	"podcast_keep_downloaded" =>			"保留所有已下载的片段",
	"podcast_kd_tooltip" =>					"启用这个选项来保留所有已下载的片段。上面的两个选项将只会应用到还未下载的片段。",
	"podcast_tooltip_new" =>				"这是一个新片段",
	"podcast_tooltip_notnew" =>				"这个片段不是新的但是没听过的",
	"podcast_tooltip_downloaded" =>			"这个片段已经下载，点击以移除下载的文件。",
	"podcast_tooltip_download" =>			"下载这个片段到你的电脑",
	"podcast_tooltip_mark" =>				"标记为已听",
	"podcast_tooltip_delepisode" =>			"删除这个片段",
	// eg 2 days left to listen

	// Soma FM Chooser Panel
	"label_soma_beg" =>						"如果你喜欢这些电台，请考虑支持Soma.FM",

	// Your radio stations
	"label_radioinput" =>					"输入一个URL",

	//Album Art Manager
	"albumart_title" =>						"专辑封面",
	"albumart_getmissing" =>				"获取缺失的封面",
	"albumart_showall" =>					"显示所有封面",
	"albumart_instructions" =>				"点击一个封面来进行修改，或从硬盘或者其他浏览器窗口拖拽一个图片来修改",
	"albumart_onlyempty" =>					"只显示没有封面的专辑",
	"albumart_allartists" =>				"所有歌手",
	"albumart_googlesearch" =>				"Bing搜索",
	"albumart_local" =>						"本地图片",
	"albumart_upload" =>					"文件上传",
	"albumart_uploadbutton" =>				"上传",
	"albumart_newtab" =>					"在新标签页用Google搜索",
	"albumart_dragdrop" =>					"你可以从硬盘或其他浏览器（大多数浏览器）窗口直接拖拽图片到图片上",
	"albumart_showmore" =>					"显示更多结果",
	"albumart_googleproblem" =>				"Bing提示出现问题",
	"albumart_getthese" =>					"获取这些封面",
	"albumart_nocovercount" =>				"缺少封面的专辑",
	"albumart_getting" =>					"获取中",

	// Setup page (rompr/?setup)
	"setup_connectfail" =>					"Rompr不能连接到mpd或mopidy服务器",
	"setup_connecterror" =>					"与mpd或mopidy服务器通信时发生错误：",
	"setup_request" =>						"你请求访问设置页面",
	"setup_addressnote" =>					"注意：localhost在这个上下文中表示运行网页服务器的那台计算机：",
	"setup_port" =>							"端口",
	"setup_advanced" =>						"高级选项",
	"setup_password" =>						"密码",
	"setup_unixsocket" =>					"UNIX-domain socket",
	"setup_websocket_port" =>				"Websocket端口",

	// Intro Window

	// Last.FM
	"lastfm_loginwindow" =>					"登录到Last.FM",
	"lastfm_login1" =>						"请点击下面的链接在新标签页打开Last.FM站点。按要求输入你的Last.FM登录信息然后允许RompЯ访问你的账户",
	"lastfm_login2" =>						"完成后可以关闭新标签页但是不要关闭本标签页！",
	"lastfm_loginbutton" =>					"点击此处进行登录",
	"lastfm_login3" =>						"一旦登录到Last.FM，点击OK按钮来完成整个流程。",
	"lastfm_loginfailed" =>					"登录Last.FM失败",
	"label_loved" =>						"已收藏",
	"label_lovefailed" =>					"收藏失败",
	"label_unloved" =>						"取消收藏",
	"label_unlovefailed" =>					"移除收藏失败",
	"label_scrobblefailed" =>				"抓取失败",

	// Info Panel
	"info_gettinginfo" =>					"获取信息中...",
	"info_newtab" =>						"在新标签页浏览",

	// File Info panel
	"button_fileinfo" =>					"信息面板（集合信息）",
	"info_file" =>							"文件",
	"info_from_beets" =>					"(源自 beets 服务器)",
	"info_format" =>						"格式：",
	"info_bitrate" =>						"比特率：",
	"info_samplerate" =>					"采样率：",
	"info_mono" =>							"单声道",
	"info_stereo" =>						"立体声",
	"info_channels" =>						"通道",
	"info_date" =>							"日期：",
	"info_genre" =>							"类型：",
	"info_performers" =>					"演唱：",
	"info_composers" =>						"作曲：",
	"info_comment" =>						"备注：",
	"info_label" =>							"标签：",
	"info_disctitle" =>						"唱片标题：",
	"info_encoder" =>						"编码：",
	"info_year" =>							"年份：",

	// Last.FM Info Panel
	"button_infolastfm" =>					"信息面板（Last.FM）",
	"label_notrackinfo" =>					"未找到此曲目相关的信息",
	"label_noalbuminfo" =>					"未找到此专辑相关的信息",
	"label_noartistinfo" =>					"未找到此歌手相关的信息",
	"lastfm_listeners" =>					"听众数：",
	"lastfm_plays" =>						"播放数：",
	"lastfm_yourplays" =>					"你的播放数:",
	"lastfm_toptags" =>						"顶部标签:",
	"lastfm_addtags" =>						"添加标签",
	"lastfm_addtagslabel" =>				"添加标签，逗号分割",
	"button_add" =>							"添加",
	"lastfm_yourtags" =>					"你的标签：",
	"lastfm_simar" =>						"类似歌手",
	"lastfm_removetag" =>					"移除标签",
	"lastfm_releasedate" =>					"发行日期",
	"lastfm_viewtrack" =>					"在Last.FM上查看曲目",
	"lastfm_tagerror" =>					"修改标签失败",
	"lastfm_loved" =>						"收藏",
	"lastfm_lovethis" =>					"收藏此曲目",
	"lastfm_unlove" =>						"取消收藏此曲目",
	"lastfm_notfound" =>					"未找到%s",

	// Lyrics info panel
	"button_lyrics" =>						"信息面板（歌词）",
	"lyrics_lyrics" =>						"歌词",
	"lyrics_nonefound" =>					"未找到歌词",
	"lyrics_info" =>						"要使用歌词查看器，您需要确保您的本地文件标记有歌词",
	"lyrics_nopath" =>						"要使用歌词查看器，您需要确保本地文件标记有歌词，并在首选项中设置音乐路径",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" =>							"年份",
	"title_title" =>						"标题",
	"title_type" =>							"类型",
	"title_label" =>						"标签",
	"label_pages" =>						"页",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" =>					"公司",
	"discogs_personnel" =>					"成员",
	"discogs_videos" =>						"视频",
	"discogs_styles" =>						"风格",
	"discogs_genres" =>						"类型",
	"discogs_tracklisting" =>				"曲目列表",
	"discogs_realname" =>					"真实名称：",
	"discogs_aliases" =>					"别名：",
	"discogs_alsoknown" =>					"另称为：",
	"discogs_external" =>					"扩展链接",
	"discogs_bandmembers" =>				"乐队成员",
	"discogs_memberof" =>					"属于",
	"discogs_discography" =>				"%s DISCOGRAPHY",

	// Discogs info panel
	"button_discogs" =>						"信息面板（Discogs）",
	"discogs_error" =>						"Discogs上未找到相关信息",
	"discogs_nonsense" =>					"无法从Discogs获取到有用的响应",
	"discogs_noalbum" =>					"无法在Discogs找到这个专辑",
	"discogs_notrack" =>					"无法在Discogs上找个这个曲目",

	// Musicbrainz info panel
	"button_musicbrainz" =>					"信息面板（Musicbrainz）",
	"musicbrainz_error" =>					"无法从MusicBrainz获取到响应",
	"musicbrainz_contacterror" =>			"访问Musicbrainz时发生错误",
	"musicbrainz_noartist" =>				"无法在Musicbrainz上找到这个歌手",
	"musicbrainz_noalbum" =>				"无法在Musicbrainz上找到这个专辑",
	"musicbrainz_notrack" =>				"无法在Musicbrainz上找到这个曲目",
	"musicbrainz_noinfo" =>					"无法在Musicbrainz上找到相关信息",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" =>					"Present",
	"musicbrainz_origin" =>					"ORIGIN",
	"musicbrainz_active" =>					"ACTIVE",
	"musicbrainz_rating" =>					"评价",
	"musicbrainz_notes" =>					"备注",
	"musicbrainz_tags" =>					"标签",
	"musicbrainz_externaldiscography" =>	"Discography (%s)",
	"musicbrainz_officalhomepage" =>		"官方主页 (%s)",
	"musicbrainz_fansite" =>				"粉丝站点 (%s)",
	"musicbrainz_lyrics" =>					"歌词 (%s)",
	"musicbrainz_social" =>					"社交网络 (%s)",
	"musicbrainz_streaming" =>				"免费的流 (%s)",
	"musicbrainz_microblog" =>				"Microblog",
	"musicbrainz_review" =>					"评论 (%s)",
	"musicbrainz_purchase" =>				"购买 (%s)",
	"musicbrainz_novotes" =>				"（没有投票）",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" =>					"%s/5 源于 %s 投票",
	"musicbrainz_appears" =>				"这个曲目出现在",
	"musicbrainz_credits" =>				"声望",
	"musicbrainz_status" =>					"状态",
	"musicbrainz_date" =>					"日期",
	"musicbrainz_country" =>				"国家",
	"musicbrainz_disc" =>					"唱片",
	"musicbrainz_album_releases" =>			"专辑发行",

	// SoundCloud info panel
	"button_soundcloud" =>					"信息面板（SoundCloud）",
	"soundcloud_trackinfo" =>				"曲目信息",
	"soundcloud_plays" =>					"播放次数",
	"soundcloud_downloads" =>				"下载次数",
	"soundcloud_faves" =>					"收藏次数",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" =>					"状态",
	"soundcloud_license" =>					"许可",
	"soundcloud_buy" =>						"购买曲目",
	"soundcloud_view" =>					"在SoundCloud上查看",
	"soundcloud_user" =>					"SoundCloud用户",
	"soundcloud_fullname" =>				"姓名",
	"soundcloud_Country" =>					"国家",
	"soundcloud_city" =>					"城市",
	"soundcloud_website" =>					"访问网站",
	"soundcloud_not" =>						"此面板只展示SoundCloud上关于音乐的信息",

	// Wikipedia Info Panel
	"button_wikipedia" =>					"信息面板（Wikipedia）",
	"wiki_nothing" =>						"未从Wikipedia上获取到任何信息",
	"wiki_fail" =>							"Wikipedia上未找到任何关于'%s'的信息",
	"wiki_suggest" =>						"Wikipedia上未能找到任何匹配'%s'的页面",
	"wiki_suggest2" =>						"以下是一些建议",

	// Keybindings editor
	"title_keybindings" =>					"快捷键",
	"button_volup" =>						"提高音量",
	"button_voldown" =>						"降低音量",

	// Extras for mobile version

	// Various Plugins, Rating, and Tagging
	"stars" =>								"星",
	"star" =>								"星",
	"label_tags" =>							"标签",
	"label_wishlist" =>						"心愿单",
	"label_viewwishlist" =>					"查看你的心愿单",
	"label_addtow" =>						"已加入到心愿单",
	"config_synctags" =>					"与Last.FM保持标签同步",
	"config_loveis" =>						"Last.FM Love 表示",
	"playlist_xstar" =>						"%s 或更多星",
	"button_about" =>						"关于RompЯ",
	"label_notfound" =>						"曲目未找到",
	// Eg + 3 more

	//New in 0.52
	"config_alarm_ramp" =>					"淡入",

	// New in 0.60
	"spotify_error" =>						"Spotify没有响应",
	"spotify_noinfo" =>						"无法从 Spotify 获取到信息",
	"button_infospotify" =>					"信息面板（Spotify）",
	"config_icontheme" =>					"图标",
	"label_radio" =>						"电台",
	"label_pop" =>							"流行度",
	"label_albumsby" =>						"歌手的专辑",
	"label_singleartistradio" =>			"歌手的曲目",
	"label_mostplayed" =>					"收藏的曲目",
	"label_neverplayed" =>					"从未播放的曲目",
	"label_radio_fartist" =>				"收藏的歌手",
	"label_pluginplaylists" =>				"个性化电台",
	"label_recentlyadded_random" =>			"最近新增的曲目（随机）",
	"label_recentlyadded_byalbum" =>		"最近新增的专辑",
	"setup_mpd" =>							"MPD/Mopidy设置",
	"settings_appearance" =>				"外观",
	"settings_panels" =>					"面板",
	"settings_language" =>					"语言",
	"settings_interface" =>					"界面",
	"label_charts" =>						"Top 40",
	"button_subscribe" =>					"订阅",
	"config_composergenre" =>				" .. 仅当类型为：",
	"config_displaycomposer" =>				"在正在播放中显示作曲者/演唱者",
	"label_radio_mix" =>					"收藏的歌手和关联歌手",
	"label_gotnotracks" =>					"未找到任何曲目",
	"config_artistfirst" =>					"集合前列的歌手",
	"config_nosortprefixes" =>				"排序歌手的时候忽略这些前缀",
	"button_skipforward" =>					"快进",
	"button_skipbackward" =>				"快退",
	"config_snoozetime" =>					"睡眠时间（分钟）",
	"config_ramptime" =>					"淡入淡出时间（秒）",
	"button_rateone" =>						"打 1 星",
	"button_ratetwo" =>						"打 2 星",
	"button_ratethree" =>					"打 3 星",
	"button_ratefour" =>					"打 4 星",
	"button_ratefive" =>					"打 5 星",
	"button_updatecollection" =>			"更新音乐集",
	"label_favealbums" =>					"收藏的专辑",
	"button_nextsource" =>					"信息面板 - Cycle Source",
	"button_infopanel" =>					"信息面板",
	"config_coversize" =>					"封面尺寸",
	"podcast_sortmode" =>					"排序规则",
	"podcast_newestfirst" =>				"最新的在前",
	"podcast_oldestfirst" =>				"最老的在前",
	"podcast_hidedescriptions" =>			"隐藏描述",

	// New in 0.64/0.65/0.70
	"label_metabackup" =>					"元数据备份",
	"button_backup" =>						"创建备份",
	"button_restore" =>						"还原备份",
	"button_collectioncontrols" =>			"音乐集排序控制",
	"button_createplaylist" =>				"创建播放列表",
	"label_renameplaylist" =>				"重命名播放列表",
	"button_plugins" =>						"各种好东西",
	"label_filename" =>						"文件名",
	"label_resultscollection" =>			"集合",
	"label_resultstree" =>					"词典树",
	"label_displayresultsas" =>				"显示音乐搜索记录为：",
	"label_files" =>						"文件",
	"label_albumartist" =>					"专辑歌手",
	"config_collectionfolders" =>			"构建集合的来源：",
	"button_videos" =>						"关联视频",
	"label_allrandom" =>					"随机所有曲目",
	"label_randomalbums" =>					"随机所有专辑",
	"config_background" =>					"背景图片",
	"lastfm_error" =>						"无法在Last.FM上找到信息",
	"config_skin" =>						"皮肤",

	// New in 0.71
	"label_albumsbyartist" =>				"专辑（按歌手）",
	"config_wheelspeed" =>					"鼠标滚轮滚动速率",

	"label_radio_recommend" =>				"推荐基于此 %s",
	"label_amendalbum" =>					"修订专辑细节",
	"label_radio_recommended" =>			"为你推荐",

	//CHANGED in 0.60
	"config_country" =>						"国家（用于 Spotify ）",
	"setup_labeladdresses" =>				"如果出现连接异常，请尝试使用IP地址来替代'localhost'",
	"setup_ipaddress" =>					"Mopidy 或 mpd 服务器",

	"config_cdplayermode" =>				"CD播放器模式（不排队曲目，从选择的曲目开始播放专辑）",

	"label_recentlyplayed" =>				"最近播放的曲目",
	"label_simar_radio" =>					"相似歌手",

	"label_tradsearch" =>					"高级搜索",

	"played_never" =>						"此曲目从未被播放",
	"played_once" =>						"此曲目被播放过一次",
	"played_twice" =>						"此曲目被播放过两次",
	"played_n" =>							"此曲目被播放过%s次",
	"played_last" =>						"最后一次播放于%s",
	"added_on" =>							"加入集合于%s",
	"button_infoyou" =>						"The Discoverator",
	"discover_now" =>						"曲目推荐基于 %s",
	"config_discovembobulate" =>			"启动时开启 Discoverator",
	"label_spotify_mix" =>					"Spotify 每周 Mix",
	"label_spotify_dj" =>					"Spotify Swim",
	"label_spottery_lottery" =>				"Spotify 惊喜！",
	"label_dailymix" =>						"你的每日 Mix",
	"label_luckydip" =>						"你的抽彩",
	"label_startshere" =>					"你的发现始于此处",
	"label_getspotify" =>					"上线以开启发现之旅",
	"because_liked" =>						"你喜欢 %s，因此你可能喜欢：",
	"because_listened" =>					"类似于 %s:",
	"albumart_findsmall" =>					"查找小图片",
	"button_sleep" =>						"睡眠计时器（Time为倒计时时长，Fade为淡出时长，单位：分钟）",
	"label_tuneinradio" =>					"TuneIn Radio Directory",
	"label_generalsettings" =>				"常规设置",
	"config_beetsserver" =>					"Beets 服务器的地址（IP地址:端口）",
	"config_players" =>						"播放器",
	"button_edit_players" =>				"编辑播放器",

	"label_play_all" =>						"播放歌手的所有曲目",
	"label_last_played" =>					"最后播放：",
	"label_station_website" =>				"电台网站",

	"label_play_whole_album" =>				"播放整张专辑",
	"label_from_collection" =>				"播放集合中所有曲目",
	"label_with_ratings" =>					"只播放有评分的曲目",
	"label_with_tags" =>					"只播放有标签的曲目",
	"label_with_tagandrat" =>				"只播放带有标签和评分的曲目",
	"label_with_tagorrat" =>				"只播放带有标签或评分的曲目",
	"config_google_credentials" =>			"Bing API 凭证",
	"config_read_the_docs" =>				"请阅读文档",
	"label_dateadded" =>					"加入的日期",
	"label_radiostation" =>					"电台",
	"label_opmlimporter" =>					"OPML导入器",
	"config_playerintitlebar" =>			"在标题栏显示播放器名称",
	"label_communityradio" =>				"社区电台浏览器",
	"label_volume" =>						"音量",
	"button_debuginfo" =>					"调试信息",
	"config_podcast_defaults" =>			"作为新播客的缺省选项",
	"config_marknewasunlistened" =>			"在刷新之前标记新的片段为未听",
	"config_albumartinplaylist" =>			"在播放队列显示专辑封面",
	"label_resume" =>						"继续播放",
	"label_sortby" =>						"排序方式",
	"label_then" =>							"然后",
	"label_publisher" =>					"发现",
	"label_category" =>						"类别",
	"label_new_episodes" =>					"新片段",
	"label_unlistened_episodes" =>			"未听的片段",
	"label_loading" =>						"加载中...",
	"label_choosefile" =>					"选择一个文件",
	"label_choosefiles" =>					"选择一或多个文件",
	"label_changevery" =>					"修改所有",
	"label_albumstolistento" =>				"要收听的专辑",
	"no_albumtolistento" =>					"你可以从信息面板添加任意 Spotify 专辑到这个列表中，回头再回来检查列表。",
	"label_addedtolistenlater" =>			"已加入要收听的专辑",
	"label_all_time" =>						"整个结合",
	"label_today" =>						"今日添加的",
	"label_thisweek" =>						"本周添加的",
	"label_thismonth" =>					"本月添加的",
	"label_thisyear" =>						"今年添加的",
	"label_searchtrack" =>					"搜索这个曲目",
	"label_removefromwl" =>					"从心愿单移除曲目",
	"label_gethelp" =>						"点击获取帮助",
	"label_podcastcontrols" =>				"播客搜索和排序控制",
	"label_closepanel" =>					"关闭这个面板",
	"label_hidepanel" =>					"隐藏这个面板",
	"label_removefromplaylist" =>			"从播放列表移除",
	"label_addtolistenlater" =>				"添加专辑到稍后收听",
	"label_removefromlistenlater" =>		"从稍后收听中移除专辑",
	"label_addtocollection" =>				"添加专辑到音乐集",
	"label_addtoradio" =>					"添加到你的电台",
	"button_logout" =>						"登出",
	"label_transferplaylist" =>				"转移播放队列到新的播放器？",
	"label_yes" =>							"是",
	"label_no" =>							"否",
	"podcast_refresh_all" =>				"刷新所有播客",
	"label_global_controls" =>				"全局控制",
	"label_topleft" =>						"左上",
	"label_topright" =>						"右上",
	"label_bottomleft" =>					"左下",
	"label_bottomright" =>					"右下",
	"label_centre" =>						"中心",
	"label_bottomcentre" =>					"底部中心",
	"label_topcentre" =>					"顶部中心",
	"config_preferlocal" =>					"本地音乐优先于网络来源",
	"config_lastfm_playcounts" =>			"使用 Last.FM 的播放计数",
	"config_sync_lastfm_playcounts" =>		"与 Last.FM 同步播放次数",
	"label_lfm_playcountimporter" =>		"Last.FM 播放计数导入器",
	"label_mustlogintolfm" =>				"你必须登录到 Last.FM 才能使用这个功能",
	"label_lfm_syncing" =>					"正在同步 Last.FM 播放计数",
	"label_lfm_nonew" =>					"在 %s 最后一次导入后没有新的曲目添加到音乐集。",
	"config_smart_chunksize" =>				"显示即将推出的曲目的数量",
	"warning_smart_debug" =>				"警告！启用调试模式运行个人电台可能导致你的浏览器崩溃！",
	"label_unplayabletracks" =>				"不可播放的曲目",
	"label_no_unplayable" =>				"集合中无不可播放的曲目",
	"label_removefromcol" =>				"从集合中移除",
	"label_audiobooks" =>					"听书",
	"config_hideaudiobooks" =>				"隐藏听书",
	"config_audiobook_directory" =>			"包含听书文件的目录",
	"error_imageupload" =>					"上传图片失败",
	"error_toomanyimages" =>				"太多图片或图片文件太大",
	"error_sendingcommands" =>				"发送命令给%s失败",
	"error_cantdeleteplayer" =>				"不能删除正在使用的播放器",
	"error_duplicateplayer" =>				"两个播放器不能同名",
	"error_backupfail" =>					"%s备份失败",
	"error_nogenres" =>						"请选择若干类型",
	"error_collectionupdate" =>				"音乐集更新失败",
	"error_nocol" =>						"已在更新集合！",
	"error_dupkey" =>						"密钥 '%s' 已经被 '%s' 使用",
	"error_dlpfail" =>						"检查下载进度发生错误！",
	"error_refreshfail" =>					"播客刷新失败",
	"error_trfailed" =>						"转移播放列表失败",
	"error_trackexists" =>					"此曲目已经在集合中",
	"error_nosearchnow" =>					"当正在更新集合时不能进行搜索",
	"label_backupcreated" =>				"备份创建完成",
	"label_sleepon" =>						"已启用睡眠计时器",
	"label_addedtocol" =>					"已添加曲目到集合",
	"label_addedtosw" =>					"添加曲目到听书",
	"label_addedradio" =>					"已添加到你的电台",
	"label_updatedone" =>					"音乐集已更新",
	"label_addingalbum" =>					"正在将专辑添加进集合",
	"error_truncated" =>					"浏览器历史已被清空 -- 歌手无法显示",
	"error_noplayer" =>						"无法从播放器获取响应！",
	"label_preparing" =>					"准备中。当RompЯ在计算时请等待...",
	"label_scanningf" =>					"正在扫描目录 %s",
	"label_fremaining" =>					"%s 目录剩余",
	"label_scanningp" =>					"正在扫描播放列表 %s",
	"importer_status" =>					"完成 %s / %s. 已处理 %s, 剩余 %s",
	"label_playcount" =>					"播放计数",
	"label_lfm_playcount" =>				"Last.FM播放计数",
	"label_norecdata" =>					"一旦RompЯ收集到若干数据，它将在这里显示推荐内容。播放一些音乐！",
	"label_dailymixdesc" =>					"专门为你准备的播放列表，混合了你知道的曲目和你可能喜欢的新曲目。由 %s 驱动。",
	"label_luckydipdesc" =>					"你独享的电台，播放你喜欢的和还没喜欢上的歌手各种音乐。由 %s 驱动",
	"label_goonlogin" =>					"登录 Last.FM 并开始抓取。 然后 RompЯ 会用你喜欢的新音乐来让你愉悦！",
	"label_nospotify" =>					"使用 Mopidy 并配套一个 Spotify、 Youtube Music、 或者 Qobuz 订阅， 据此 RompЯ 会用你喜欢的新音乐来让你愉悦！",
	"label_spotimixdesc" =>					"根据你最近的收听情况推荐的一个电台。由 RompЯ 和 Spotify驱动",
	"label_spotiswimdesc" =>				"正在扫描浩瀚的 Spotify。 由 RompЯ 和 Spotify 驱动",
	"label_opmlexp" =>						"OPML导出",
	"button_opmlexp" =>						"将播客到处为OPML",
	"button_selectall" =>					"全选",
	"button_selectnone" =>					"清空选择",
	"button_import" =>						"导入已选",
	"label_onlyspotify" =>					"这个面板只在你可以播放Spotify的情况下才可用",
	// NOTE: Sunday MUST be first
	"label_daylabels" => array("周日", "周一", "周二", "周三", "周四", "周五", "周六"),
	"label_alarm_play_specific" =>			"播放此项目：",
	"label_alarm_to_play" =>				"将项目拖放到此处",
	"label_alarm_to_play_click" =>			"点击来选择需要播放的项目",
	"label_every_day" =>					"每天",
	"label_every_wday" =>					"每工作日",
	"label_every_wend" =>					"每周末",
	"label_new_alarm" =>					"创建新闹钟...",
	"label_delete_alarm" =>					"删除此闹钟",
	"config_hidesearcher" =>				"因此搜索面板",
	"label_refreshinprogress" =>			"播客已在刷新中，请稍后重试",
	"button_addtoplaylist" =>				"添加到保存的播放列表",
	"config_snapcast" =>					"Snapcast",
	"config_snapcast_server" =>				"Snapcast服务器",
	"config_snapcast_port" =>				"TCP端口",
	"config_snapcast_http" =>				"HTTP端口",
	"snapcast_notthere" =>					"无法连接Snapcast服务器",
	"snapcast_group" =>						"分组 ",
	"snapcast_changegroup" =>				"修改分组",
	"snapcast_latency" =>					"延迟 ",
	"snapcast_setlatency" =>				"设置延迟",
	"snapcast_notconnected" =>				"(未连接)",
	"label_lastfm_mix_7day" =>				"Last.FM 每日 Mix",
	"label_lastfm_mix_1month" =>			"Last.FM 每月 Mix",
	"label_lastfm_mix_12month" =>			"Last.FM 每年 Mix",
	"label_lastfm_mix_overall" =>			"Last.FM 所有时间的 Mix",
	"label_lastfm_dip_7day" =>				"Last.FM 推荐",
	"label_lastfm_dip_1month" =>			"Last.FM 抽彩",
	"label_lastfm_dip_12month" =>			"Last.FM 年度回顾",
	"label_lastfm_dip_overall" =>			"Last.FM Nostalgia Trip",
	"config_alarm_stopafter" =>				"多久后停止（分钟）",
	"label_move_to_audiobooks" =>			"移入到听书",
	"label_move_to_collection" =>			"移入到音乐集",
	"label_removealbum" =>					"从集合移除专辑",
	"label_subbed_podcasts" =>				"已订阅播客",
	"podcast_tooltip_unlistened" =>			"标记为未听",
	"label_addtoqueue" =>					"添加到播放队列",
	"label_resetresume" =>					"重置继续播放位置",
	"label_sameascollection" =>				"与集合相同",
	"label_duration_seconds" =>				"时长（秒）",
	"label_year" =>							"年",
	"label_is" =>							"是",
	"label_is_not" =>						"不是",
	"label_contains" =>						"包含",
	"label_does_not_contain" =>				"不包含",
	"label_exists" =>						"存在",
	"label_lessthan" =>						"少于",
	"label_equals" =>						"等于",
	"label_greaterthan" =>					"大于",
	"label_any_rule" =>						"曲目必须至少匹配一个规则",
	"label_all_rules" =>					"曲目必须匹配所有规则",
	"label_choose_one" =>					"选择一首...",
	"error_norules" =>						"你必须创建若干规则",
	"label_ruleoptions" =>					"规则选项",
	"label_genres" =>						"类型",
	"label_createcustom" =>					"创建自定义电台",
	"label_edit" =>							"编辑",
	"label_dayssince" =>					"最后一次播放距今的天数",
	"label_disc" =>							"唱片编号",
	"label_tracktitle" =>					"曲目标题",
	"label_albumtitle" =>					"专辑标题",
	"label_tracknumber" =>					"曲目数量",
	"config_use_original_releasedate" =>	"如果存在，使用原始发行日期作为专辑日期",
	"label_cantataimporter" =>				"从Cantata导入评价",
	"podcast_writetags" =>					"写入ID3标签到下载的文件",
	"label_youtubedl" =>					"下载音频",
	"label_youtubedl_all" =>				"下载所有Youtube曲目",
	"error_playergone" =>					"播放器 '%s' 停止响应！",
	"label_collinfo" =>						"集合信息",
	"label_incoll" =>						"此曲目在音乐集中",
	"label_notincoll" =>					"此曲目不在音乐集中，点击添加",
	"label_image_search" =>					'你需要一个Bing图片搜索API密钥来使用Bing搜索。请阅读相关文档。',
	"config_hidemastervolume" =>			'使用Snapcast音量作为主音量控制',
	"setup_mopidy_scan" =>					'当创建音乐集时允许RompR运行mopidy本地扫描',
	"setup_mopidy_scan_title" =>			'Mopidy特定选项',
	"label_upnext" =>						'向上一个',
	// "config_consumeworkaround" =>			'Work Around Mopidy Consume Bug (Read the Docs First)',
	// "warn_consumearound" =>					'Please DISABLE consume before enabling this option',
	// "msg_consumearound" =>					'Read the Docs about this option. You must be running romonitor for it to work',
	"podcast_display_nud" =>				'新的, 未听的, & 已下载的',
	"label_usetrackimages" =>				'扫描每个曲目以获取图片',
	"label_unusetrackimages" =>				'不要扫描每个曲目获取图片',
	"config_audiobook_tags" =>				'添加标签时将曲目设置为听书',
	"label_random_order" => 				'随机顺序',
	"label_remove_all" => 					'移除所有',
	"manage_bgs" =>							'管理背景图片',
	"label_bg_global" =>					'应用到所有浏览器',
	"label_bg_only" =>						'只用于当前浏览器',
	"label_playfromhere" =>					'从这里开始播放',
	"config_browserid" =>					'浏览器ID',
	"button_clearwishlist" =>				'清空愿望单',
	"label_mfyc" =>							'你的集合中的音乐',
	"label_mfsp" =>							'Spotify的音乐',
	"label_mfe" =>							'所有来源的音乐',
	"label_playqueue" =>					'播放队列',
	"label_numplays" =>						'%s 播放次数',
	"button_bookmarks" =>					'添加书签',
	"label_remcur" =>						'移除当前图片',
	"button_nextbg" => 						'下一个背景图片',
	"button_delbg" => 						'删除当前背景图片',
	"label_name" =>							'名称',
	"play_even_if_playing" =>				'即使正在播放',
	"setup_mpd_special"	=>					'MPD特定选项',
	"label_ui_defaults" =>					'缺省',
	"button_save_defaults" =>				'保存为所有浏览器的缺省设置',
	"label_recommenddesc" =>				'根据你最近的收听情况推荐的一个电台。由 %s 驱动',
	"label_rmixdesc" =>						'根据你喜欢的歌手和相似的歌手推荐的一个电台。由 %s 驱动',
	"config_stupid_round_corners" =>		'屏幕底部填充（有助于有圆角或操控受阻的手机）',
	"config_clearfirst" =>					'开始前清空播放队列',
	"label_classicalrules" =>				'古典音乐排序规则',
	"config_classicalrules" =>				'使用不同的规则来排序古典音乐',
	"config_sortbyartist" =>				"使用曲目歌手作为排序歌手",
	"config_sortbycomposer" =>				"使用作曲作为排序歌手",
	"label_classicalgenre" =>				"使用类型检测古典音乐",
	"label_classicalfolder" =>				"使用目录路径检测古典音乐",
	"label_showallresults" =>				"显示所有曲目",
	"label_bythisartist" =>					"在集合中此歌手的作品"
	"label_generic_error" =>				"未知错误",
	"label_genrebyartist" =>				"年代 (按歌手)",
	"label_ratingbyartist" =>				"评级 (按歌手)",
	"label_tagbyartist" =>					"Tag (按歌手)",
	"label_playtaggedwith" =>				'播放带有"%s*"标记的曲目',
	"config_headerbar" =>					'图标栏位置'

	// ----------------------------------------------------
	// Proobaly Unused
	// ----------------------------------------------------
	//"label_smartsetup" =>					"Preparing. Please Wait A Moment....",

]);

?>
