var sources = new Array();
var update_load_timer = 0;
var update_load_timer_running = false;
var last_selected_element = null;
var serverTimeOffset = 0;
var resizeTimer = null;
var menuOpeners = new Array();
const masonry_gutter = 8;
var coverscraper;
var lastfm;